import "server-only";
import { getMobileSession } from "@/lib/mobile-auth";
import { getAuditLogRequestData } from "@/lib/audit-log-request";
import { getLoginRequestInfo } from "@/lib/login-history-core";
import { YouthError, youthId, youthObject, youthQuery, youthPage, readYouthJson, parseYouthCreate, parseYouthPatch, parseYouthExtension } from "@/lib/mobile-youth-core";
import { getMobileYouthList, getMobileYouthDetail, viewMobileYouth, getMobileYouthViewStatus, getMobileYouthHistory } from "@/lib/youth-mobile-queries";
import { createMobileYouth, patchMobileYouth, extendMobileYouth, getYouthMutationStatus } from "@/lib/youth-mobile-mutations";
import type { YouthContext } from "@/lib/youth-mobile-context";
export const youthPrivateHeaders = { "Cache-Control": "private, no-store", Pragma: "no-cache", Vary: "Authorization, Cookie", "X-Content-Type-Options": "nosniff" };
export const youthJson = (value: unknown, status = 200) => Response.json(value, { status, headers: youthPrivateHeaders });
export function youthFailure(error: unknown) { return error instanceof YouthError ? youthJson({ error: error.message, code: error.code, ...(error.fields ? { fields: error.fields } : {}) }, error.status) : youthJson({ error: "청소년 요청을 처리하지 못했습니다. 같은 요청으로 다시 확인해 주세요.", code: "REQUEST_UNAVAILABLE" }, 503); }
export type YouthRouteAction = "list" | "detail" | "details" | "contacts" | "view-status" | "history" | "create" | "patch" | "extension" | "mutation-status";
export async function mobileYouthResponse(request: Request, action: YouthRouteAction, id?: string | (() => Promise<string>)) { try { const session = await getMobileSession(request); if (!session) throw new YouthError("인증이 필요합니다.", "UNAUTHORIZED", 401); const context: YouthContext = { actorId: session.userId, requestData: getAuditLogRequestData(getLoginRequestInfo(request.headers)), client: "mobile" }, target = id ? youthId(typeof id === "function" ? await id() : id, ["view-status", "mutation-status"].includes(action)) : undefined, url = new URL(request.url); if (action === "list") { const query = youthQuery(url, ["q", "page"]); return youthJson(await getMobileYouthList(context, { q: (query.q ?? "").trim(), page: youthPage(query.page) })); } if (action === "history") { const query = youthQuery(url, ["page"]); return youthJson(await getMobileYouthHistory(context, target!, youthPage(query.page))); } youthQuery(url); if (action === "detail") return youthJson(await getMobileYouthDetail(context, target!)); if (action === "view-status") return youthJson(await getMobileYouthViewStatus(context, target!)); if (action === "mutation-status") return youthJson(await getYouthMutationStatus(context, target!)); const body = await readYouthJson(request, action === "create" || action === "patch" ? 8388608 : 65536); if (action === "details" || action === "contacts") { const raw = youthObject(body, ["requestId"]); return youthJson(await viewMobileYouth(context, target!, action, youthId(raw.requestId, true))); } if (action === "create") { const result = await createMobileYouth(context, parseYouthCreate(body)); return youthJson(result, result.replayed ? 200 : 201); } if (action === "patch") return youthJson(await patchMobileYouth(context, target!, parseYouthPatch(body))); if (action === "extension") return youthJson(await extendMobileYouth(context, target!, parseYouthExtension(body))); throw new YouthError(); } catch (error) { return youthFailure(error); } }
