import "server-only";
import { AuditAction, type Prisma } from "@/generated/prisma/client";
import { YouthError, nextYouthTimestamp, youthId, type YouthCreateBody, type YouthPatchBody, type YouthExtensionBody, type YouthProfilePatch, type YouthBasicDetail } from "@/lib/mobile-youth-core";
import { assertYouthPermission, lockOperationalYouth, mapYouthBasic, withYouthMutation, withYouthRead, youthPermissions, youthMutationEnvelope, youthScopeSelect, type YouthActor, type YouthContext } from "@/lib/youth-mobile-context";
import { youthBasicDetail } from "@/lib/youth-mobile-queries";
import { isRestrictedYouth } from "@/lib/youth-retention-core";

const profileSelect = { ...youthScopeSelect, birthDate: true, initialDischargeDate: true, phone: true, familyContact: true, familyPhone: true, familyRelationship: true, familyContacts: { orderBy: [{ createdAt: "asc" }, { id: "asc" }], select: { id: true, relationship: true, phone: true } }, mathSettlement: { select: { reopenedAt: true } } } satisfies Prisma.YouthSelect;
function assertPatchPermission(actor: YouthActor, patch: YouthProfilePatch) { if (Object.hasOwn(patch, "birthDate")) assertYouthPermission(actor, "canViewYouthDetails"); if (Object.hasOwn(patch, "phone") || Object.hasOwn(patch, "familyContacts")) assertYouthPermission(actor, "canViewYouthContacts"); }
function assertVersion(actual: Date, expected: string) { if (actual.toISOString() !== expected) throw new YouthError("다른 사용자가 먼저 청소년 정보를 수정했습니다. 최신 정보를 확인한 후 다시 시도해 주세요.", "YOUTH_CONFLICT", 409); }
async function uniqueName(tx: Prisma.TransactionClient, name: string, currentId?: string) { const existing = await tx.youth.findUnique({ where: { name }, select: { id: true } }); if (existing && existing.id !== currentId) throw new YouthError("이미 등록된 청소년 이름입니다.", "VALIDATION_ERROR", 400, { name: "이미 등록된 이름입니다." }); }
export async function createMobileYouth(context: YouthContext, input: YouthCreateBody) {
  return withYouthMutation(context, { operation: "profile.create", requestId: input.requestId, payload: input, targetType: "Youth", replay: (tx, actor, today, _now, receipt) => youthBasicDetail(tx, actor, today, receipt.targetId) }, async (tx, actor, today, now, receiptId) => {
    await uniqueName(tx, input.name); const family = input.familyContacts ?? [], first = family[0];
    const row = await tx.youth.create({ data: { name: input.name, admissionDate: input.admissionDate, birthDate: input.birthDate ?? null, age: null, initialDischargeDate: input.dischargeDate, dischargeDate: input.dischargeDate, phone: input.phone ?? null, familyRelationship: first?.relationship ?? null, familyPhone: first?.phone ?? null, familyContact: first?.phone ?? null, updatedAt: now }, select: youthScopeSelect });
    if (family.length) await tx.youthFamilyContact.createMany({ data: family.map(contact => ({ ...contact, youthId: row.id })) });
    if (input.uploadIds.length) { const { consumeYouthDecisionUploads } = await import("@/lib/youth-decision-uploads"); await consumeYouthDecisionUploads(tx, actor.id, row.id, receiptId, input.uploadIds, now, { allowUnbound: true }); }
    await tx.auditLog.create({ data: { actorId: actor.id, ...context.requestData, action: AuditAction.CREATE_YOUTH, targetType: "Youth", targetId: row.id, message: `${row.name} 청소년을 등록했습니다.`, metadata: { familyContactCount: family.length, hasPhone: Boolean(input.phone), decisionDocumentCount: input.uploadIds.length }, createdAt: now } });
    return { targetId: row.id, committedUpdatedAt: row.updatedAt, result: { today, permissions: youthPermissions(actor), youth: mapYouthBasic(row) } };
  });
}
export async function patchMobileYouth(context: YouthContext, id: string, input: YouthPatchBody & { uploadIds?: string[] }) {
  youthId(id);
  return withYouthMutation(context, { operation: "profile.patch", requestId: input.requestId, payload: input, youthId: id, targetType: "Youth", targetId: id, replay: async (tx, actor, today) => { assertPatchPermission(actor, input.patch); return youthBasicDetail(tx, actor, today, id); } }, async (tx, actor, today, now, receiptId) => {
    assertPatchPermission(actor, input.patch); const before = await tx.youth.findUniqueOrThrow({ where: { id }, select: profileSelect }); assertVersion(before.updatedAt, input.expectedUpdatedAt);
    const patch = input.patch; if (patch.name !== undefined) await uniqueName(tx, patch.name, id);
    if (Object.hasOwn(patch, "admissionDate") && before.mathSettlement?.reopenedAt === null && patch.admissionDate !== before.admissionDate) throw new YouthError("수학 보상 정산이 확정되어 입소일을 바꿀 수 없습니다. 먼저 관리자 해제를 하세요.", "VALIDATION_ERROR", 400, { admissionDate: "정산 확정 후 입소일을 바꿀 수 없습니다." });
    const first = patch.familyContacts?.[0], data = { ...("name" in patch ? { name: patch.name } : {}), ...("admissionDate" in patch ? { admissionDate: patch.admissionDate } : {}), ...("birthDate" in patch ? { birthDate: patch.birthDate, age: null } : {}), ...("phone" in patch ? { phone: patch.phone } : {}), ...("familyContacts" in patch ? { familyRelationship: first?.relationship ?? null, familyPhone: first?.phone ?? null, familyContact: first?.phone ?? null } : {}), updatedAt: nextYouthTimestamp(before.updatedAt, now) } satisfies Prisma.YouthUpdateManyMutationInput;
    const update = await tx.youth.updateMany({ where: { id, updatedAt: before.updatedAt }, data }); if (update.count !== 1) throw new YouthError("청소년 정보가 변경되었습니다. 최신 정보를 확인해 주세요.", "YOUTH_CONFLICT", 409);
    if (patch.familyContacts !== undefined) { await tx.youthFamilyContact.deleteMany({ where: { youthId: id } }); if (patch.familyContacts.length) await tx.youthFamilyContact.createMany({ data: patch.familyContacts.map(contact => ({ ...contact, youthId: id })) }); }
    if (input.uploadIds?.length) { const { consumeYouthDecisionUploads } = await import("@/lib/youth-decision-uploads"); await consumeYouthDecisionUploads(tx, actor.id, id, receiptId, input.uploadIds, now); }
    const labels: Record<string, string> = { name: "이름", admissionDate: "입소 날짜", birthDate: "생년월일", phone: "핸드폰 번호", familyContacts: "가족 연락처" }, familyText = (contacts: Array<{ relationship: string | null; phone: string | null }>) => contacts.length ? contacts.map(contact => `${contact.relationship || "관계 미등록"}(${contact.phone || "연락처 미등록"})`).join(", ") : "미등록";
    const changes = Object.keys(patch).flatMap(field => { const from = field === "familyContacts" ? familyText(before.familyContacts) : String(before[field as keyof typeof before] ?? "미등록"), value = patch[field as keyof YouthProfilePatch], to = field === "familyContacts" ? familyText(patch.familyContacts!) : String(value ?? "미등록"); return from === to ? [] : [{ field, label: labels[field], from, to }]; });
    const name = patch.name ?? before.name; await tx.auditLog.create({ data: { actorId: actor.id, ...context.requestData, action: AuditAction.UPDATE_YOUTH, targetType: "Youth", targetId: id, message: [`${name} 청소년 기본 정보를 수정했습니다.`, ...changes.map(change => `- ${change.label}: ${change.from} → ${change.to}`), ...(changes.length ? [] : ["- 변경된 항목이 없습니다."])].join("\n"), metadata: { changes, addedDocumentNames: [], familyContactCount: patch.familyContacts?.length ?? before.familyContacts.length, hasPhone: Boolean(patch.phone === undefined ? before.phone : patch.phone), decisionDocumentCount: input.uploadIds?.length ?? 0 }, createdAt: now } });
    const result = await youthBasicDetail(tx, actor, today, id); return { targetId: id, committedUpdatedAt: new Date(result.youth.updatedAt), result };
  });
}
export async function extendMobileYouth(context: YouthContext, id: string, input: YouthExtensionBody) {
  youthId(id);
  return withYouthMutation(context, { operation: "profile.extend", requestId: input.requestId, payload: input, youthId: id, targetType: "Youth", targetId: id, replay: (tx, actor, today) => youthBasicDetail(tx, actor, today, id) }, async (tx, actor, today, now) => {
    const before = await tx.youth.findUniqueOrThrow({ where: { id }, select: { ...profileSelect, dischargeExtensions: { select: { extensionOrder: true } } } }); assertVersion(before.updatedAt, input.expectedUpdatedAt);
    if (before.mathSettlement?.reopenedAt === null) throw new YouthError("수학 보상 정산이 확정되어 퇴소 예정일을 바꿀 수 없습니다. 먼저 관리자 해제를 하세요.", "VALIDATION_ERROR", 400);
    const initial = before.initialDischargeDate ?? before.dischargeDate; if (!initial || !before.dischargeDate) throw new YouthError("기본 퇴소 예정일이 등록된 청소년만 퇴소 연장할 수 있습니다.", "VALIDATION_ERROR", 400);
    if (before.dischargeExtensions.length >= 2) throw new YouthError("퇴소 연장은 최대 2회까지만 등록할 수 있습니다.", "VALIDATION_ERROR", 400);
    if (input.extendedDischargeDate <= before.dischargeDate) throw new YouthError("연장 퇴소일은 현재 적용 퇴소 예정일보다 뒤여야 합니다.", "VALIDATION_ERROR", 400, { extendedDischargeDate: "현재 퇴소 예정일보다 뒤여야 합니다." });
    const order = before.dischargeExtensions.length + 1, extension = await tx.youthDischargeExtension.create({ data: { youthId: id, processedById: actor.id, extensionOrder: order, previousDischargeDate: before.dischargeDate, extendedDischargeDate: input.extendedDischargeDate, reason: input.reason, processedAt: now } });
    const token = nextYouthTimestamp(before.updatedAt, now), updated = await tx.youth.updateMany({ where: { id, updatedAt: before.updatedAt }, data: { initialDischargeDate: initial, dischargeDate: input.extendedDischargeDate, updatedAt: token } }); if (updated.count !== 1) throw new YouthError("청소년 정보가 변경되었습니다.", "YOUTH_CONFLICT", 409);
    await tx.auditLog.create({ data: { actorId: actor.id, ...context.requestData, action: AuditAction.EXTEND_YOUTH_DISCHARGE, targetType: "Youth", targetId: id, message: `${before.name} 청소년의 퇴소 예정일을 ${order}차 연장했습니다.`, metadata: { extensionOrder: order, previousDischargeDate: before.dischargeDate, extendedDischargeDate: input.extendedDischargeDate, reason: input.reason, processedAt: extension.processedAt.toISOString(), processedBy: actor.name }, createdAt: now } });
    return { targetId: id, committedUpdatedAt: token, committedTargets: { extensionId: extension.id }, result: await youthBasicDetail(tx, actor, today, id) };
  });
}
export async function getYouthMutationStatus(context: YouthContext, requestId: string) { return withYouthRead(context, async (tx, actor, today) => { assertYouthPermission(actor, "canManageYouth"); const receipt = await tx.youthMutationReceipt.findUnique({ where: { actorId_requestId: { actorId: actor.id, requestId: youthId(requestId, true) } } }); if (!receipt) throw new YouthError("요청 결과를 찾을 수 없습니다.", "NOT_FOUND", 404); let unavailable = receipt.state !== "committed"; if (receipt.youthId) { if (receipt.operation === "profile.create") { const parent = await tx.youth.findUnique({ where: { id: receipt.youthId }, select: youthScopeSelect }); unavailable ||= !parent || isRestrictedYouth(parent, today); } else await lockOperationalYouth(tx, receipt.youthId, today); } const result: YouthBasicDetail | null = !unavailable && receipt.youthId && receipt.operation.startsWith("profile.") ? await youthBasicDetail(tx, actor, today, receipt.youthId) : null; return youthMutationEnvelope(receipt, result, true, unavailable); }); }
