import "server-only";
import { AuditAction, Prisma } from "@/generated/prisma/client";
import { YouthError, youthId, isMobileYouthDate, type YouthBasicDetail, type YouthContacts, type YouthSensitiveDetails } from "@/lib/mobile-youth-core";
import { youthOperationalWhere } from "@/lib/youth-retention-core";
import { assertYouthPermission, lockOperationalYouth, lockYouthRequest, mapYouthBasic, withYouthRead, youthTransaction, youthPermissions, type YouthContext, type YouthActor, youthTransactionConflict, youthReceiptConflict } from "@/lib/youth-mobile-context";

export async function getMobileYouthList(context: YouthContext, input: { q: string; page: number }) { return withYouthRead(context, async (tx, actor, today) => { const where: Prisma.YouthWhereInput = { AND: [youthOperationalWhere(today), ...(input.q ? [{ name: { contains: input.q, mode: "insensitive" as const } }] : [])] }, total = await tx.youth.count({ where }), pageSize = 20 as const, totalPages = Math.max(1, Math.ceil(total / pageSize)), page = Math.min(input.page, totalPages), rows = await tx.youth.findMany({ where, select: { id: true, name: true, admissionDate: true, dischargeDate: true, updatedAt: true }, orderBy: [{ admissionDate: { sort: "asc", nulls: "last" } }, { name: "asc" }, { id: "asc" }], skip: (page - 1) * pageSize, take: pageSize }); return { today, permissions: youthPermissions(actor), q: input.q, page, pageSize, total, totalPages, items: rows.map(mapYouthBasic) }; }); }
export async function youthBasicDetail(tx: Prisma.TransactionClient, actor: YouthActor, today: string, id: string): Promise<YouthBasicDetail> { const parent = await lockOperationalYouth(tx, id, today); return { today, permissions: youthPermissions(actor), youth: mapYouthBasic(parent) }; }
export async function getMobileYouthDetail(context: YouthContext, id: string) { return withYouthRead(context, (tx, actor, today) => youthBasicDetail(tx, actor, today, youthId(id))); }
const contactSelect = { id: true, phone: true, familyContact: true, familyPhone: true, familyRelationship: true, familyContacts: { orderBy: [{ createdAt: "asc" }, { id: "asc" }], select: { id: true, relationship: true, phone: true } } } satisfies Prisma.YouthSelect;
const blank = (value: string | null) => value?.trim() || null;
export async function youthContacts(tx: Prisma.TransactionClient, id: string): Promise<YouthContacts> { const row = await tx.youth.findUniqueOrThrow({ where: { id }, select: contactSelect }), phone = blank(row.phone), legacyPhone = blank(row.familyPhone) ?? blank(row.familyContact), legacyRelationship = blank(row.familyRelationship); return { phone, familyContacts: row.familyContacts.length ? row.familyContacts.map(contact => ({ id: contact.id, phone: blank(contact.phone), relationship: blank(contact.relationship) })) : legacyPhone || legacyRelationship ? [{ id: "legacy-family-" + row.id, phone: legacyPhone, relationship: legacyRelationship }] : [] }; }
export async function youthDetails(tx: Prisma.TransactionClient, id: string, today: string): Promise<YouthSensitiveDetails> { const row = await tx.youth.findUniqueOrThrow({ where: { id }, select: { birthDate: true, age: true, initialDischargeDate: true, dischargeDate: true, dischargeExtensions: { orderBy: [{ extensionOrder: "asc" }, { id: "asc" }], select: { id: true, extensionOrder: true, previousDischargeDate: true, extendedDischargeDate: true, reason: true, processedAt: true, processedBy: { select: { id: true, name: true } } } } } }); let age = row.age, koreanAge: number | null = null; if (isMobileYouthDate(row.birthDate)) { const birth = row.birthDate, years = Number(today.slice(0, 4)) - Number(birth.slice(0, 4)); age = years - Number(today.slice(5) < birth.slice(5)); if (age < 0) age = null; koreanAge = years >= 0 ? years + 1 : null; } return { birthDate: row.birthDate, age, koreanAge, initialDischargeDate: row.initialDischargeDate ?? row.dischargeDate, dischargeExtensions: row.dischargeExtensions.map(extension => ({ ...extension, processedAt: extension.processedAt.toISOString() })) }; }
export type YouthPrivateKind = "details" | "contacts";
const privatePermission = (kind: YouthPrivateKind) => kind === "details" ? "canViewYouthDetails" as const : "canViewYouthContacts" as const;
function assertViewWindow(receipt: { state: string; disclosureUntil: Date | null; sourceUpdatedAt: Date | null }, updatedAt: Date, now: Date) { if (receipt.state !== "recorded" || !receipt.disclosureUntil || receipt.disclosureUntil <= now) throw new YouthError("열람 시간이 만료되었습니다. 다시 열람해 주세요.", "VIEW_REQUEST_EXPIRED", 410); if (!receipt.sourceUpdatedAt || receipt.sourceUpdatedAt.getTime() !== updatedAt.getTime()) throw new YouthError("정보가 변경되었습니다. 다시 열람해 주세요.", "VIEW_SNAPSHOT_CHANGED", 409); }
export async function viewMobileYouth(context: YouthContext, id: string, kind: YouthPrivateKind, requestId: string) {
  youthId(id); youthId(requestId, true);
  return youthTransaction(context, async (tx, actor, today, now) => {
    assertYouthPermission(actor, privatePermission(kind)); const parent = await lockOperationalYouth(tx, id, today, { write: true }); await lockYouthRequest(tx, actor.id, requestId, "youth-view");
    let receipt = await tx.youthViewRequest.findUnique({ where: { actorId_requestId: { actorId: actor.id, requestId } } }); const replayed = Boolean(receipt);
    if (receipt) { if (receipt.youthId !== id || receipt.kind !== kind || receipt.documentId !== null) throw new YouthError("같은 열람 요청의 대상이 변경되었습니다.", "REQUEST_CONFLICT", 409); assertViewWindow(receipt, parent.updatedAt, now); }
    else {
      await lockYouthRequest(tx, actor.id, id + ":" + kind, "youth-audit");
      const action = kind === "details" ? AuditAction.VIEW_YOUTH_DETAIL : AuditAction.VIEW_YOUTH_CONTACT;
      let audit = kind === "details" ? await tx.auditLog.findFirst({ where: { actorId: actor.id, action, targetType: "Youth", targetId: id, createdAt: { gte: new Date(now.getTime() - 1800000) } }, orderBy: [{ createdAt: "desc" }, { id: "desc" }], select: { id: true, createdAt: true } }) : null;
      try { if (!audit) audit = await tx.auditLog.create({ data: { actorId: actor.id, ...context.requestData, action, targetType: "Youth", targetId: id, message: `${parent.name} 청소년의 ${kind === "details" ? "상세정보" : "연락처"}를 열람했습니다.`, metadata: { youthId: id }, createdAt: now }, select: { id: true, createdAt: true } }); receipt = await tx.youthViewRequest.create({ data: { actorId: actor.id, requestId, youthId: id, kind, sourceUpdatedAt: parent.updatedAt, auditLogId: audit.id, auditedAt: audit.createdAt, disclosureUntil: new Date(now.getTime() + 300000), createdAt: now, state: "recorded" } }); } catch (error) { if (error instanceof YouthError || youthTransactionConflict(error) || youthReceiptConflict(error, "YouthViewRequest")) throw error; throw new YouthError("열람 기록을 저장하지 못했습니다. 다시 시도해 주세요.", "AUDIT_UNAVAILABLE", 503); }
    }
    const envelope = { ok: true as const, replayed, today, permissions: youthPermissions(actor), youthId: id, sourceUpdatedAt: receipt!.sourceUpdatedAt!.toISOString(), auditedAt: receipt!.auditedAt!.toISOString(), serverNow: now.toISOString(), disclosureUntil: receipt!.disclosureUntil!.toISOString() };
    return kind === "details" ? { ...envelope, details: await youthDetails(tx, id, today) } : { ...envelope, contacts: await youthContacts(tx, id) };
  }, { write: true, receiptModel: "YouthViewRequest" });
}
export async function getMobileYouthViewStatus(context: YouthContext, requestId: string) { return withYouthRead(context, async (tx, actor, today, now) => { const receipt = await tx.youthViewRequest.findUnique({ where: { actorId_requestId: { actorId: actor.id, requestId: youthId(requestId, true) } } }); if (!receipt || receipt.kind !== "details" && receipt.kind !== "contacts") throw new YouthError("열람 요청을 찾을 수 없습니다.", "NOT_FOUND", 404); assertYouthPermission(actor, privatePermission(receipt.kind)); const parent = await lockOperationalYouth(tx, receipt.youthId, today); if (receipt.state !== "recorded") throw new YouthError("열람 요청을 찾을 수 없습니다.", "NOT_FOUND", 404); if (receipt.disclosureUntil && receipt.disclosureUntil > now && receipt.sourceUpdatedAt?.getTime() !== parent.updatedAt.getTime()) throw new YouthError("정보가 변경되었습니다. 다시 열람해 주세요.", "VIEW_SNAPSHOT_CHANGED", 409); return { today, permissions: youthPermissions(actor), kind: receipt.kind, youthId: receipt.youthId, state: receipt.disclosureUntil && receipt.disclosureUntil > now ? "recorded" as const : "expired" as const, auditedAt: receipt.auditedAt?.toISOString() ?? null, sourceUpdatedAt: receipt.sourceUpdatedAt?.toISOString() ?? null, serverNow: now.toISOString(), disclosureUntil: receipt.disclosureUntil?.toISOString() ?? null }; }); }
const labels: Record<string, string> = { name: "이름", admissionDate: "입소 날짜", dischargeDate: "퇴소 예정일", birthDate: "생년월일", initialDischargeDate: "기본 퇴소 예정일", phone: "핸드폰 번호", familyContacts: "가족 연락처" };
function safeChanges(metadata: Prisma.JsonValue | null, actor: YouthActor): Array<{ field: string; label: string; from: string; to: string }> {
  if (!metadata || typeof metadata !== "object" || Array.isArray(metadata)) return [];
  const permission = youthPermissions(actor), raw = metadata.changes;
  const changes = !Array.isArray(raw) ? [] : raw.flatMap(change => {
    if (!change || typeof change !== "object" || Array.isArray(change)) return [];
    const { field, from, to } = change;
    if (typeof field !== "string" || !Object.hasOwn(labels, field) || typeof from !== "string" || typeof to !== "string" || ["birthDate", "initialDischargeDate"].includes(field) && !permission.canViewYouthDetails || ["phone", "familyContacts"].includes(field) && !permission.canViewYouthContacts) return [];
    return [{ field, label: labels[field], from, to }];
  });
  // A closed summary cannot disclose filenames or grant file visibility through basic history.
  const documentOperations: Record<string, { label: string; verb: string }> = {
    "youth.documents.add": { label: "결정문 첨부", verb: "첨부" },
    "youth.documents.delete": { label: "결정문 삭제", verb: "삭제" },
    "youth.documents.reencrypt": { label: "결정문 재암호화", verb: "재암호화" },
  };
  if (permission.canDownloadYouthDocuments && typeof metadata.changeType === "string" && Object.hasOwn(documentOperations, metadata.changeType)) {
    const operation = documentOperations[metadata.changeType], count = metadata.decisionDocumentCount;
    changes.push({ field: "decisionDocuments", label: operation.label, from: "—", to: typeof count === "number" && Number.isSafeInteger(count) && count >= 0 ? `${count}개 ${operation.verb}` : `${operation.verb} 처리` });
  }
  return changes;
}
export async function getMobileYouthHistory(context: YouthContext, id: string, requestedPage: number) { return withYouthRead(context, async (tx, actor, today) => { await lockOperationalYouth(tx, youthId(id), today); const where = { targetType: "Youth", targetId: id, action: { in: [AuditAction.CREATE_YOUTH, AuditAction.UPDATE_YOUTH, AuditAction.EXTEND_YOUTH_DISCHARGE] } }, total = await tx.auditLog.count({ where }), pageSize = 5, totalPages = Math.max(1, Math.ceil(total / pageSize)), page = Math.min(requestedPage, totalPages), rows = await tx.auditLog.findMany({ where, orderBy: [{ createdAt: "desc" }, { id: "desc" }], take: pageSize, skip: (page - 1) * pageSize, select: { id: true, action: true, createdAt: true, metadata: true, actor: { select: { id: true, name: true } } } }); return { today, permissions: youthPermissions(actor), youthId: id, page, pageSize, total, totalPages, items: rows.map(row => ({ id: row.id, action: row.action, createdAt: row.createdAt.toISOString(), actor: row.actor ? { id: row.actor.id, name: row.actor.name } : null, changes: safeChanges(row.metadata, actor) })) }; }); }

/** Existing web projection; mobile never uses it. */
export async function getWebYouthProfile(context: YouthContext, id: string): Promise<import("@/lib/youth-management-core").YouthProfile> { return withYouthRead(context, async (tx, actor, today) => {
  assertYouthPermission(actor, "canManageYouth"); const parent = await lockOperationalYouth(tx, id, today), permission = youthPermissions(actor), details = permission.canViewYouthDetails ? await youthDetails(tx, id, today) : null, contact = permission.canViewYouthContacts ? await youthContacts(tx, id) : null, documents = permission.canDownloadYouthDocuments ? await tx.youthDecisionDocument.findMany({ where: { youthId: id }, select: { id: true, originalName: true, size: true, createdAt: true, updatedAt: true }, orderBy: [{ createdAt: "asc" }, { id: "asc" }] }) : [];
  const hasPhone = Boolean(contact?.phone), hasFamilyContact = Boolean(contact?.familyContacts.some(row => row.phone || row.relationship));
  return { ...mapYouthBasic(parent), birthDate: details?.birthDate ?? null, age: details?.age ?? null, ...(details ? { initialDischargeDate: details.initialDischargeDate, dischargeExtensions: details.dischargeExtensions } : {}), phone: null, familyContacts: [], hasPhone, hasFamilyContact, hasContact: hasPhone || hasFamilyContact, decisionDocuments: documents.map(file => ({ ...file, createdAt: file.createdAt.toISOString(), updatedAt: file.updatedAt.toISOString() })), notes: [] };
}); }
