ALTER TYPE "AuditAction" ADD VALUE 'CREATE_YOUTH';
ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_YOUTH';
ALTER TYPE "AuditAction" ADD VALUE 'UPDATE_YOUTH_NOTE';
ALTER TYPE "AuditAction" ADD VALUE 'DELETE_YOUTH_NOTE';
