name: Build Bajaul staff Android app

jobs:
  build_android:
    type: build
    env:
      EAS_NO_VCS: '1'
    params:
      platform: android
      profile: staff
    hooks:
      before_install_node_modules:
        - run: set-env EAS_PROJECT_ROOT "$PWD"
