name: Build Bajaul private Google Play app

jobs:
  build_android:
    type: build
    env:
      EAS_NO_VCS: '1'
    params:
      platform: android
      profile: private-store
    hooks:
      before_install_node_modules:
        - run: set-env EAS_PROJECT_ROOT "$PWD"
      after_install_node_modules:
        - run: npm run lint
        - run: npm run typecheck
