import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { after, beforeEach, test } from "node:test";
import ts from "typescript";
import { Prisma } from "../src/generated/prisma/client.ts";
import { prepareAttachmentFiles } from "../src/lib/attachment-storage.ts";
import { getStaffChatToday, isStaffChatEmployeeActive } from "../src/lib/staff-chat-core.ts";
import { readMobileChatJson, readMobileChatFileForm, readMobileChatChunk, mobileChatUploadJsonMaxBytes } from "../src/lib/mobile-chat-core.ts";
// Actual mobile routes, auth, shared domains, policy and parsers; DB/storage only are isolated.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row = Record<string, any>;
const today=getStaffChatToday(),token="t".repeat(43),h:Row={};
const hash=(value:Uint8Array|string)=>createHash("sha256").update(value).digest("hex");
function matches(row:Row,where:Row={}):boolean{return Object.entries(where).every(([key,value])=>{
 if(key==="AND")return(Array.isArray(value)?value:[value]).every((part:Row)=>matches(row,part));if(key==="OR")return value.some((part:Row)=>matches(row,part));
 if(key==="senderId_requestId")return matches(row,value);if(key==="message")return matches(h.messages.find((r:Row)=>r.id===row.messageId)??{},value);
 const got=row[key];if(value===null||typeof value!=="object"||value instanceof Date)return got instanceof Date&&value instanceof Date?got.getTime()===value.getTime():got===value;
 if("not"in value&&got===value.not)return false;if("gt"in value&&!(got!=null&&got>value.gt))return false;if("lt"in value&&!(got!=null&&got<value.lt))return false;if("lte"in value&&!(got!=null&&got<=value.lte))return false;return true;
});}
function project(row:Row|undefined,select?:Row):Row|null{if(!row)return null;if(!select)return structuredClone(row);return Object.fromEntries(Object.entries(select).filter(([,yes])=>yes).map(([key,value])=>{
 const got=key==="attachment"?h.attachments.find((r:Row)=>r.messageId===row.id):key==="message"?h.messages.find((r:Row)=>r.id===row.messageId):row[key];return[key,value===true?structuredClone(got):got==null?got:project(got,value.select)];
}));}
function many(rows:Row[],args:Row){const found=rows.filter(row=>matches(row,args.where));if(args.orderBy?.sequence)found.sort((a,b)=>a.sequence>b.sequence?(args.orderBy.sequence==="desc"?-1:1):a.sequence<b.sequence?(args.orderBy.sequence==="desc"?1:-1):0);return found.slice(0,args.take).map(row=>project(row,args.select));}
function write(){h.mutations++;}
const db:Row={
 mobileSession:{async findUnique({where}:Row){h.sessionReads++;return where.tokenHash===hash(token)?h.session:null;}},
 user:{async findUnique({where,select}:Row){h.userReads++;return project(h.users.find((r:Row)=>matches(r,where)),select);},async findMany(args:Row){return h.users.filter((u:Row)=>u.id!==h.session.userId).filter((u:Row)=>isStaffChatEmployeeActive(u,today)||h.messages.some((r:Row)=>r.senderId===u.id&&r.recipientId===h.session.userId||r.recipientId===u.id&&r.senderId===h.session.userId)).map((u:Row)=>({...u,sentChatMessages:many(h.messages,{...args.select.sentChatMessages,where:{senderId:u.id,...args.select.sentChatMessages.where}}),receivedChatMessages:many(h.messages,{...args.select.receivedChatMessages,where:{recipientId:u.id,...args.select.receivedChatMessages.where}}),_count:{sentChatMessages:h.messages.filter((r:Row)=>r.senderId===u.id&&matches(r,args.select._count.select.sentChatMessages.where)).length}}));}},
 attachmentPolicy:{async findUnique(){if(h.failGlobalPolicy)throw Error("Global policy must not be read");h.policyReads++;return h.policy?structuredClone(h.policy):null;},async upsert({create}:Row){if(h.failGlobalPolicy)throw Error("Global policy must not be written");write();h.policy=create;return create;}},
 staffChatMessage:{async findUnique({where,select}:Row){return project(h.messages.find((r:Row)=>matches(r,where)),select);},async findFirst(args:Row){return many(h.messages,{...args,take:1})[0]??null;},async findMany(args:Row){return many(h.messages,args);},async create({data,select}:Row){write();assert(h.locked);if(h.messages.some((r:Row)=>r.senderId===data.senderId&&r.requestId===data.requestId))throw new Prisma.PrismaClientKnownRequestError("duplicate",{code:"P2002",clientVersion:"7.10.0"});const{attachment,...fields}=data;const row={id:`message-${++h.nextId}`,sequence:BigInt(h.nextId)+9007199254740993n,createdAt:new Date(),readAt:null,...fields};h.messages.push(row);if(attachment)h.attachments.push({id:`attachment-${row.id}`,messageId:row.id,downloadRequestId:null,downloadToken:null,downloadExpiresAt:null,downloadedAt:null,deletionRequestedAt:null,deletedAt:null,...attachment.create});return project(row,select);},async updateMany({where,data}:Row){assert(h.locked);write();const rows=h.messages.filter((r:Row)=>matches(r,where));rows.forEach((r:Row)=>Object.assign(r,data));return{count:rows.length};}},
 staffChatAttachment:{async findUnique({where,select}:Row){return project(h.attachments.find((r:Row)=>matches(r,where)),select);},async findFirst({where,select}:Row){return project(h.attachments.find((r:Row)=>matches(r,where)),select);},async findMany(args:Row){h.cleanupReads++;return many(h.attachments,args);},async update({where,data,select}:Row){write();const row=h.attachments.find((r:Row)=>matches(r,where));assert(row);Object.assign(row,data);return project(row,select);},async updateMany({where,data}:Row){if(h.failTombstone)throw Error("PRIVATE_DATABASE_FAILURE");write();const rows=h.attachments.filter((r:Row)=>matches(r,where));rows.forEach((r:Row)=>Object.assign(r,data));return{count:rows.length};}},
 staffChatUpload:{async findUnique({where,select}:Row){return project(h.uploads.find((r:Row)=>matches(r,where)),select);},async findMany(args:Row){h.cleanupReads++;const rows=many(h.uploads,args);h.onUploadCandidates?.();return rows;},async create({data}:Row){write();const row={messageId:null,deletionRequestedAt:null,...data};h.uploads.push(row);return project(row);},async update({where,data}:Row){write();const row=h.uploads.find((r:Row)=>matches(r,where));assert(row);Object.assign(row,data);return project(row);},async deleteMany({where}:Row){write();const before=h.uploads.length;h.uploads=h.uploads.filter((r:Row)=>!matches(r,where));return{count:before-h.uploads.length};}},
 async $queryRaw(query:Row){h.locks.push(query);if(query.sql.includes('FROM "User"')){h.locked=true;const date=query.values.find((v:unknown)=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v));return h.users.filter((r:Row)=>query.values.includes(r.id)&&isStaffChatEmployeeActive(r,date));}if(query.sql.includes('FROM "StaffChatAttachment"')){const[id,actor]=query.values;return h.attachments.filter((r:Row)=>r.id===id&&h.messages.some((m:Row)=>m.id===r.messageId&&[m.senderId,m.recipientId].includes(actor)));}if(query.sql.includes('FROM "StaffChatUpload"')){const[id,actor]=query.values;return h.uploads.filter((r:Row)=>r.id===id&&r.senderId===actor);}if(query.sql.includes("pg_advisory_xact_lock"))return[];throw Error("unexpected SQL");},
 async $transaction(operation:(tx:Row)=>Promise<unknown>,options?:Row){h.transactions.push(options);h.beforeTx?.();const before=structuredClone({messages:h.messages,attachments:h.attachments,uploads:h.uploads});try{return await operation(db);}catch(error){Object.assign(h,before);throw error;}finally{h.locked=false;}},
};
const key="__mobileChatActualHarness";(globalThis as Row)[key]={h,db,prepareAttachmentFiles};
const url=(source:string)=>`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`;
const mocks=url(`const {h,db,prepareAttachmentFiles}=globalThis.${key};export const prisma=db;export {prepareAttachmentFiles};export async function getCurrentUser(){return h.session?.user;}export async function publishStaffChatChange(ids){h.changes.push(ids);}export async function retryPendingStaffChatFileDeletes(...args){return h.files.retryPendingStaffChatFileDeletes(...args);}export async function persistAttachmentFiles(files){h.storageWrites++;for(const file of files)h.objects.set(file.storageKey,file.buffer);}export async function removeStoredAttachmentFiles(files){h.storageDeletes++;if(h.failDelete)throw Error('PRIVATE_DELETE_FAILURE');for(const file of files)h.objects.delete(file.storageKey);}export const removeStoredStaffChatFiles=removeStoredAttachmentFiles;export async function readStoredAttachmentFile(file){h.storageReads++;const bytes=h.objects.get(file.storageKey);if(!bytes)throw Error('missing');return {body:new ReadableStream({start(c){c.enqueue(new Uint8Array(bytes));c.close();}}),size:bytes.length};}export const readStaffChatStoredFile=readStoredAttachmentFile;export function getStaffChatChunkRef(id,index,provider){return {storageKey:'staff-chat-chunks/'+id+'/'+index,storageProvider:provider};}export async function writeStaffChatChunk(id,index,provider,bytes){h.storageWrites++;h.objects.set('staff-chat-chunks/'+id+'/'+index,bytes);}export async function writeStaffChatManifest(id,provider,parts,size){h.storageWrites++;return {storageKey:'staff-chat-manifests/'+id,storageProvider:provider,parts,size};}export async function removeStaffChatChunkUpload(){h.storageDeletes++;}`);
function compile(file:string,aliases:Record<string,string>){let source=readFileSync(new URL(`../src/${file}`,import.meta.url),"utf8");for(const[a,b]of Object.entries(aliases))source=source.replaceAll(`"${a}"`,JSON.stringify(b));return url(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);}
const aliases={"@/lib/prisma":mocks,"@/lib/auth":mocks,"@/lib/staff-chat-events":mocks};
const serviceUrl=compile("lib/staff-chat.ts",{...aliases,"@/lib/staff-chat-files":mocks});
const policyUrl=compile("lib/attachment-policy.ts",aliases),filesUrl=compile("lib/staff-chat-files.ts",{...aliases,"@/lib/staff-chat":serviceUrl,"@/lib/attachment-policy":policyUrl,"@/lib/attachment-storage":mocks,"@/lib/staff-chat-chunk-storage":mocks});
// Preserve constants/types used by the real policy module; its storage dependency is real read-only helpers.
const uploadsUrl=compile("lib/staff-chat-uploads.ts",{...aliases,"@/lib/staff-chat":serviceUrl,"@/lib/staff-chat-chunk-storage":mocks}),authUrl=compile("lib/mobile-auth.ts",aliases);
const adapterUrl=compile("lib/mobile-chat.ts",{...aliases,"@/lib/mobile-auth":authUrl,"@/lib/staff-chat":serviceUrl,"@/lib/staff-chat-files":filesUrl,"@/lib/staff-chat-uploads":uploadsUrl});
const files=await import(filesUrl);h.files=files;
const routes:Row={};for(const[path,name]of [["","root"],["/messages","messages"],["/read","read"],["/files","files"],["/files/[id]/preview","preview"],["/files/[id]/download","download"],["/files/[id]/status","status"],["/files/[id]/complete","receipt"],["/uploads","uploads"],["/uploads/[id]/parts/[index]","part"],["/uploads/[id]/complete","publish"]])routes[name]=await import(compile(`app/api/mobile/chat${path}/route.ts`,{"@/lib/mobile-chat":adapterUrl}));
function user(id:string,extra:Row={}){return{id,name:id,status:"ACTIVE",role:"USER",resignationDate:null,department:{name:"부서"},position:{name:"직원"},passwordHash:"PRIVATE_HASH",...extra};}
function signIn(id="actor"){h.session={userId:id,user:h.users.find((r:Row)=>r.id===id),expiresAt:new Date(Date.now()+60000),tokenHash:hash(token)};}
function req(path="",method="GET",value?:unknown,headers:Row={}){return new Request(`https://fixture.invalid/api/mobile/chat${path}`,{method,headers:{Authorization:`Bearer ${token}`,...(method!=="GET"?{"Content-Type":"application/json"}:{}),...headers},...(value===undefined?{}:{body:typeof value==="string"?value:JSON.stringify(value)})});}
const context=(id:string,index="0")=>({params:Promise.resolve({id,index})});
function post(route:string,path:string,value:unknown,id?:string){return routes[route].POST(req(path,"POST",value),id?context(id):undefined);}
function privateJson(response:Response){assert.equal(response.headers.get("cache-control"),"private, no-store");assert.equal(response.headers.get("pragma"),"no-cache");assert.equal(response.headers.get("vary"),"Authorization");assert.equal(response.headers.get("location"),null);}
function safe(value:unknown){assert.doesNotMatch(JSON.stringify(value),/PRIVATE_|storageKey|storageProvider|fileDigest|chunkDigests|downloadToken|downloadRequestId|passwordHash|tokenHash/);}
function seedMessage(extra:Row={}){const row={id:`seed-${++h.nextId}`,sequence:9007199254740993n+BigInt(h.nextId),senderId:"peer",recipientId:"actor",requestId:`request-${h.nextId}`,body:"보관 메시지",createdAt:new Date(0),readAt:null,...extra};h.messages.push(row);return row;}
function seedFile(extra:Row={}){const message=seedMessage(),bytes=Buffer.from("private file"),attachment={id:"file-1",messageId:message.id,originalName:"자료.txt",size:bytes.length,mimeType:"text/plain",fileDigest:hash(bytes),storageKey:"PRIVATE_STORAGE",storageProvider:"local",downloadRequestId:null,downloadToken:null,downloadExpiresAt:null,deletionRequestedAt:null,deletedAt:null,...extra};h.attachments.push(attachment);h.objects.set(attachment.storageKey,bytes);return attachment;}
const driver=process.env.ATTACHMENT_STORAGE_DRIVER,vercel=process.env.VERCEL;
beforeEach(()=>{process.env.ATTACHMENT_STORAGE_DRIVER="local";delete process.env.VERCEL;Object.assign(h,{users:[user("actor"),user("peer"),user("admin",{role:"ADMIN"}),user("other")],session:null,messages:[],attachments:[],uploads:[],policy:null,objects:new Map(),mutations:0,nextId:0,changes:[],locks:[],transactions:[],locked:false,beforeTx:null,sessionReads:0,userReads:0,policyReads:0,cleanupReads:0,storageReads:0,storageWrites:0,storageDeletes:0,failDelete:false,failTombstone:false,failGlobalPolicy:false,onUploadCandidates:null});signIn();});
after(()=>{delete(globalThis as Row)[key];if(driver===undefined)delete process.env.ATTACHMENT_STORAGE_DRIVER;else process.env.ATTACHMENT_STORAGE_DRIVER=driver;if(vercel===undefined)delete process.env.VERCEL;else process.env.VERCEL=vercel;});

test("every actual mobile method authenticates before params/query/body and returns private401",async()=>{
 const calls=[()=>routes.root.GET(req("?bad=1")),()=>routes.messages.GET(req("/messages?peerId=")),()=>post("messages","/messages",{}),()=>post("read","/read",{}),()=>routes.files.GET(req("/files?bad=1")),()=>post("files","/files",{}),()=>routes.preview.GET(req("/files/bad/preview"),context("bad:id")),()=>post("download","/files/bad/download",{},"bad:id"),()=>post("status","/files/bad/status",{},"bad:id"),()=>post("receipt","/files/bad/complete",{},"bad:id"),()=>routes.uploads.GET(req("/uploads?requestId=")),()=>post("uploads","/uploads",{}),()=>routes.part.PUT(req("/uploads/bad/parts/00","PUT",{}),context("bad","00")),()=>post("publish","/uploads/bad/complete",{},"bad")];
 for(const mode of ["missing","expired","inactive","resigned"]){signIn();if(mode==="missing")h.session=null;if(mode==="expired")h.session.expiresAt=new Date(0);if(mode==="inactive")h.users[0].status="INACTIVE";if(mode==="resigned"){h.users[0].status="ACTIVE";h.users[0].resignationDate=today;}for(const call of calls){const response=await call();assert.equal(response.status,401);privateJson(response);assert.equal((await response.json()).code,"UNAUTHORIZED");}h.users[0].status="ACTIVE";h.users[0].resignationDate=null;}
 assert.equal(h.mutations,0);assert.equal(h.storageReads+h.storageWrites+h.storageDeletes,0);assert.equal(h.cleanupReads,0);
});
test("pure policy missing default and normalization do no writes/cleanup/storage; web initializer stays",async()=>{
 const first=await routes.files.GET(req("/files"));privateJson(first);const policy=await first.json();assert.equal(policy.maxFileCount,1);assert.equal(policy.maxFileSize,4*1024*1024);assert.equal(policy.zipMaxFileSize,100*1024*1024);assert(policy.allowedExtensions.includes(".zip"));assert.equal(h.policy,null);assert.equal(h.mutations+h.cleanupReads+h.storageReads+h.storageDeletes,0);
 h.policy={maxFileCount:10,maxFileSizeMb:1,allowedExtensions:[" TXT ",".TXT"]};assert.deepEqual((await(await routes.files.GET(req("/files"))).json()).allowedExtensions,[".txt",".zip"]);assert.equal((await files.getStaffChatFilePolicy()).maxFileSize,1024*1024);h.policy=null;await files.getStaffChatFilePolicy();assert.equal(h.mutations,1);assert(h.policy);
});
test("file domain injected policy stays inside supplied actor transaction, including missing default",async()=>{
 const form=new FormData();for(const[key,value]of Object.entries({peerId:"peer",body:"",requestId:"injected-file-request"}))form.set(key,value);form.set("file",new File(["safe bytes"],"자료.txt",{type:"text/plain"}));
 let policy:Row|null=null,reads=0,writes=0;const scopedPolicy={async findUnique(){assert(h.locked);reads++;return policy;},async upsert({create}:Row){assert(h.locked);writes++;policy=create;return create;}};
 const tx={...db,attachmentPolicy:scopedPolicy},injected={...db,$transaction:(work:(client:Row)=>Promise<unknown>,options?:Row)=>db.$transaction(()=>work(tx),options)};h.failGlobalPolicy=true;
 const result=await files.sendStaffChatFile("actor",form,{db:injected,today});safe(result);assert.equal(result.body,"파일: 자료.txt");assert.equal(reads,1);assert.equal(writes,1);assert(policy);assert.equal(h.policy,null);assert.equal(h.policyReads,0);
 h.users[0].status="INACTIVE";await assert.rejects(files.sendStaffChatFile("actor",form,{db:injected,today}),{status:401});assert.equal(reads,1);assert.equal(writes,1);assert.equal(h.messages.length,1);
});
test("ZIP cleanup checks fresh actor before query and again before claim; suspension never marks or deletes",async()=>{
 const id="12345678-1234-1234-1234-123456789abc",input={peerId:"peer",body:"",requestId:"cleanup-next-request",originalName:"자료.zip",mimeType:"application/zip",size:4194305,chunkDigests:["a".repeat(64),"b".repeat(64)]};
 h.uploads.push({id,senderId:"actor",recipientId:"peer",requestId:"expired-request",size:4194305,uploadedParts:[0],messageId:null,expiresAt:new Date(0),deletionRequestedAt:null,storageProvider:"local"});h.objects.set("staff-chat-chunks/"+id+"/0",Buffer.from("preserved"));
 h.beforeTx=()=>{h.users[0].status="INACTIVE";};const initial=await post("uploads","/uploads",input);assert.equal(initial.status,401);assert.equal(h.cleanupReads,0);assert.equal(h.mutations+h.storageWrites+h.storageDeletes,0);assert.equal(h.uploads[0].deletionRequestedAt,null);
 h.beforeTx=null;h.users[0].status="ACTIVE";h.onUploadCandidates=()=>{h.users[0].resignationDate=today;};const race=await post("uploads","/uploads",input);assert.equal(race.status,401);privateJson(race);assert.equal(h.cleanupReads,1);assert.equal(h.uploads[0].deletionRequestedAt,null);assert.equal(h.uploads.length,1);assert.equal(h.mutations+h.storageWrites+h.storageDeletes,0);assert.equal(h.objects.size,1);
});
test("blank resignation matches JS/SQL, no hire check and inactive peer archive/count preserved",async()=>{
 h.users[0].resignationDate="";h.users[0].hireDate="2999-01-01";h.users[1].status="INACTIVE";seedMessage();const response=await routes.root.GET(req());assert.equal(response.status,200);const data=await response.json();assert.equal(data.unreadCount,1);assert.equal(data.conversations[0].peer.active,false);assert(!data.employees.some((u:Row)=>u.id==="peer"));safe(data);assert(h.locks.every((q:Row)=>q.sql.includes('"resignationDate" = \'\'')));
 h.users[1].status="ACTIVE";h.users[1].resignationDate="";assert.equal((await post("messages","/messages",{peerId:"peer",body:"일치",requestId:"blank-request"})).status,200);
});
test("text send replay preserves inactive-peer result but actor fresh/shape/change boundaries hold",async()=>{
 const input={peerId:"peer",body:" 본문 ",requestId:"text-request"},first=await(await post("messages","/messages",input)).json();safe(first);assert.equal(first.message.body,"본문");assert.equal(typeof first.message.sequence,"string");h.users[1].status="INACTIVE";const replay=await(await post("messages","/messages",input)).json();assert.equal(replay.message.id,first.message.id);assert.equal(h.messages.length,1);
 assert.equal((await post("messages","/messages",{...input,body:"다름"})).status,409);assert.equal((await post("messages","/messages",{...input,requestId:"new-request"})).status,404);h.beforeTx=()=>{h.users[0].status="INACTIVE";};assert.equal((await post("messages","/messages",input)).status,401);assert.equal(h.messages.length,1);
});
test("read only own viewed inbound sequence inside actor lock; outbound/foreign404 and inactivepeer allowed",async()=>{
 const a=seedMessage(),viewed=seedMessage(),later=seedMessage(),out=seedMessage({senderId:"actor",recipientId:"peer"}),foreign=seedMessage({senderId:"other",recipientId:"admin"});h.users[1].status="INACTIVE";
 const response=await post("read","/read",{peerId:"peer",messageId:viewed.id});assert.equal(response.status,200);assert(a.readAt&&viewed.readAt);assert.equal(later.readAt,null);assert.equal(out.readAt,null);assert.equal(foreign.readAt,null);for(const row of [out,foreign])assert.equal((await post("read","/read",{peerId:"peer",messageId:row.id})).status,404);
 h.beforeTx=()=>{h.users[0].status="INACTIVE";};assert.equal((await post("read","/read",{peerId:"peer",messageId:later.id})).status,401);assert.equal(later.readAt,null);
});
test("message cursor50+1 and precision stay scoped, valid unknownpeer empty, strictqueries/types",async()=>{
 for(let n=0;n<53;n++)seedMessage();const first=await(await routes.messages.GET(req("/messages?peerId=peer"))).json();assert.equal(first.messages.length,50);assert.equal(first.hasMore,true);assert.equal(first.messages[0].sequence,"9007199254740997");const older=await(await routes.messages.GET(req(`/messages?peerId=peer&before=${first.messages[0].id}`))).json();assert.equal(older.messages.length,3);assert.equal(older.hasMore,false);const foreign=seedMessage({senderId:"other",recipientId:"admin"});assert.equal((await routes.messages.GET(req(`/messages?peerId=peer&before=${foreign.id}`))).status,404);assert.deepEqual(await(await routes.messages.GET(req("/messages?peerId=unknown"))).json(),{messages:[],hasMore:false});
 for(const path of ["/messages?peerId=","/messages?peerId=peer&peerId=peer","/messages?peerId=peer&before=","/messages?peerId=peer&userId=admin"]){assert.equal((await routes.messages.GET(req(path))).status,400);}for(const input of [null,[],{}, {peerId:"peer",body:"a",requestId:"request-1",senderId:"admin"}])assert.equal((await post("messages","/messages",input)).status,400);
});
test("known receipt pure status checks recipient/request/token, expired match and tombstones without effects",async()=>{
 const file=seedFile({downloadRequestId:"download-1",downloadToken:"token-known",downloadExpiresAt:new Date(0)}),baseline=h.mutations;
 for(const [requestId,receiptToken,match]of [["download-1","token-known",true],["download-2","token-known",false],["download-1","token-other",false]]){const response=await post("status","/files/file-1/status",{requestId,token:receiptToken},file.id);assert.equal(response.status,200);assert.deepEqual(await response.json(),{match,status:"available"});}
 for(const [field,status]of [["deletionRequestedAt","deleting"],["deletedAt","deleted"]]){file[field]=new Date();assert.deepEqual(await(await post("status","/files/file-1/status",{requestId:"download-1",token:"token-known"},file.id)).json(),{match:true,status});}
 for(const id of ["peer","admin","other"]){signIn(id);assert.equal((await post("status","/files/file-1/status",{requestId:"download-1",token:"token-known"},file.id)).status,404);}assert.equal(h.mutations,baseline);assert.equal(h.cleanupReads+h.storageReads+h.storageDeletes+h.storageWrites,0);
});
test("download/complete lease mismatch and deleting retry preserve original until confirmed; no raw DTO",async()=>{
 const file=seedFile(),download=await post("download","/files/file-1/download",{requestId:"download-1"},file.id);assert.equal(download.status,200);const receiptToken=download.headers.get("x-chat-download-token");assert(receiptToken);assert.equal(Buffer.from(await download.arrayBuffer()).length,file.size);privateJson(download);assert.equal((await post("download","/files/file-1/download",{requestId:"download-2"},file.id)).status,409);assert.equal(h.storageDeletes,0);
 h.failDelete=true;const response=await post("receipt","/files/file-1/complete",{token:receiptToken},file.id);assert.equal(response.status,503);assert(h.attachments[0].deletionRequestedAt);assert.equal(h.attachments[0].deletedAt,null);assert(h.attachments[0].storageKey);assert.equal((await post("download","/files/file-1/download",{requestId:"download-1"},file.id)).status,410);h.failDelete=false;const complete=await post("receipt","/files/file-1/complete",{token:receiptToken},file.id);assert.equal(complete.status,200);safe(await complete.json());assert(h.attachments[0].deletedAt);assert.equal(h.attachments[0].storageKey,null);assert.equal((await post("receipt","/files/file-1/complete",{token:receiptToken},file.id)).status,200);
});
test("external removal then database failure stays deleting and exact-token retry finalizes once",async()=>{
 const file=seedFile(),download=await post("download","/files/file-1/download",{requestId:"download-1"},file.id),receiptToken=download.headers.get("x-chat-download-token");assert(receiptToken);await download.arrayBuffer();h.failTombstone=true;
 const first=await post("receipt","/files/file-1/complete",{token:receiptToken},file.id);assert.equal(first.status,503);privateJson(first);safe(await first.json());assert(h.attachments[0].deletionRequestedAt);assert.equal(h.attachments[0].deletedAt,null);assert.equal(h.objects.size,0);assert.equal(h.storageDeletes,1);
 assert.deepEqual(await(await post("status","/files/file-1/status",{requestId:"download-1",token:receiptToken},file.id)).json(),{match:true,status:"deleting"});assert.equal((await post("receipt","/files/file-1/complete",{token:"other-token"},file.id)).status,409);assert.equal(h.storageDeletes,1);h.failTombstone=false;
 const retry=await post("receipt","/files/file-1/complete",{token:receiptToken},file.id);assert.equal(retry.status,200);const result=await retry.json();safe(result);assert.equal(result.message.attachment.status,"deleted");assert.equal(h.attachments[0].storageKey,null);assert.equal(h.storageDeletes,2);assert.equal((await post("receipt","/files/file-1/complete",{token:receiptToken},file.id)).status,200);assert.equal(h.storageDeletes,2);
});
test("actual mobile ZIP start/parts/publish enforce hash, ownership and immutable matching replay",async()=>{
 const bytes=[Buffer.alloc(4*1024*1024,1),Buffer.from([2])],input={peerId:"peer",body:"",requestId:"zip-full-request",originalName:" 자료.zip ",mimeType:"application/zip",size:4*1024*1024+1,chunkDigests:bytes.map(hash)};
 const started=await post("uploads","/uploads",input);assert.equal(started.status,200);const initial=await started.json();safe(initial);assert.deepEqual(initial.uploadedParts,[]);const id=initial.uploadId,put=(index:string,part:Uint8Array)=>routes.part.PUT(new Request(`https://fixture.invalid/api/mobile/chat/uploads/${id}/parts/${index}`,{method:"PUT",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/octet-stream"},body:new Uint8Array(part)}),context(id,index));
 assert.equal((await post("publish","/uploads/id/complete",{},id)).status,409);assert.equal((await put("00",bytes[0])).status,400);assert.equal((await put("0",Buffer.alloc(bytes[0].length,3))).status,409);assert.equal(h.storageWrites,0);signIn("admin");assert.equal((await put("0",bytes[0])).status,404);signIn();
 assert.equal((await put("0",bytes[0])).status,200);assert.equal((await put("0",bytes[0])).status,200);assert.equal(h.storageWrites,1);assert.equal((await put("1",bytes[1])).status,200);assert.equal(h.storageWrites,2);assert.deepEqual((await(await routes.uploads.GET(req("/uploads?requestId=zip-full-request"))).json()).uploadedParts,[0,1]);
 const published=await post("publish","/uploads/id/complete",{},id);assert.equal(published.status,200);const result=await published.json();safe(result);assert.equal(result.message.body,"파일: 자료.zip");assert.equal(result.message.attachment.originalName,"자료.zip");assert.equal(h.messages.length,1);assert.equal(h.storageWrites,3);assert.equal((await put("0",bytes[0])).status,200);assert.equal(h.storageWrites,3);
 assert.equal((await post("publish","/uploads/id/complete",{},id)).status,200);assert.equal(h.messages.length,1);h.users[1].status="INACTIVE";assert.equal((await post("publish","/uploads/id/complete",{},id)).status,404);const recovered=await(await routes.uploads.GET(req("/uploads?requestId=zip-full-request"))).json();assert.equal(recovered.message.id,result.message.id);assert.equal(h.storageWrites,3);
});
test("sender ZIP pure GET recovers published inactivepeer without storage/expiry mutation; foreign404",async()=>{
 const message=seedMessage({senderId:"actor",recipientId:"peer"}),upload={id:"12345678-1234-1234-1234-123456789abc",senderId:"actor",recipientId:"peer",requestId:"zip-request",size:4*1024*1024+1,uploadedParts:[1,0,1],messageId:message.id,expiresAt:new Date(0),deletionRequestedAt:null};h.uploads.push(upload);h.users[1].status="INACTIVE";
 const response=await routes.uploads.GET(req("/uploads?requestId=zip-request"));assert.equal(response.status,200);const data=await response.json();assert.deepEqual(data.uploadedParts,[0,1]);assert.equal(data.message.id,message.id);safe(data);assert.equal(h.cleanupReads+h.storageReads+h.storageWrites+h.storageDeletes+h.mutations,0);for(const [id,status]of [["peer",401],["admin",404]]){signIn(id);assert.equal((await routes.uploads.GET(req("/uploads?requestId=zip-request"))).status,status);}signIn();h.uploads[0].messageId=null;assert.equal((await routes.uploads.GET(req("/uploads?requestId=zip-request"))).status,410);h.uploads[0].expiresAt=new Date(Date.now()+60000);assert.equal((await routes.uploads.GET(req("/uploads?requestId=zip-request"))).status,200);
 assert.equal((await post("publish","/uploads/id/complete",{},upload.id)).status,404);assert.equal(h.storageWrites,0);assert.equal((await routes.uploads.GET(req("/uploads?requestId=zip-request&requestId=zip-request"))).status,400);
});
test("bounded JSON byte/mime/unknown/UTF8/declared limits and ZIP escaped legitimate max use32KiB",async()=>{
 const keys=["peerId","body","requestId"],valid={peerId:"peer",body:"가".repeat(2000),requestId:"request-1"};assert.equal((await readMobileChatJson(req("","POST",valid),keys)).body,valid.body);
 for(const [headers,body,status]of [[{"Content-Length":"1"},JSON.stringify(valid),400],[{"Content-Length":"-1"},"{}",400],[{"Content-Length":"16385"},"{}",413],[{"Content-Type":"text/plain"},"{}",415],[{},"{",400]])await assert.rejects(readMobileChatJson(req("","POST",body,headers),keys),{status});
 const bad=new Request("https://fixture.invalid",{method:"POST",headers:{"Content-Type":"application/json"},body:new Uint8Array([0xc3,0x28])});await assert.rejects(readMobileChatJson(bad,[]),{status:400});await assert.rejects(readMobileChatJson(req("","POST"," ".repeat(16385)),[]),{status:413});
 const zip={peerId:"p".repeat(128),body:"가".repeat(2000),requestId:"r".repeat(128),originalName:"나".repeat(176)+".zip",mimeType:"다".repeat(255),size:100*1024*1024,chunkDigests:Array(25).fill("a".repeat(64))};const escaped=JSON.stringify(zip).replace(/[가-힣]/g,c=>`\\u${c.charCodeAt(0).toString(16)}`);assert(Buffer.byteLength(escaped)>16384);assert.deepEqual(await readMobileChatJson(req("","POST",escaped),Object.keys(zip),mobileChatUploadJsonMaxBytes),zip);await assert.rejects(readMobileChatJson(req("","POST",escaped),Object.keys(zip)),{status:413});
});
test("multipart/chunk actual caps and duplicate/unknown fields reject before domain/storage",async()=>{
 const form=new FormData();for(const[key,value]of Object.entries({peerId:"peer",body:"",requestId:"file-request"}))form.set(key,value);form.set("file",new File(["safe bytes"],"자료.txt",{type:"text/plain"}));
 const multipart=()=>new Request("https://fixture.invalid/api/mobile/chat/files",{method:"POST",headers:{Authorization:`Bearer ${token}`},body:form});const first=await routes.files.POST(multipart());assert.equal(first.status,200);safe(await first.json());form.append("peerId","other");assert.equal((await routes.files.POST(multipart())).status,400);form.delete("peerId");form.set("peerId","peer");form.set("userId","admin");await assert.rejects(readMobileChatFileForm(multipart()),{status:400});
 const chunk=(bytes:Uint8Array,headers:Row={})=>new Request("https://fixture.invalid",{method:"PUT",headers:{"Content-Type":"application/octet-stream",...headers},body:new Uint8Array(bytes)});assert.equal((await readMobileChatChunk(chunk(Buffer.alloc(4*1024*1024)))).length,4*1024*1024);await assert.rejects(readMobileChatChunk(chunk(Buffer.alloc(4*1024*1024+1))),{status:413});await assert.rejects(readMobileChatChunk(chunk(Buffer.alloc(1),{"Content-Length":"2"})),{status:400});
});
test("whole body read deadline cancels hanging stream before mutation",async()=>{
 const originalNow=Date.now;let calls=0;Date.now=()=>originalNow()+(calls++===0?0:10001);
 try{let canceled=false;const request=new Request("https://fixture.invalid",{method:"POST",headers:{"Content-Type":"application/json"},body:new ReadableStream({pull(){return new Promise(()=>{});},cancel(){canceled=true;}}),duplex:"half"}as RequestInit);await assert.rejects(readMobileChatJson(request,[]),{status:408});assert.equal(canceled,true);assert.equal(h.mutations,0);}finally{Date.now=originalNow;}
});
