import assert from 'node:assert/strict';
import { test } from 'node:test';
import { ApiError } from '../mobile/src/lib/api';
import { createYouthFileApi, isYouthUpload, validateYouthDecisionFile, type YouthFileAdapter } from '../mobile/src/lib/youth-file-core';
const policy={maxNewFileCount:5 as const,maxFileSize:31457280 as const,allowedExtensions:['.pdf']};
const iso='2026-10-04T00:00:00.000Z',digest='a'.repeat(64),fileDescriptor={originalName:'자료.pdf',size:12,mimeType:'application/pdf'};
function dto(patch:Record<string,unknown>={}){return{id:'upload-id',requestId:'original-request',targetYouthId:null,state:'uploading',expiresAt:'2099-01-01T00:00:00.000Z',file:fileDescriptor,consumed:null,...patch};}
function harness(){const calls:{path:string;options:Record<string,unknown>}[]=[],removed:unknown[]=[],local={size:12};let puts=0,hashes=0,account=true;let responder=async(path:string,options:Record<string,unknown>):Promise<unknown>=>path.endsWith('/complete')?{upload:dto({state:'ready'}),pending:false}:path.endsWith('/grant')?{upload:dto(),grant:{method:'PUT',url:'https://storage.example/signed-synthetic',headers:{'Content-Type':'application/pdf'},signedExpiresAt:'2099-01-01T00:00:00.000Z'}}:options.method==='POST'?{upload:dto(),replayed:false}:{upload:dto()};
 const adapter:YouthFileAdapter<typeof local>={pick:async()=>({file:local,name:'자료.pdf',size:12,mimeType:'application/pdf'}),size:f=>f.size,hash:async()=>{hashes++;return digest;},put:async()=>{puts++;},download:async(_path,_expected,call)=>{call.check();calls.push({path:'binary',options:{body:call.downloadBody}});return{file:{size:12},info:{name:'actual.pdf',size:12,mimeType:'application/pdf'}};},head:async()=>new Uint8Array(),export:async()=> '파일 저장 요청',preview:()=>({uri:'unused',release(){}}),release:f=>removed.push(f),clear:async()=>{}};
 const request=async<T,>(path:string,_token:string,options:Record<string,unknown>={})=>{calls.push({path,options});return await responder(path,options) as T;};const api=createYouthFileApi(adapter,request);const pick=()=>api.pickYouthDecisionFile({token:'a',policy,isCurrent:()=>account});const operation=(file:Awaited<ReturnType<typeof pick>>)=>api.createYouthDecisionUpload({token:'a',file:file!,requestId:'original-request',targetYouthId:null,isCurrent:()=>account});return{api,adapter,calls,removed,pick,operation,setResponder(fn:typeof responder){responder=fn;},invalidate(){account=false;},counts:()=>({puts,hashes})};}
test('youth selection is opaque; start has no grant then explicit grant+PUT+complete matches whole SHA',async()=>{const h=harness(),file=await h.pick();assert.deepEqual(Object.keys(file!).sort(),['name','release','size']);const op=h.operation(file);await op.prepare();assert.equal(h.calls[0].path,'/youth/document-uploads');assert.equal(h.calls[1].path,'/youth/document-uploads/upload-id/grant');assert.equal(h.calls[0].options.body&& (h.calls[0].options.body as Record<string,unknown>).wholeSha256,digest);assert.equal(op.readyUploadId(),'upload-id');assert.deepEqual(h.counts(),{puts:1,hashes:1});await h.api.clearYouthFileResources();});
test('lost start GET404 preserves immutable source and retries same start key after receipt first',async()=>{const h=harness(),file=await h.pick(),op=h.operation(file);h.setResponder(async()=>{throw new ApiError('lost',0);});await assert.rejects(op.prepare());const original=h.calls[0].options.body;file!.release();assert.equal(h.removed.length,0);h.setResponder(async(_path,options)=>{if(options.method==='GET')throw new ApiError('none',404);throw new ApiError('samekey lost',0);});await assert.rejects(op.prepare());assert.equal(h.calls[1].path,'/youth/document-uploads/requests/original-request');assert.deepEqual(h.calls[2].options.body,original);await h.api.clearYouthFileResources();});
test('unknown PUT and pure uploading status cannot authorize another PUT or grant',async()=>{const h=harness(),file=await h.pick(),op=h.operation(file);let puts=0;h.adapter.put=async()=>{puts++;throw new ApiError('lost PUT',0);};await assert.rejects(op.prepare());h.setResponder(async path=>path.endsWith('/complete')?Promise.reject(new ApiError('unknown',503,undefined,'STORAGE_UNAVAILABLE')):{upload:dto()});await op.refresh();await assert.rejects(op.prepare(),{code:'STORAGE_UNAVAILABLE'});assert.equal(puts,1);assert.equal(h.calls.filter(x=>x.path.endsWith('/grant')).length,1);await h.api.clearYouthFileResources();});
test('only explicit UPLOAD_RETRY permits same snapshot and original receipt to retransmit',async()=>{const h=harness(),file=await h.pick(),op=h.operation(file);let puts=0,proof=true;h.adapter.put=async()=>{if(++puts===1)throw new ApiError('PUT lost',0);};await assert.rejects(op.prepare());h.setResponder(async path=>path.endsWith('/complete')?(proof?Promise.reject(new ApiError('absent',503,undefined,'UPLOAD_RETRY')):{upload:dto({state:'ready'}),pending:false}):path.endsWith('/grant')?{upload:dto(),grant:{method:'PUT',url:'https://storage.example/signed',headers:{'Content-Type':'application/pdf'},signedExpiresAt:'2099-01-01T00:00:00.000Z'}}:{upload:dto()});await assert.rejects(op.prepare(),{code:'UPLOAD_RETRY'});proof=false;await op.prepare();assert.equal(puts,2);assert.equal(h.counts().hashes,1);assert.equal(h.calls.filter(x=>x.path==='/youth/document-uploads').length,1);await h.api.clearYouthFileResources();});
test('202 finalizing keeps same upload ID and completes without another PUT',async()=>{const h=harness(),file=await h.pick(),op=h.operation(file);let pending=true;h.setResponder(async(path,opts)=>path.endsWith('/complete')?{upload:dto({state:pending?'finalizing':'ready'}),pending}:path.endsWith('/grant')?{upload:dto(),grant:{method:'PUT',url:'https://storage.example/signed',headers:{'Content-Type':'application/pdf'},signedExpiresAt:'2099-01-01T00:00:00.000Z'}}:opts.method==='POST'?{upload:dto(),replayed:false}:{upload:dto({state:'finalizing'})});await assert.rejects(op.prepare(),{status:202});pending=false;await op.prepare();assert.equal(h.counts().puts,1);assert.equal(op.readyUploadId(),'upload-id');await h.api.clearYouthFileResources();});
test('consumed/deleting DTO strips file and stale account selected handle cannot upload',async()=>{assert.equal(isYouthUpload(dto({state:'deleting',file:null})),true);assert.equal(isYouthUpload(dto({state:'consumed',file:null,consumed:{youthId:'y',documentId:'d',requestId:'parent-key'}})),true);assert.equal(isYouthUpload(dto({state:'consumed',file:fileDescriptor,consumed:null})),false);const h=harness(),file=await h.pick(),op=h.operation(file);h.invalidate();await assert.rejects(op.prepare(),{name:'AbortError'});assert.equal(h.calls.length,0);await h.api.clearYouthFileResources();});
test('old token scoped cleanup leaves newer account selected file valid',async()=>{const h=harness();const old=await h.pick();const newer=await h.api.pickYouthDecisionFile({policy,token:'b'});await h.api.clearYouthFileResources({expectedToken:'a'});assert.throws(()=>h.operation(old),{name:'AbortError'});assert.doesNotThrow(()=>h.api.createYouthDecisionUpload({file:newer!,token:'b',targetYouthId:null,requestId:'new-key'}));await h.api.clearYouthFileResources();});
test('decision download immutable reason POST has no chat/resource completion',async()=>{const h=harness();const op=h.api.createYouthDecisionTransfer({token:'a',document:{id:'d',name:'원래.pdf',size:12,createdAt:iso,updatedAt:iso},requestId:'same-download',reason:'OTHER',reasonDetail:'기관 업무'});assert.equal(await op.download(),true);assert.equal(await op.save(),'파일 저장 요청');assert.deepEqual(h.calls[0].options.body,{requestId:'same-download',reason:'OTHER',reasonDetail:'기관 업무'});assert.equal(h.calls.length,1);op.release();await h.api.clearYouthFileResources();});
test('filename is preserved without silent resource truncation and policy denies unsafe/oversized source',()=>{const p={maxFileSizeMb:30,allowedExtensions:['.pdf']};const long='가'.repeat(200)+'.pdf';assert.equal(validateYouthDecisionFile(long,12,p),long);assert.throws(()=>validateYouthDecisionFile('../x.pdf',12,p),{status:400});assert.throws(()=>validateYouthDecisionFile('x.exe',12,p),{status:415});assert.throws(()=>validateYouthDecisionFile('x.pdf',31457281,p),{status:413});});
