import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { after, beforeEach, test } from "node:test";
import ts from "typescript";
// Actual parsers, domain, queries and route adapter; only persistence/storage ports are synthetic.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row = Record<string, any>;
const now = new Date("2026-10-03T03:00:00Z"), actor = { id:"actor", name:"직원", role:"USER", status:"ACTIVE", department:{name:"부서"},position:{name:"직급"},profileImageStorageKey:"PRIVATE_PROFILE" }, other={...actor,id:"other",name:"다른직원"};
const tables=["user","resourcePost","resourceAttachment","resourcePostView","resourceMutationReceipt","resourceUpload","resourceViewEvent","resourceFileCleanup","attachment","attachmentPolicy","youthDecisionDocument","mobileDraftUpload","staffChatAttachment","auditLog"];
const h: Row={state:{},reads:[],writes:[],sql:[],session:null,next:0,auditFailure:false,storageFailure:false,storageDeletes:[],beforeTx:null,txErrors:[],cacheFailure:false};
const equal=(a:unknown,b:unknown)=>a instanceof Date&&b instanceof Date?a.getTime()===b.getTime():a===b;
function match(row:Row,where:Row={}):boolean{return Object.entries(where).every(([key,value])=>{if(key==="AND")return(Array.isArray(value)?value:[value]).every((part:Row)=>match(row,part));if(key==="OR")return value.some((part:Row)=>match(row,part));if(key.includes("_")&&!(key in row))return match(row,value);const current=row[key];if(value===null||value instanceof Date||typeof value!=="object")return equal(current,value);if("not"in value&&equal(current,value.not))return false;if("in"in value&&!value.in.some((v:unknown)=>equal(current,v)))return false;if("lte"in value&&!(current!=null&&current<=value.lte))return false;if("gte"in value&&!(current!=null&&current>=value.gte))return false;if("lt"in value&&!(current!=null&&current<value.lt))return false;if("contains"in value&&!String(current).toLowerCase().includes(String(value.contains).toLowerCase()))return false;if("some"in value)return(current??[]).some((v:Row)=>match(v,value.some));if("name"in value)return match(current,value);return true;});}
function related(model:string,row:Row):Row{if(model==="resourcePost")return{...row,author:h.state.user.find((user:Row)=>user.id===row.authorId),attachments:h.state.resourceAttachment.filter((file:Row)=>file.resourceId===row.id),views:h.state.resourcePostView.filter((view:Row)=>view.resourceId===row.id).map((view:Row)=>related("resourcePostView",view))};if(model==="resourcePostView")return{...row,user:h.state.user.find((user:Row)=>user.id===row.userId)};if(model==="resourceAttachment")return{...row,resource:h.state.resourcePost.find((post:Row)=>post.id===row.resourceId)};return row;}
function project(row:Row,args:Row={}):Row{const result:Row=args.select?{}:structuredClone(row);for(const[key,value]of Object.entries(args.select??args.include??{})){if(value===true)result[key]=structuredClone(row[key]);else if(Array.isArray(row[key]))result[key]=many(row[key],value as Row);else result[key]=row[key]==null?row[key]:project(row[key],value as Row);}return result;}
function many(rows:Row[],args:Row={}):Row[]{const order=Array.isArray(args.orderBy)?args.orderBy:[args.orderBy??{}];return rows.filter(row=>match(row,args.where)).sort((a,b)=>{for(const o of order)for(const[k,d]of Object.entries(o)){const n=a[k]<b[k]?-1:a[k]>b[k]?1:0;if(n)return d==="desc"?-n:n;}return 0;}).slice(args.skip??0,args.take===undefined?undefined:(args.skip??0)+args.take).map(row=>project(row,args));}
function change(row:Row,data:Row){for(const[key,value]of Object.entries(data))row[key]=value&&typeof value==="object"&&"increment"in value?row[key]+value.increment:structuredClone(value);}
const compoundFields:Record<string,Record<string,string[]>>={resourceFileCleanup:{storageProvider_storageKey:["storageProvider","storageKey"]},resourceUpload:{actorId_startRequestId:["actorId","startRequestId"]},resourceMutationReceipt:{actorId_requestId:["actorId","requestId"]},resourceViewEvent:{resourceId_actorId_requestId:["resourceId","actorId","requestId"]},resourcePostView:{resourceId_userId:["resourceId","userId"]}};
function validateCompoundWhere(model:string,where:Row={}){for(const[key,fields]of Object.entries(compoundFields[model]??{})){const value=where[key];if(value===undefined)continue;if(!value||typeof value!=="object"||Object.keys(value).length!==fields.length||fields.some(field=>typeof value[field]!=="string")||Object.keys(value).some(field=>!fields.includes(field)))throw Object.assign(Error("Invalid compound unique selector"),{name:"PrismaClientValidationError"});}}
const cleanupCreateFields=["id","storageProvider","storageKey","objectKind","sourceUploadId","sourceMutationId","notBefore","nextAttemptAt","state","claimId","leaseUntil","attemptCount","lastErrorCode","createdAt","updatedAt","completedAt"];
const db:Row={mobileSession:{async findUnique(){return h.session;}},async $queryRaw(sql:Row){h.sql.push(sql);const projected=sql.strings.join("?").split(/\bFROM\b/i)[0];if(/\b(?:pg_advisory_xact_lock|pg_sleep)\s*\(/i.test(projected)&&!/::(?:text|varchar)/i.test(projected))throw Object.assign(Error("Unsupported PostgreSQL void result"),{name:"PrismaClientKnownRequestError",code:"P2010"});return[];},async $transaction(operation:(tx:Row)=>Promise<unknown>){h.beforeTx?.();if(h.txErrors.length)throw h.txErrors.shift();const old=structuredClone(h.state),writeCount=h.writes.length;try{return await operation(db);}catch(error){h.state=old;h.writes.length=writeCount;throw error;}}};
for(const model of tables){db[model]={async findMany(args:Row={}){h.reads.push({model,...args});return many(h.state[model].map((row:Row)=>related(model,row)),args);},async findUnique(args:Row){validateCompoundWhere(model,args.where);return(await this.findMany(args))[0]??null;},async findFirst(args:Row){return this.findUnique(args);},async findUniqueOrThrow(args:Row){const row=await this.findUnique(args);if(!row)throw Error("missing synthetic row");return row;},async count(args:Row={}){return(await this.findMany(args)).length;},async create({data,...args}:Row){if(model==="resourceFileCleanup"&&Object.keys(data).some(field=>!cleanupCreateFields.includes(field)))throw Object.assign(Error("Invalid cleanup create field"),{name:"PrismaClientValidationError"});if(model==="auditLog"&&h.auditFailure)throw Error("PRIVATE_AUDIT_ERROR");const row={id:`${model}-${++h.next}`,createdAt:now,updatedAt:now,viewCount:model==="resourcePostView"?1:0,pinned:false,state:model==="resourceFileCleanup"?"pending":"uploading",purpose:"resource",completedAt:null,lastGrantExpiresAt:null,finalizeClaimId:null,finalizeLeaseUntil:null,finalizeIv:null,finalizeWriteEvidence:null,hadUnknownWrite:false,consumedResourceId:null,consumedAttachmentId:null,consumedMutationId:null,terminalReason:null,claimId:null,leaseUntil:null,attemptCount:0,firstViewedAt:now,lastViewedAt:now,cleanupIds:[],...structuredClone(data)};h.state[model].push(row);h.writes.push({model,action:"create",data});return project(related(model,row),args);},async update({where,data,...args}:Row){const row=h.state[model].find((r:Row)=>match(r,where));if(!row)throw Error("missing synthetic row");change(row,data);h.writes.push({model,action:"update",data});return project(related(model,row),args);},async updateMany({where,data}:Row){const rows=h.state[model].filter((r:Row)=>match(r,where));for(const row of rows)change(row,data);h.writes.push({model,action:"updateMany",data});return{count:rows.length};},async upsert({where,create,update}:Row){return await this.findUnique({where})?this.update({where,data:update}):this.create({data:create});},async deleteMany({where}:Row){const old=h.state[model].length;h.state[model]=h.state[model].filter((row:Row)=>!match(row,where));h.writes.push({model,action:"deleteMany"});return{count:old-h.state[model].length};},async delete({where}:Row){const row=await this.findUnique({where});await this.deleteMany({where});if(model==="resourcePost")for(const child of["resourceAttachment","resourcePostView","resourceViewEvent"])await db[child].deleteMany({where:{resourceId:row.id}});return row;}};}
const key="__actualResourceHarness";(globalThis as Row)[key]={h,db};
const url=(source:string)=>`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`;
const mocks=url(`const {h,db}=globalThis.${key};export const prisma=db;export async function getCurrentUser(){return h.session?.user??null;}export function getAuditLogRequestData(){return {ipAddress:'PRIVATE_IP'};}export function revalidateResourceLibrary(){if(h.cacheFailure){} }`);
function compile(file:string,aliases:Record<string,string>={}){let source=readFileSync(new URL(`../src/${file}`,import.meta.url),"utf8");
  // Notification delivery is an external effect; actual queue/integration tests cover it separately.
  source = source.replaceAll(JSON.stringify("@/lib/mobile-push-events"), JSON.stringify('data:text/javascript,export%20async%20function%20queueStaffPushEvent(){}%20export%20async%20function%20queueChatPush(){}'));
for(const[a,b]of Object.entries(aliases))source=source.replaceAll(JSON.stringify(a),JSON.stringify(b));return url(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);}
const base={"@/lib/prisma":mocks,"@/lib/audit-log-request":mocks,"@/lib/resource-library-cache":mocks};
const policy=compile("lib/attachment-policy.ts",base),queries=compile("lib/resource-library-queries.ts",{...base,"@/lib/attachment-policy":policy}),cleanup=compile("lib/resource-file-cleanup.ts",{...base,"@/lib/resource-library-queries":queries}),mutations=compile("lib/resource-library-mutations.ts",{...base,"@/lib/attachment-policy":policy,"@/lib/resource-library-queries":queries,"@/lib/resource-file-cleanup":cleanup}),uploads=compile("lib/resource-uploads.ts",{...base,"@/lib/attachment-policy":policy,"@/lib/resource-library-queries":queries,"@/lib/resource-library-mutations":mutations,"@/lib/resource-file-cleanup":cleanup}),auth=compile("lib/mobile-auth.ts",base),adapter=compile("lib/mobile-resources.ts",{...base,"@/lib/mobile-auth":auth,"@/lib/resource-library-queries":queries,"@/lib/resource-library-mutations":mutations,"@/lib/resource-uploads":uploads});
const domain=await import(mutations),query=await import(queries),upload=await import(uploads),clean=await import(cleanup),api=await import(adapter),core=await import("../src/lib/mobile-resources-core.ts");
const storage={async createResourceStagingGrant(){return{method:"PUT",url:"https://staging.invalid/opaque",headers:{"Content-Type":"application/pdf"},expiresAt:now};},async finalizeResourceStoredUpload(input:Row){if(h.storageFailure)throw Object.assign(Error("PRIVATE_STORAGE"),{writeEvidence:h.unknown?"unknown":"none"});h.afterStorage?.();return{size:input.size,wholeSha256:input.wholeSha256,storedSize:input.size+32,storedSha256:"b".repeat(64),encryptionIvBase64:input.ivBase64,reused:false,writeEvidence:"confirmed"};},async writeResourceStagingFile(){return{writeEvidence:"confirmed"};},async deleteResourceStoredFile(ref:Row){h.storageDeletes.push(ref.storageKey);if(h.storageFailure)throw Error("PRIVATE_STORAGE");},async resourceStoredFileExists(){return !!h.exists;},async readResourceStoredFile(_ref:Row,options:Row){await options.beforeExpose?.();return{body:new ReadableStream({start(c){c.enqueue(new Uint8Array([1,2,3]));c.close();}}),size:3,verifiedSha256:"a".repeat(64),mimeType:h.preview===false?"application/octet-stream":"application/pdf",previewKind:h.preview===false?null:"pdf"};}};
const webAdapter=url(`import {readResourceAttachment as read, resourceFailure, resourceJson} from ${JSON.stringify(adapter)};export {resourceFailure,resourceJson};export function readResourceAttachment(context,id,options){const {db,storage,h}=globalThis.${key};return read({...context,db,storage,now:()=>h.now},id,options);}`);
const webDownload=await import(compile("app/resources/attachments/[id]/route.ts",{"@/lib/auth":mocks,"@/lib/mobile-resources":webAdapter})),webPreview=await import(compile("app/resources/attachments/[id]/preview/route.ts",{"@/lib/auth":mocks,"@/lib/mobile-resources":webAdapter}));
(globalThis as Row)[key].storage=storage;h.now=now;
const maintenancePort=url(`import {reconcileResourceLibraryMaintenance as reconcile} from ${JSON.stringify(cleanup)};export async function reconcileResourceLibraryMaintenance(context,options){const {db,storage,h}=globalThis.${key};h.maintenanceCalls=(h.maintenanceCalls??0)+1;return reconcile({...context,db,storage,now:()=>h.now},options);}`);
// The resource regression keeps the real dispatcher/resource domain; unrelated lanes are empty synthetic ports.
const maintenanceEmptyPort=url(`export async function reconcileYouthDecisionUploadExpiry(){return{checked:0,expired:0};}export async function reconcileYouthDecisionFileQueue(){return{checked:0,completed:0};}export async function reconcileYouthPurgeMaintenance(){return{checked:0,completed:0,pending:0};}`);
const maintenanceDispatcher=compile("lib/internal-file-maintenance.ts",{"@/lib/resource-file-cleanup":maintenancePort,"@/lib/youth-decision-file-cleanup":maintenanceEmptyPort,"@/lib/youth-purge":maintenanceEmptyPort});
const maintenanceRoute=await import(compile("app/api/internal/resource-maintenance/route.ts",{"@/lib/internal-file-maintenance":maintenanceDispatcher}));
const ctx=(actorId=actor.id)=>({actorId,db,now:()=>new Date(now),storage});
const values=(extra:Row={})=>({requestId:"request-create",title:"자료 제목",summary:"자료 설명입니다.",category:"bajaul",educationLevel:null,uploadIds:[],...extra});
async function create(extra:Row={},context=ctx()){return domain.mutateResource(context,{operation:"create",data:values(extra)});}
function post(extra:Row={}){const row={id:"post",title:"저장 자료",summary:"저장된 설명",category:"bajaul",educationLevel:null,authorId:actor.id,pinned:false,viewCount:0,createdAt:now,updatedAt:now,...extra};h.state.resourcePost.push(row);return row;}
function ready(extra:Row={}){const row={id:"upload",actorId:actor.id,purpose:"resource",targetResourceId:null,originalName:"자료.pdf",mimeType:"application/pdf",size:3,expectedSha256:"a".repeat(64),plaintextSha256:"a".repeat(64),storedSha256:"b".repeat(64),storedSize:35,storageProvider:"local",stagingKey:"resources/staging/id",finalKey:"resources/final/id",state:"ready",finalizeWriteEvidence:"confirmed",hadUnknownWrite:false,expiresAt:new Date(now.getTime()+100000),completedAt:now,lastGrantExpiresAt:null,finalizeLeaseUntil:null,...extra};h.state.resourceUpload.push(row);return row;}
function request(action:string,body?:unknown,path=""){return api.mobileResourceResponse(new Request("https://fixture.invalid/api/mobile/resources"+path,{method:body===undefined?"GET":"POST",headers:{authorization:`Bearer ${"t".repeat(43)}`,"content-type":"application/json"},...(body===undefined?{}:{body:typeof body==="string"?body:JSON.stringify(body)})}),action);}
beforeEach(()=>{h.state=Object.fromEntries(tables.map(model=>[model,[]]));h.state.user=structuredClone([actor,other]);Object.assign(h,{reads:[],writes:[],sql:[],next:0,auditFailure:false,storageFailure:false,storageDeletes:[],beforeTx:null,txErrors:[],cacheFailure:false,preview:true,afterStorage:null,exists:false,unknown:false});h.session={userId:actor.id,user:structuredClone(actor),expiresAt:new Date(Date.now()+60000)};});
after(()=>delete(globalThis as Row)[key]);
test("all 18 mobile method families auth before invalid query/body/params",async()=>{h.session=null;for(const action of["list","create","options","detail","editor","viewers","view","update","delete","mutation","upload-start","upload-status","upload-grant","upload-complete","upload-cancel","attachment","preview","download"]){const response=await request(action,"malformed", "?unknown=1");assert.equal(response.status,401);assert.equal(response.headers.get("cache-control"),"private, no-store");assert.equal(response.headers.get("x-content-type-options"),"nosniff");assert.equal(response.headers.get("location"),null);assert.doesNotMatch(await response.text(),/PRIVATE|storageKey|grant/);}assert.deepEqual(h.reads,[]);assert.deepEqual(h.writes,[]);});
test("fresh inactive/deleted actor prevents all reads/writes after session precheck",async()=>{post();h.state.user[0].status="INACTIVE";await assert.rejects(query.getResourceDetail(ctx(),"post"),{code:"UNAUTHORIZED"});await assert.rejects(create(),{code:"UNAUTHORIZED"});assert.equal(h.writes.length,0);});
test("safe pure list/options/detail/editor/viewers/status return no keys and write zero",async()=>{post();ready();for(const call of[()=>query.getResourcePage(ctx(),{category:"bajaul",level:"all",q:"",page:999}),()=>query.getResourceOptions(ctx()),()=>query.getResourceDetail(ctx(),"post"),()=>query.getResourceEditor(ctx(),"post"),()=>query.getResourceViewers(ctx(),"post"),()=>upload.getResourceUploadStatus(ctx(),{id:"upload"})])assert.doesNotMatch(JSON.stringify(await call()),/PRIVATE|storageKey|finalize|startPayload|lastGrant/);assert.deepEqual(h.writes,[]);});
test("stable pinned created id pagination and own/admin edit authorization",async()=>{for(let i=0;i<8;i++)post({id:"p"+i,pinned:i===0,authorId:other.id});const page=await query.getResourcePage(ctx(),{category:"bajaul",level:"all",q:"",page:999});assert.equal(page.page,3);assert.equal(page.pageSize,3);assert.equal(page.total,8);await assert.rejects(query.getResourceEditor(ctx(),"p1"),{code:"FORBIDDEN"});h.state.user[0].role="ADMIN";assert.equal((await query.getResourceEditor(ctx(),"p1")).resource.canManage,true);});
test("visit A B late-A counts once per event and preserves content baseline",async()=>{post();const visit=(requestId:string)=>domain.recordResourceView(ctx(),{resourceId:"post",requestId});await visit("visit-key-A");await visit("visit-key-B");const replay=await visit("visit-key-A");assert.equal(replay.replayed,true);assert.equal(replay.viewer.visitCount,2);assert.equal(replay.uniqueViewerCount,1);assert.equal(h.state.resourcePost[0].updatedAt.getTime(),now.getTime());await domain.recordResourceView(ctx(other.id),{resourceId:"post",requestId:"visit-other"});assert.equal(h.state.resourcePost[0].viewCount,2);assert.equal(h.state.auditLog.length,0);});
test("create same key/canonical trimmed payload replay has no duplicate audit",async()=>{const result=await create();const replay=await create({title:"  자료 제목 "});assert.equal(replay.replayed,true);assert.equal(replay.resourceId,result.resourceId);assert.equal(h.state.resourcePost.length,1);assert.equal(h.state.auditLog.length,1);assert.equal(h.state.auditLog[0].targetType,"ResourcePost");await assert.rejects(create({summary:"변경된 설명입니다."}),{code:"REQUEST_CONFLICT"});});
test("update CAS monotonic same-ms and replay before stale baseline",async()=>{const row=post();const data=values({requestId:"update-key",expectedUpdatedAt:row.updatedAt.toISOString(),removeAttachmentIds:[]});const first=await domain.mutateResource(ctx(),{operation:"update",resourceId:row.id,data});assert.equal(first.resource.updatedAt,new Date(now.getTime()+1).toISOString());const replay=await domain.mutateResource(ctx(),{operation:"update",resourceId:row.id,data});assert.equal(replay.replayed,true);await assert.rejects(domain.mutateResource(ctx(),{operation:"update",resourceId:row.id,data:{...data,requestId:"new-update-key"}}),{code:"RESOURCE_CONFLICT"});});
test("matching committed create receipt survives hard delete and never re-creates",async()=>{const first=await create();await domain.mutateResource(ctx(),{operation:"delete",resourceId:first.resourceId,data:{requestId:"delete-key",expectedUpdatedAt:first.resource.updatedAt}});const replay=await create();assert.equal(replay.outcome,"deleted");assert.equal(replay.resource,null);assert.equal(h.state.resourcePost.length,0);assert.equal(h.state.resourceMutationReceipt.length,2);});
test("ADMIN loss rejects live receipt status/replay without exposing other body",async()=>{h.state.user[0].role="ADMIN";post({authorId:other.id});const data=values({requestId:"admin-update",expectedUpdatedAt:now.toISOString(),removeAttachmentIds:[]});await domain.mutateResource(ctx(),{operation:"update",resourceId:"post",data});h.state.user[0].role="USER";await assert.rejects(domain.getResourceMutationStatus(ctx(),data.requestId),{code:"FORBIDDEN"});await assert.rejects(domain.mutateResource(ctx(),{operation:"update",resourceId:"post",data}),{code:"FORBIDDEN"});});
test("atomic upload consume/audit/receipt rollback and prepared retry",async()=>{ready();h.auditFailure=true;await assert.rejects(create({uploadIds:["upload"]}));assert.equal(h.state.resourcePost.length,0);assert.equal(h.state.resourceAttachment.length,0);assert.equal(h.state.resourceUpload[0].state,"ready");assert.equal(h.state.resourceMutationReceipt.length,0);h.auditFailure=false;const result=await create({uploadIds:["upload"]});assert.equal(result.resource.attachments.length,1);assert.equal(h.state.resourceUpload[0].state,"consumed");assert.equal(h.state.resourceFileCleanup[0].objectKind,"staging");});
test("foreign purpose target expired unconfirmed receipt never consumed",async()=>{for(const override of[{actorId:other.id},{purpose:"document"},{targetResourceId:"other"},{expiresAt:now},{finalizeWriteEvidence:"unknown"},{state:"consumed"}]){h.state.resourceUpload=[];ready(override);await assert.rejects(create({uploadIds:["upload"]}),{code:"UPLOAD_CONFLICT"});assert.equal(h.state.resourcePost.length,0);}});
test("new policy validates new receipt only and total includes retained legacy",async()=>{post();h.state.resourceAttachment.push({id:"legacy",resourceId:"post",originalName:"legacy.disallowed",size:999999999,mimeType:"other",storageProvider:"local",storageKey:"legacy"});ready({targetResourceId:"post",originalName:"new.disallowed"});await assert.rejects(domain.mutateResource(ctx(),{operation:"update",resourceId:"post",data:values({requestId:"policy-key",uploadIds:["upload"],removeAttachmentIds:[],expectedUpdatedAt:now.toISOString()})}),{code:"ATTACHMENT_POLICY"});h.state.resourceUpload=[];const result=await domain.mutateResource(ctx(),{operation:"update",resourceId:"post",data:values({requestId:"retained-key",removeAttachmentIds:[],expectedUpdatedAt:now.toISOString()})});assert.equal(result.resource.attachments.length,1);});
test("mobile foreign removal rejects while web intersection preserves legacy",async()=>{post();const data=values({requestId:"remove-key",expectedUpdatedAt:now.toISOString(),removeAttachmentIds:["foreign"]});await assert.rejects(domain.mutateResource(ctx(),{operation:"update",resourceId:"post",data}),{code:"INVALID_REQUEST"});assert.equal((await domain.mutateResource({...ctx(),strictRemoveIds:false},{operation:"update",resourceId:"post",data})).ok,true);});
test("business delete stays successful with storage cleanup failure and replay",async()=>{post();h.state.resourceAttachment.push({id:"legacy",resourceId:"post",originalName:"old.pdf",size:3,mimeType:"application/pdf",storageProvider:"local",storageKey:"legacy"});h.storageFailure=true;const data={requestId:"delete-failure-key",expectedUpdatedAt:now.toISOString()};const result=await domain.mutateResource(ctx(),{operation:"delete",resourceId:"post",data});assert.equal(result.ok,true);assert.equal(result.cleanupPending,true);assert.equal(h.state.resourcePost.length,0);assert.equal(h.state.resourceFileCleanup[0].state,"pending");assert.equal((await domain.mutateResource(ctx(),{operation:"delete",resourceId:"post",data})).replayed,true);});
test("shared legacy keys referenced by all known owners are never deleted",async()=>{for(const model of["resourceAttachment","attachment","youthDecisionDocument","mobileDraftUpload","staffChatAttachment","user"]){h.state.resourceFileCleanup=[];h.storageDeletes=[];for(const m of["resourceAttachment","attachment","youthDecisionDocument","mobileDraftUpload","staffChatAttachment"])h.state[m]=[];h.state.user=structuredClone([actor,other]);if(model==="user"){h.state.user[1].profileImageStorageKey="shared";h.state.user[1].profileImageStorageProvider="local";}else h.state[model].push({id:"ref",storageProvider:"local",storageKey:"shared",deletedAt:null});await db.$transaction((tx:Row)=>clean.enqueueResourceFileCleanup(tx,{ref:{storageProvider:"local",storageKey:"shared"},objectKind:"legacy"},now));await clean.reconcileResourceFileQueue(ctx());assert.deepEqual(h.storageDeletes,[]);assert.equal(h.state.resourceFileCleanup[0].lastErrorCode,"LIVE_REFERENCE");}});
test("unknown deleting writer late object is repeatedly deleted but never false done",async()=>{const row=ready({state:"deleting",hadUnknownWrite:true,finalizeWriteEvidence:"unknown",originalName:null,mimeType:null,size:null,expectedSha256:null});await db.$transaction((tx:Row)=>clean.queueResourceUploadFiles(tx,row,now));await clean.reconcileResourceFileQueue(ctx());assert.equal(h.storageDeletes.length,2);assert.ok(h.state.resourceFileCleanup.every((row:Row)=>row.state==="pending"&&row.lastErrorCode==="WRITE_PENDING"));});
test("active grant and current finalization lease prevent provider deletion",async()=>{const row=ready({state:"deleting",lastGrantExpiresAt:new Date(now.getTime()+100000),finalizeLeaseUntil:new Date(now.getTime()+100000)});await db.$transaction((tx:Row)=>clean.queueResourceUploadFiles(tx,row,now));await clean.reconcileResourceFileQueue(ctx());assert.deepEqual(h.storageDeletes,[]);});
test("trusted maintenance expires inactive/deleted owner uploads and minimizes descriptor",async()=>{ready({actorId:"deleted-user",expiresAt:now});await clean.reconcileResourceLibraryMaintenance({db,now:()=>now,storage});assert.ok(["deleting","expired"].includes(h.state.resourceUpload[0].state));assert.equal(h.state.resourceUpload[0].originalName,null);});
test("owner upload status has no writes and other owner gets indistinguishable404",async()=>{ready();await assert.rejects(upload.getResourceUploadStatus(ctx(other.id),{id:"upload"}),{code:"NOT_FOUND"});await upload.getResourceUploadStatus(ctx(),{id:"upload"});assert.deepEqual(h.writes,[]);});
test("complete validates exact provider proof then ready and repeated complete no extra writes",async()=>{ready({state:"uploading",plaintextSha256:null,completedAt:null});const result=await upload.completeResourceUpload(ctx(),"upload");assert.equal(result.upload.state,"ready");assert.equal(result.pending,false);const count=h.writes.length;assert.equal((await upload.completeResourceUpload(ctx(),"upload")).pending,false);assert.equal(h.writes.length,count);});
test("unknown final write persisted even after lease release and cancellation",async()=>{ready({state:"uploading",plaintextSha256:null,completedAt:null});h.storageFailure=true;h.unknown=true;await assert.rejects(upload.completeResourceUpload(ctx(),"upload"),{code:"STORAGE_UNAVAILABLE"});assert.equal(h.state.resourceUpload[0].hadUnknownWrite,true);h.storageFailure=false;const result=await upload.cancelResourceUpload(ctx(),"upload");assert.equal(result.upload.file,null);assert.equal(result.upload.state,"deleting");});
test("actual verified MIME preview blocks forged extension and download is non-consuming",async()=>{post();h.state.resourceAttachment.push({id:"file",resourceId:"post",originalName:"forged.pdf",mimeType:"application/pdf",size:3,storageProvider:"local",storageKey:"private"});h.preview=false;await assert.rejects(api.readResourceAttachment(ctx(),"file",{preview:true}),{code:"UNSUPPORTED_PREVIEW"});const response=await api.readResourceAttachment(ctx(),"file");assert.equal(response.headers.get("content-type"),"application/octet-stream");assert.equal(response.headers.get("cache-control"),"private, no-store");assert.equal(response.headers.get("content-disposition")!.startsWith("attachment;"),true);await response.arrayBuffer();assert.deepEqual(h.writes,[]);});
test("strict JSON transport duplicate decoded keys malformed UTF8 declared mismatch and streaming cap",async()=>{for(const body of['{"requestId":"a","requestId":"b"}','{"x":1,"\\u0078":2}',"{bad}"]){await assert.rejects(core.readResourceJson(new Request("https://fixture.invalid",{method:"POST",headers:{"content-type":"application/json"},body})));}await assert.rejects(core.readResourceJson(new Request("https://fixture.invalid",{method:"POST",headers:{"content-type":"application/json","content-length":"2"},body:"{} "})),{code:"INVALID_REQUEST"});await assert.rejects(core.readResourceJson(new Request("https://fixture.invalid",{method:"POST",headers:{"content-type":"application/json"},body:new Uint8Array([255])})));await assert.rejects(core.readResourceJson(new Request("https://fixture.invalid",{method:"POST",headers:{"content-type":"application/json"},body:" ".repeat(65537)})),{code:"PAYLOAD_TOO_LARGE"});});
test("strict queries reject duplicate/unknown/coercion/unsafe page; valid canonical trim",()=>{for(const path of["?page=0","?page=01","?page=1.0","?page=9007199254740992","?page=1&page=1","?role=ADMIN","?category=unknown","?q="+"a".repeat(8193)])assert.throws(()=>core.parseResourcePageQuery(new URL("https://fixture.invalid"+path)));assert.equal(core.parseResourcePageQuery(new URL("https://fixture.invalid?category=education&level=high&q=%20test%20")).q,"test");});
test("bounded exact retry recognizes real adapter serialization only",async()=>{const conflict=Object.assign(Error("driver"),{name:"DriverAdapterError",cause:{kind:"TransactionWriteConflict"}});h.txErrors=[conflict,conflict];await create();assert.equal(h.state.auditLog.length,1);for(const error of[Object.assign(Error("unknown"),{code:"P2034"}),Object.assign(Error("constraint"),{name:"DriverAdapterError",cause:{kind:"PostgresError",code:"23514"}})])assert.equal(query.resourceTransactionConflict(error),false);});

test("actual delete/remove legacy-first queues retain upload evidence and minimize descriptor",async()=>{for(const operation of ["delete","update"]){h.state.resourcePost=[];h.state.resourceAttachment=[];h.state.resourceUpload=[];h.state.resourceFileCleanup=[];h.state.resourceMutationReceipt=[];h.storageDeletes=[];post();ready({state:"consumed",targetResourceId:"post",consumedResourceId:"post",consumedAttachmentId:"file",hadUnknownWrite:true});h.state.resourceAttachment.push({id:"file",resourceId:"post",originalName:"file.pdf",mimeType:"application/pdf",size:3,storageProvider:"local",storageKey:"resources/final/id"});const data=operation==="delete"?{requestId:"delete-link-key",expectedUpdatedAt:now.toISOString()}:values({requestId:"update-link-key",expectedUpdatedAt:now.toISOString(),removeAttachmentIds:["file"]});await domain.mutateResource(ctx(),{operation,resourceId:"post",data});const final=h.state.resourceFileCleanup.find((row:Row)=>row.storageKey==="resources/final/id");assert.equal(final.sourceUploadId,"upload");assert.equal(final.objectKind,"final");assert.equal(final.state,"pending");assert.equal(final.lastErrorCode,"WRITE_PENDING");assert.equal(h.state.resourceUpload[0].originalName,null);assert.ok(h.storageDeletes.includes("resources/final/id"));}});
test("profile and signature references independently protect cleanup key",async()=>{h.state.user[1].signatureImageStorageKey="signature-key";h.state.user[1].signatureImageStorageProvider="local";await db.$transaction((tx:Row)=>clean.enqueueResourceFileCleanup(tx,{ref:{storageProvider:"local",storageKey:"signature-key"},objectKind:"legacy"},now));await clean.reconcileResourceFileQueue(ctx());assert.deepEqual(h.storageDeletes,[]);assert.equal(h.state.resourceFileCleanup[0].lastErrorCode,"LIVE_REFERENCE");});
test("expired grant staging is softly deleted repeatedly without durable absence assumption",async()=>{const row=ready({state:"consumed",lastGrantExpiresAt:new Date(now.getTime()-1)});await db.$transaction((tx:Row)=>clean.enqueueResourceFileCleanup(tx,{ref:{storageProvider:row.storageProvider,storageKey:row.stagingKey},objectKind:"staging",sourceUploadId:row.id},now));await clean.reconcileResourceFileQueue(ctx());assert.equal(h.storageDeletes.length,1);assert.equal(h.state.resourceFileCleanup[0].state,"pending");assert.equal(h.state.resourceFileCleanup[0].lastErrorCode,"WRITE_PENDING");});
test("provider success followed by actor suspension persists quiescence proof but never ready",async()=>{ready({state:"uploading",plaintextSha256:null,completedAt:null});h.afterStorage=()=>{h.state.user[0].status="INACTIVE";};await assert.rejects(upload.completeResourceUpload(ctx(),"upload"),{code:"UNAUTHORIZED"});assert.equal(h.state.resourceUpload[0].state,"finalizing");assert.equal(h.state.resourceUpload[0].finalizeWriteEvidence,"confirmed");assert.equal(h.state.resourceUpload[0].completedAt,null);});
test("safe exact receipt unique classifier accepts only the named model/fields",()=>{const error=(modelName:string,target:unknown)=>Object.assign(Error("unique"),{name:"PrismaClientKnownRequestError",code:"P2002",meta:{modelName,target}});assert.equal(query.resourceReceiptConflict(error("ResourceMutationReceipt",["actorId","requestId"]),"ResourceMutationReceipt"),true);for(const e of[error("ResourcePost",["actorId","requestId"]),error("ResourceMutationReceipt",["id"]),error("ResourceMutationReceipt",["actorId","requestId","extra"])])assert.equal(query.resourceReceiptConflict(e,"ResourceMutationReceipt"),false);});

test("signed staging causal late PUT recreation is removed again and never loses queue key",async()=>{const row=ready({state:"deleting",originalName:null,mimeType:null,size:null,expectedSha256:null,lastGrantExpiresAt:new Date(now.getTime()-1)}),objects=new Set([row.stagingKey]);let at=new Date(now);const causal={...storage,async deleteResourceStoredFile(ref:Row){objects.delete(ref.storageKey);},async resourceStoredFileExists(ref:Row){return objects.has(ref.storageKey);}};const context={...ctx(),storage:causal,now:()=>at};await db.$transaction((tx:Row)=>clean.enqueueResourceFileCleanup(tx,{ref:{storageProvider:row.storageProvider,storageKey:row.stagingKey},objectKind:"staging",sourceUploadId:row.id},now));await clean.reconcileResourceFileQueue(context);assert.equal(objects.size,0);assert.equal(h.state.resourceFileCleanup[0].state,"pending");objects.add(row.stagingKey);at=new Date(now.getTime()+120000);await clean.reconcileResourceFileQueue(context);assert.equal(objects.size,0);assert.equal(h.state.resourceFileCleanup[0].storageKey,row.stagingKey);assert.equal(h.state.resourceFileCleanup[0].state,"pending");assert.equal(h.state.resourceFileCleanup[0].lastErrorCode,"WRITE_PENDING");});
test("grant issuance delayed actual expiry is durable, returned provider fact preserved",async()=>{const row=ready({state:"uploading",storageProvider:"supabase-storage"});const actual=new Date(now.getTime()+7200000+15000);const context={...ctx(),storage:{...storage,async createResourceStagingGrant(){return{method:"PUT",url:"https://staging.invalid/opaque",headers:{"Content-Type":"application/pdf"},expiresAt:actual};}}};const result=await upload.grantResourceUpload(context,row.id);assert.equal(result.grant.expiresAt,actual.toISOString());assert.equal(h.state.resourceUpload[0].lastGrantExpiresAt.toISOString(),actual.toISOString());assert.equal(JSON.stringify(await upload.getResourceUploadStatus(ctx(),{id:row.id})).includes("url"),false);});
test("stale worker unknown persists independently of newer claim and ready proof",async()=>{ready({state:"uploading",plaintextSha256:null,completedAt:null});const context={...ctx(),storage:{...storage,async finalizeResourceStoredUpload(){h.state.resourceUpload[0].finalizeClaimId="newer-claim";h.state.resourceUpload[0].finalizeWriteEvidence="confirmed";throw Object.assign(Error("late-old-write"),{writeEvidence:"unknown"});}}};await assert.rejects(upload.completeResourceUpload(context,"upload"),{code:"STORAGE_UNAVAILABLE"});assert.equal(h.state.resourceUpload[0].hadUnknownWrite,true);assert.equal(h.state.resourceUpload[0].finalizeClaimId,"newer-claim");assert.equal(h.state.resourceUpload[0].finalizeWriteEvidence,"confirmed");});
test("late final callback after cancel never restores cleared descriptor or marks ready",async()=>{ready({state:"uploading",plaintextSha256:null,completedAt:null});h.afterStorage=()=>{const row=h.state.resourceUpload[0];row.state="deleting";row.originalName=null;row.mimeType=null;row.size=null;row.expectedSha256=null;};const result=await upload.completeResourceUpload(ctx(),"upload");assert.equal(result.upload.state,"deleting");assert.equal(result.upload.file,null);assert.equal(h.state.resourceUpload[0].finalizeWriteEvidence,"confirmed");assert.equal(h.state.resourceUpload[0].completedAt,null);});
test("server File stream fallback keeps same consumed receipt and no arrayBuffer",async()=>{const file=new File([new Uint8Array([1,2,3])],"example.pdf",{type:"application/pdf"});file.arrayBuffer=async()=>{throw Error("arrayBuffer forbidden");};const started=await upload.createResourceServerUpload(ctx(),{requestId:"server-file-key",targetResourceId:null,file});assert.equal(started.upload.state,"ready");const result=await create({uploadIds:[started.upload.id]});const replay=await upload.createResourceServerUpload(ctx(),{requestId:"server-file-key",targetResourceId:null,file});assert.equal(replay.upload.id,started.upload.id);assert.equal(replay.upload.state,"consumed");assert.equal((await create({uploadIds:[started.upload.id]})).resourceId,result.resourceId);});

test("known missing-stage no-finalwrite restores same receipt uploading and permits same grant",async()=>{ready({state:"uploading",storageProvider:"supabase-storage",plaintextSha256:null,completedAt:null});h.storageFailure=true;await assert.rejects(upload.completeResourceUpload(ctx(),"upload"),{code:"UPLOAD_RETRY"});assert.equal(h.state.resourceUpload[0].state,"uploading");assert.equal(h.state.resourceUpload[0].hadUnknownWrite,false);h.storageFailure=false;const grant=await upload.grantResourceUpload(ctx(),"upload");assert.equal(grant.upload.id,"upload");assert.ok(grant.grant);});
test("expired uncertain claim persists unknown even when new worker fails before write",async()=>{ready({state:"finalizing",storageProvider:"supabase-storage",plaintextSha256:null,completedAt:null,finalizeWriteEvidence:"pending",finalizeLeaseUntil:new Date(now.getTime()-1)});h.storageFailure=true;await assert.rejects(upload.completeResourceUpload(ctx(),"upload"));assert.equal(h.state.resourceUpload[0].hadUnknownWrite,true);assert.equal(h.state.resourceUpload[0].state,"finalizing");await assert.rejects(upload.grantResourceUpload(ctx(),"upload"),{code:"UPLOAD_CONFLICT"});});
test("intermediate stored cipher sizes cannot become ready even with correct plaintext hash",async()=>{for(const overhead of[1,15,31]){h.state.resourceUpload=[];ready({state:"uploading",plaintextSha256:null,completedAt:null});const context={...ctx(),storage:{...storage,async finalizeResourceStoredUpload(input:Row){return{...await storage.finalizeResourceStoredUpload(input),storedSize:input.size+overhead};}}};await assert.rejects(upload.completeResourceUpload(context,"upload"),{code:"UPLOAD_CONFLICT"});assert.equal(h.state.resourceUpload[0].state,"finalizing");assert.equal(h.state.resourceUpload[0].hadUnknownWrite,true);assert.equal(h.state.resourceUpload[0].completedAt,null);}});

test("actual web binary cookie auth precedes params and all failure/success statuses stay private",async()=>{h.session=null;let paramsRead=false;const params={then(){paramsRead=true;throw Error("invalid params read");}};for(const route of[webDownload,webPreview]){const response=await route.GET(new Request("https://fixture.invalid/resources/attachments/file"),{params});assert.equal(response.status,401);assert.equal(response.headers.get("cache-control"),"private, no-store");}assert.equal(paramsRead,false);h.session={user:actor};post();h.state.resourceAttachment.push({id:"file",resourceId:"post",originalName:"real.pdf",mimeType:"application/pdf",size:3,storageProvider:"local",storageKey:"private"});const context={params:Promise.resolve({id:"file"})};h.preview=false;const unsupported=await webPreview.GET(new Request("https://fixture.invalid"),context);assert.equal(unsupported.status,415);assert.equal(unsupported.headers.get("x-content-type-options"),"nosniff");h.preview=true;const response=await webDownload.GET(new Request("https://fixture.invalid"),context);assert.equal(response.status,200);assert.equal(response.headers.get("cache-control"),"private, no-store");await response.arrayBuffer();h.state.user[0].status="INACTIVE";assert.equal((await webDownload.GET(new Request("https://fixture.invalid"),context)).status,401);assert.deepEqual(h.writes,[]);});

test("older cleanup result cannot publish done over a newer durable claim",async()=>{await db.$transaction((tx:Row)=>clean.enqueueResourceFileCleanup(tx,{ref:{storageProvider:"local",storageKey:"fenced-key"},objectKind:"legacy",sourceMutationId:"fenced-mutation"},now));const context={...ctx(),storage:{...storage,async deleteResourceStoredFile(){const row=h.state.resourceFileCleanup[0];row.claimId="newer-queue-claim";row.leaseUntil=new Date(now.getTime()+60000);}}};const result=await clean.reconcileResourceFileQueue(context);assert.equal(result.completed,0);assert.equal(h.state.resourceFileCleanup[0].state,"running");assert.equal(h.state.resourceFileCleanup[0].claimId,"newer-queue-claim");assert.equal(h.state.resourceFileCleanup[0].completedAt,null);});


test("actual cron and domain expire40 across four grant-gated batches with public counts unchanged",async()=>{
  for(let i=0;i<40;i++)ready({id:`expired-${i}`,actorId:"deleted-user",state:"uploading",expiresAt:now,completedAt:null,finalKey:null,stagingKey:`resources/staging/expired-${i}`,lastGrantExpiresAt:new Date(now.getTime()+60000)});
  const originalSecret=process.env.CRON_SECRET;process.env.CRON_SECRET="synthetic-maintenance-only";h.maintenanceCalls=0;
  try{const response=await maintenanceRoute.GET(new Request("https://fixture.invalid/api/internal/resource-maintenance",{headers:{authorization:"Bearer synthetic-maintenance-only"}}));assert.equal(response.status,200);const summary=await response.json();assert.deepEqual({ok:summary.ok,checked:summary.checked,completed:summary.completed},{ok:true,checked:0,completed:0});assert.equal(summary.lanes.resource.expired,40);assert.equal(summary.lanes.resource.batches,4);assert.equal(summary.lanes.resource.failed,false);assert.equal(summary.lanes.approvedPurge.checked,0);assert.equal(h.maintenanceCalls,4);assert.equal(h.state.resourceUpload.filter((row:Row)=>row.state==="deleting").length,40);assert.equal(h.state.resourceFileCleanup.length,40);assert.deepEqual(h.storageDeletes,[]);assert.ok(h.state.resourceUpload.every((row:Row)=>row.originalName===null&&row.mimeType===null&&row.size===null));}
  finally{if(originalSecret===undefined)delete process.env.CRON_SECRET;else process.env.CRON_SECRET=originalSecret;}
});
test("maintenance expiration count excludes a candidate consumed before its locked transaction",async()=>{
  ready({expiresAt:now});let transactions=0;h.beforeTx=()=>{if(++transactions===2)h.state.resourceUpload[0].state="consumed";};
  const result=await clean.reconcileResourceLibraryMaintenance({db,now:()=>now,storage},{limit:10});assert.deepEqual(result,{checked:0,completed:0,expired:0});assert.equal(h.state.resourceUpload[0].state,"consumed");assert.equal(h.state.resourceFileCleanup.length,0);assert.deepEqual(h.storageDeletes,[]);
});


test("cleanup projects storage identity from full attachment descriptors and preserves its own queue ID",async()=>{
  const attachment={id:"attachment-identity",originalName:"PRIVATE_FILENAME.pdf",mimeType:"application/pdf",size:3,createdAt:now,resourceId:"post-identity",uploaderId:actor.id,storageProvider:"local",storageKey:"resources/final/immutable"};
  const first=await clean.enqueueResourceFileCleanup(db,{ref:attachment,objectKind:"legacy",sourceMutationId:"mutation-original"},now);
  const replay=await clean.enqueueResourceFileCleanup(db,{ref:{...attachment,id:"other-attachment",resourceId:"other-post"},objectKind:"legacy",sourceMutationId:"mutation-other"},now);
  assert.equal(replay,first);assert.notEqual(first,attachment.id);assert.equal(h.state.resourceFileCleanup.length,1);
  const row=h.state.resourceFileCleanup[0];assert.equal(row.storageProvider,attachment.storageProvider);assert.equal(row.storageKey,attachment.storageKey);
  for(const field of["originalName","mimeType","size","resourceId","uploaderId"])assert.equal(field in row,false);
});


test("historical known staging completion differs from sticky unknown evidence present before consume",async()=>{
  const known=ready({id:"known-upload",stagingKey:"resources/staging/known",finalKey:"resources/final/known"});
  const knownPost=await create({requestId:"known-consume",uploadIds:[known.id]});
  const knownStage=h.state.resourceFileCleanup.find((row:Row)=>row.storageKey==="resources/staging/known");assert.equal(knownStage.state,"done");assert.equal(knownStage.lastErrorCode,null);assert.equal(known.stagingKey,null);
  // Reproduce the old PG fixture ordering: the later flag cannot retroactively
  // turn the already-confirmed historical staging queue into a pending row.
  known.hadUnknownWrite=true;h.storageFailure=true;
  await domain.mutateResource(ctx(),{operation:"delete",resourceId:knownPost.resourceId,data:{requestId:"known-delete",expectedUpdatedAt:knownPost.resource.updatedAt}});
  h.storageFailure=false;for(const row of h.state.resourceFileCleanup.filter((row:Row)=>row.sourceUploadId===known.id))row.nextAttemptAt=now;
  await clean.reconcileResourceFileQueue(ctx());
  const knownRows=h.state.resourceFileCleanup.filter((row:Row)=>row.sourceUploadId===known.id);assert.equal(knownRows.length,2);assert.equal(knownStage.state,"done");assert.ok(knownRows.some((row:Row)=>row.objectKind==="final"&&row.state==="pending"&&row.lastErrorCode==="WRITE_PENDING"));assert.equal(knownRows.every((row:Row)=>row.state==="pending"),false);
  const uncertain=ready({id:"uncertain-upload",hadUnknownWrite:true,stagingKey:"resources/staging/uncertain",finalKey:"resources/final/uncertain"});
  const uncertainPost=await create({requestId:"uncertain-consume",uploadIds:[uncertain.id]});
  const uncertainStage=h.state.resourceFileCleanup.find((row:Row)=>row.storageKey===uncertain.stagingKey);assert.equal(uncertainStage.state,"pending");assert.equal(uncertainStage.lastErrorCode,"WRITE_PENDING");assert.equal(uncertain.stagingKey,"resources/staging/uncertain");
  h.storageFailure=true;await domain.mutateResource(ctx(),{operation:"delete",resourceId:uncertainPost.resourceId,data:{requestId:"uncertain-delete",expectedUpdatedAt:uncertainPost.resource.updatedAt}});
  h.storageFailure=false;for(const row of h.state.resourceFileCleanup.filter((row:Row)=>row.sourceUploadId===uncertain.id))row.nextAttemptAt=now;
  await clean.reconcileResourceFileQueue(ctx(),{cleanupIds:h.state.resourceFileCleanup.filter((row:Row)=>row.sourceUploadId===uncertain.id).map((row:Row)=>row.id)});
  const uncertainRows=h.state.resourceFileCleanup.filter((row:Row)=>row.sourceUploadId===uncertain.id);assert.equal(uncertainRows.length,2);assert.deepEqual(new Set(uncertainRows.map((row:Row)=>row.storageKey)),new Set(["resources/staging/uncertain","resources/final/uncertain"]));assert.ok(uncertainRows.every((row:Row)=>row.state==="pending"&&row.lastErrorCode==="WRITE_PENDING"));
});
