import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { test } from "node:test";
import { sha256 } from "@noble/hashes/sha2.js";
import { call, file, nativeHarness, policy, webHarness } from "./helpers/mobile-resource-files.mjs";
const grant={method:"PUT",url:"https://storage.example/signed-synthetic",headers:{"Content-Type":"application/pdf"},expiresAt:"2099-01-01T00:00:00.000Z"};
test("native300MiB selection moves only owned picker cache and whole hash/upload are native streaming handles",async()=>{const h=nativeHarness();h.select(300*1024*1024);const c=call(),selected=await h.adapter.pick({policy},c);assert.equal(selected.size,300*1024*1024);assert.equal(await h.adapter.hash(selected.file,c),"a".repeat(64));await h.adapter.put(selected.file,grant,c);assert.equal(h.reads.length,0);assert.equal(h.wrapped[0].size,300*1024*1024);assert.deepEqual(h.requests[0].headers,{"Content-Type":"application/pdf"});assert.equal(h.requests[0].config.followRedirect,false);assert.equal(h.requests[0].method,"PUT");h.adapter.release(selected.file);});
test("native external picker URI never deletes original and disk shortage fails before binary GET",async()=>{const h=nativeHarness();h.select(12,"file:///outside/original.pdf");await assert.rejects(h.adapter.pick({policy},call()),{status:0});assert.ok(h.records.has("file:///outside/original.pdf"));h.setDisk(0);await assert.rejects(h.adapter.download("/resources/attachments/file/download",file,call()),{status:0});assert.equal(h.requests.length,0);});
test("native Android SAF uses display names, unique suffix and verifies exact external size",async()=>{const h=nativeHarness(),c=call(),result=await h.adapter.download("/resources/attachments/file/download",file,c);h.folder.createFile("actual.pdf");const message=await h.adapter.export(result.file,result.info,"save",c);assert.equal(message,"actual (1).pdf 파일을 저장했습니다.");const created=h.events.filter((event:unknown[])=>event[0]==="external");assert.equal(created.at(-1)[1],"actual (1).pdf");assert.ok(h.reads.every((size:number)=>size<=65536));assert.equal(h.records.get(created.at(-1)[2]).size,12);h.adapter.release(result.file);});
test("native partial external write removes only newly created partial and authenticated401 never opens chooser",async()=>{const h=nativeHarness(),c=call(),result=await h.adapter.download("/resources/attachments/file/download",file,c);h.folder.createFile("actual.pdf");h.setTruncate(true);await assert.rejects(h.adapter.export(result.file,result.info,"save",c),{status:0});assert.equal(h.folder.info().files.length,1);h.adapter.release(result.file);h.setStatus(401);let choosers=0;h.setDirectory(async()=>{choosers++;return h.folder;});await assert.rejects(h.adapter.download("/resources/attachments/file/download",file,c),{status:401});assert.equal(choosers,0);});
test("native iOS share returns truthful handoff copy and picker cancel writes no external file",async()=>{const h=nativeHarness(),c=call(),result=await h.adapter.download("/resources/attachments/file/download",file,c);h.setOS("ios");let shares=0;h.setShare(async()=>{shares++;});assert.match(await h.adapter.export(result.file,result.info,"save",c),/공유 창/);assert.equal(shares,1);h.setOS("android");h.setDirectory(async()=>{throw Object.assign(new Error("cancel"),{name:"AbortError"});});assert.equal(await h.adapter.export(result.file,result.info,"save",c),null);assert.equal(h.events.filter((event:unknown[])=>event[0]==="external").length,0);h.adapter.release(result.file);});
test("native download cancellation releases private partial before late response",async()=>{const h=nativeHarness(),c=call();let release!:(value:unknown)=>void;h.setTransport(()=>new Promise(resolve=>release=resolve));const pending=h.adapter.download("/resources/attachments/file/download",file,c);await Promise.resolve();c.cancel();release({status:200,headers:{}});await assert.rejects(pending,{name:"AbortError"});assert.equal([...h.records.keys()].filter((path:string)=>path.includes("resource-file-transfers")).length,0);});
test("web SHA uses oneMiB slices and actual maintained incremental SHA256",async()=>{const h=webHarness(sha256),c=call(),data=new Uint8Array(3*1024*1024+17).fill(71),widths:number[]=[];const blob=new Blob([data]);const handle={size:blob.size,slice(start:number,end:number){widths.push(end-start);return blob.slice(start,end);},arrayBuffer(){throw Error("Whole buffer forbidden");}};assert.equal(await h.adapter.hash(handle,c),createHash("sha256").update(data).digest("hex"));assert.equal(widths.length,4);assert.ok(widths.every(size=>size<=1024*1024));});
test("web signed PUT omits Bearer/cookies and redirects, and picker returns immutable Blob handle",async()=>{const h=webHarness(sha256),c=call();h.setSelected(new File([new TextEncoder().encode('%PDF-1.7\nabc')],"자료.pdf",{type:"application/pdf"}));const selected=await h.adapter.pick({policy},c);assert.equal(selected.file.size,12);h.setFetch(async()=>new Response(null,{status:200}));await h.adapter.put(selected.file,grant,c);assert.equal(h.calls[0].init.credentials,"omit");assert.equal(h.calls[0].init.redirect,"error");assert.deepEqual(h.calls[0].init.headers,{"Content-Type":"application/pdf"});});
test("web download/save is nonconsuming authenticated GET; account clear revokes pending objectURLs",async()=>{const h=webHarness(sha256),c=call(),result=await h.adapter.download("/resources/attachments/file/download",file,c);assert.equal(h.calls[0].init.headers.Authorization,"Bearer synthetic-token");assert.equal(h.calls[0].init.method,undefined);assert.match(await h.adapter.export(result.file,result.info,"save",c),/브라우저/);const anchor=h.elements.find((element:{tag:string})=>element.tag==="a");assert.equal(anchor.download,"actual.pdf");assert.equal(anchor.removed,true);await h.adapter.clear();assert.equal(h.revoked.length,1);assert.equal(h.timers.size,0);});
test("web wrong size and invalid preview MIME cannot silently export safe-looking file",async()=>{const h=webHarness(sha256);h.setFetch(async()=>new Response(new Uint8Array(13),{headers:{"Content-Length":"13","Content-Type":"application/pdf","Content-Disposition":"attachment; filename=a.pdf"}}));await assert.rejects(h.adapter.download("/resources/attachments/file/download",file,call()),{status:0});assert.equal(h.urls.length,0);});

test("web timeout and cancel reject even when transport ignores AbortSignal", async () => {
  for (const mode of ["timeout", "cancel"]) {
    const h=webHarness(sha256),c=call();h.setFetch(()=>new Promise(()=>{}));
    const pending=h.adapter.put(new Blob([new Uint8Array(12)]),grant,c);
    if(mode==="timeout") { const timer=[...h.timers.values()].find((value:{delay:number})=>value.delay===120000);assert.ok(timer);timer.fn(); }
    else c.cancel();
    await assert.rejects(pending,mode==="timeout"?{status:0}:{name:"AbortError"});
    assert.equal(h.timers.size,0);
  }
});

test("native account/startup cleanup removes orphan private cache without external originals",async()=>{
 const h=nativeHarness(),c=call(),selected=await h.adapter.pick({policy},c);
 h.records.set("file:///cache/resource-file-transfers/old-process/private.pdf",{bytes:new Uint8Array(12),size:12});
 h.records.set("file:///outside/original.pdf",{bytes:new Uint8Array(12),size:12});
 assert.ok(selected.file.file.exists);await h.adapter.clear();
 assert.equal([...h.records.keys()].filter((path:string)=>path.includes("resource-file-transfers")).length,0);
 assert.equal(h.records.has("file:///outside/original.pdf"),true);
});
