import assert from "node:assert/strict";
import { test } from "node:test";
import { ApiError } from "../mobile/src/lib/api";
import { isMobileResource, isResourceDetail, isResourceEditor, isResourceGrant, isResourceList, isResourceMutation, isResourceOptions, isResourceUpload, isResourceViewers, isResourceVisit, newResourceRequestId, resourceCategory, resourceFieldErrors, resourceLevel, resourcePage, resourceScalar, resourceUnknown, validateResourceFile } from "../mobile/src/lib/resources";
const iso="2026-10-03T00:00:00.000Z", newer="2026-10-03T00:00:00.001Z";
const author={id:"actor",name:"직원",departmentName:"지원",positionName:"담당"};
const policy={maxFileCount:10,maxFileSizeMb:30,allowedExtensions:[".pdf",".png"]};
const resource=(patch:Record<string,unknown>={})=>({id:"resource",title:"자료 제목",summary:"자료 본문 보관",category:"corporation",educationLevel:null,pinned:false,createdAt:iso,updatedAt:iso,uniqueViewerCount:1,author,canManage:true,attachments:[],...patch});
const upload=(patch:Record<string,unknown>={})=>({id:"upload",targetResourceId:null,file:{name:"자료.pdf",mimeType:"application/pdf",size:12,wholeSha256:"a".repeat(64)},state:"uploading",expiresAt:"2099-01-01T00:00:00.000Z",completedAt:null,consumedResourceId:null,cleanupPending:false,...patch});
test("explicit query arrays, whitespace and unsafe pages never silently choose another scope",()=>{assert.equal(resourceCategory(undefined),"corporation");assert.equal(resourceCategory(" corporation"),null);assert.equal(resourceLevel(["all"]),null);assert.equal(resourceScalar(["corporation"]),"");for(const p of ["0","01","1.0"," 1","9007199254740992",["1"]])assert.equal(resourcePage(p),null);assert.equal(resourcePage("100001"),100001);assert.equal(resourcePage(undefined),1);});
test("public DTO rejects private fields but accepts retained legacy attachment sizes",()=>{assert.ok(isMobileResource(resource({attachments:[{id:"file",name:"old.pdf",mimeType:"application/pdf",size:400*1024*1024,previewKind:"pdf"}]})));assert.equal(isMobileResource(resource({storageKey:"private"})),false);assert.equal(isMobileResource(resource({author:{...author,email:"hidden"}})),false);assert.equal(isResourceDetail({resource:resource()},"different"),false);assert.equal(isResourceEditor({resource:resource({canManage:false}),attachmentPolicy:policy},"resource"),false);});
test("list page counts and education scope are exact",()=>{const value={items:[resource()],category:"corporation",level:"all",q:"",page:1,pageSize:3,total:1,totalPages:1};assert.ok(isResourceList(value));assert.equal(isResourceList({...value,total:4}),false);assert.equal(isResourceList({...value,level:"middle"}),false);assert.equal(isResourceList({...value,items:[resource(),resource()],total:2}),false);assert.ok(isResourceList({...value,items:[],total:0}));});
test("mutation proof accepts newer live projection and deleted original target without input inference",()=>{const value={ok:true,message:"확정",replayed:true,operation:"update",outcome:"present",resourceId:"resource",committedUpdatedAt:iso,resource:resource({updatedAt:newer,summary:"다른 직원 최신 본문"}),cleanupPending:true};assert.ok(isResourceMutation(value,{operation:"update",resourceId:"resource"}));assert.ok(isResourceMutation({...value,outcome:"deleted",resource:null},{operation:"update",resourceId:"resource"}));assert.equal(isResourceMutation(value,{operation:"create"}),false);assert.equal(isResourceMutation({...value,resourceId:"foreign"},{operation:"update",resourceId:"resource"}),false);});
test("view unique staff and individual visit counts remain separate",()=>{const times={firstViewedAt:iso,lastViewedAt:newer,visitCount:12};assert.ok(isResourceVisit({ok:true,replayed:true,resourceId:"resource",uniqueViewerCount:1,viewer:times},"resource"));assert.ok(isResourceViewers({resourceId:"resource",uniqueViewerCount:1,items:[{user:author,...times}],page:1,pageSize:20,total:1,totalPages:1},"resource"));assert.equal(isResourceVisit({ok:true,replayed:true,resourceId:"resource",uniqueViewerCount:0,viewer:times},"resource"),false);});
test("uploads require whole SHA and terminal tombstones may erase descriptor",()=>{assert.ok(isResourceUpload(upload()));assert.equal(isResourceUpload(upload({file:{name:"x.pdf",mimeType:"application/pdf",size:1,wholeSha256:null}})),false);assert.ok(isResourceUpload(upload({state:"deleted",file:null})));assert.ok(isResourceUpload(upload({state:"deleting",file:null,cleanupPending:true})));assert.equal(isResourceUpload(upload({state:"ready",file:null})),false);assert.equal(isResourceUpload(upload({state:"consumed",completedAt:iso})),false);});
test("private grants accept only PUT HTTPS without extra credential headers",()=>{const value={upload:upload(),grant:{method:"PUT",url:"https://storage.example/signed?capability=synthetic",headers:{"Content-Type":"application/pdf"},expiresAt:iso}};assert.ok(isResourceGrant(value));assert.equal(isResourceGrant({...value,grant:{...value.grant,headers:{...value.grant.headers,Authorization:"Bearer hidden"}}}),false);assert.equal(isResourceGrant({...value,grant:{...value.grant,url:"https://user:password@storage.example/signed"}}),false);assert.ok(isResourceGrant({upload:upload({state:"ready",completedAt:iso}),grant:null}));});
test("registration defaults and validation follow JS length and education required policy",()=>{assert.ok(isResourceOptions({defaults:{category:"bajaul",educationLevel:null},attachmentPolicy:policy}));assert.deepEqual(resourceFieldErrors({title:"  제목  ",summary:" 다섯 글자 내용 ",category:"education",educationLevel:null}),{educationLevel:"교육 대상을 선택하세요."});assert.equal(validateResourceFile("../자료.pdf",300*1024*1024,{maxFileCount:1,maxFileSizeMb:300,allowedExtensions:[".pdf"]}),"자료.pdf");assert.throws(()=>validateResourceFile("a.exe",1,policy),{status:415});assert.throws(()=>validateResourceFile("a.pdf",0,policy),{status:413});});
test("all ambiguous success/timeout/error outcomes retain original keys",()=>{for(const status of [0,200,201,202,204,408,409,500,503])assert.ok(resourceUnknown(new ApiError("합성",status)));for(const status of [400,401,403,404,413,415])assert.equal(resourceUnknown(new ApiError("합성",status)),false);const keys=new Set(Array.from({length:100},newResourceRequestId));assert.equal(keys.size,100);assert.ok([...keys].every(key=>/^[a-f0-9-]{36}$/.test(key)));});

test("legacy cached unique-viewer counter is independent of current viewer row total", () => {
  const viewer = { user: author, firstViewedAt: iso, lastViewedAt: newer, visitCount: 2 };
  assert.ok(isResourceViewers({ resourceId: "resource", uniqueViewerCount: 5, items: [viewer], page: 1, pageSize: 20, total: 1, totalPages: 1 }, "resource"));
});
