import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, beforeEach, after, test } from "node:test";
import ts from "typescript";
// Only DB/session/file-consume ports are synthetic. The actual DAL/parser/adapter/route source runs.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row=Record<string,any>;
const now=new Date("2026-10-04T03:00:00Z"), actor={id:"actor",name:"직원",role:"USER",status:"ACTIVE",canViewYouthDetails:false,canViewYouthContacts:false,canDownloadYouthDocuments:false,canManageYouth:true};
const tables=["user","youth","youthFamilyContact","youthDischargeExtension","youthDecisionDocument","mathSettlement","youthMutationReceipt","youthViewRequest","auditLog"];
const h:Row={state:{},reads:[],writes:[],sql:[],next:0,session:null,auditFailure:false,txErrors:[],now};
const equal=(a:unknown,b:unknown)=>a instanceof Date&&b instanceof Date?a.getTime()===b.getTime():a===b;
function match(row:Row,where:Row={}):boolean{return Object.entries(where).every(([key,value])=>{if(key==="AND")return(Array.isArray(value)?value:[value]).every((part:Row)=>match(row,part));if(key==="OR")return value.some((part:Row)=>match(row,part));if(key.includes("_")&&!(key in row))return match(row,value);const current=row[key];if(value===null||value instanceof Date||typeof value!=="object")return equal(current,value);if("not"in value&&equal(current,value.not))return false;if("in"in value&&!value.in.some((v:unknown)=>equal(current,v)))return false;if("lte"in value&&!(current!=null&&current<=value.lte))return false;if("gte"in value&&!(current!=null&&current>=value.gte))return false;if("lt"in value&&!(current!=null&&current<value.lt))return false;if("contains"in value&&!String(current).toLowerCase().includes(String(value.contains).toLowerCase()))return false;if("some"in value)return(current??[]).some((v:Row)=>match(v,value.some));if("name"in value)return match(current,value);return true;});}
function related(model:string,row:Row):Row { if(model==='youth')return {...row,familyContacts:h.state.youthFamilyContact.filter((r:Row)=>r.youthId===row.id),dischargeExtensions:h.state.youthDischargeExtension.filter((r:Row)=>r.youthId===row.id).map((r:Row)=>related('youthDischargeExtension',r)),decisionDocuments:h.state.youthDecisionDocument.filter((r:Row)=>r.youthId===row.id),mathSettlement:h.state.mathSettlement.find((r:Row)=>r.studentId===row.id)??null}; if(model==='youthDischargeExtension')return {...row,processedBy:h.state.user.find((r:Row)=>r.id===row.processedById)}; if(model==='auditLog')return {...row,actor:h.state.user.find((r:Row)=>r.id===row.actorId)}; return row; }
function project(row:Row,args:Row={}):Row{const result:Row=args.select?{}:structuredClone(row);for(const[key,value]of Object.entries(args.select??args.include??{})){if(value===false)continue;else if(value===true)result[key]=structuredClone(row[key]);else if(Array.isArray(row[key]))result[key]=many(row[key],value as Row);else result[key]=row[key]==null?row[key]:project(row[key],value as Row);}return result;}
function many(rows:Row[],args:Row={}):Row[]{const order=Array.isArray(args.orderBy)?args.orderBy:[args.orderBy??{}];return rows.filter(row=>match(row,args.where)).sort((a,b)=>{for(const o of order)for(const[k,d]of Object.entries(o)){const n=a[k]<b[k]?-1:a[k]>b[k]?1:0;if(n)return d==="desc"?-n:n;}return 0;}).slice(args.skip??0,args.take===undefined?undefined:(args.skip??0)+args.take).map(row=>project(row,args));}
function change(row:Row,data:Row){for(const[key,value]of Object.entries(data))row[key]=value&&typeof value==="object"&&"increment"in value?row[key]+value.increment:structuredClone(value);}
const db:Row={mobileSession:{async findUnique(){return h.session;}},async $queryRaw(sql:Row){h.sql.push(sql);const projected=sql.strings.join('?').split(/\bFROM\b/i)[0];if(/\bpg_advisory_xact_lock\s*\(/i.test(projected))throw Object.assign(Error('unsupported void'),{name:'PrismaClientKnownRequestError',code:'P2010'});return [];},async $transaction(callback:(tx:Row)=>Promise<unknown>){h.beforeTx?.();if(h.txErrors.length)throw h.txErrors.shift();const old=structuredClone(h.state),written=h.writes.length;try{return await callback(db);}catch(error){h.state=old;h.writes.length=written;throw error;}}};
for(const model of tables)db[model]={async findMany(args:Row={}){h.reads.push({model,...args});return many(h.state[model].map((r:Row)=>related(model,r)),args);},async findUnique(args:Row){return(await this.findMany(args))[0]??null;},async findFirst(args:Row){return this.findUnique(args);},async findUniqueOrThrow(args:Row){const row=await this.findUnique(args);if(!row)throw Error('synthetic missing');return row;},async count(args:Row={}){return(await this.findMany(args)).length;},async create({data,...args}:Row){if(model==='auditLog'&&h.auditFailure)throw Error('PRIVATE_AUDIT');const row={id:`${model}-${++h.next}`,createdAt:h.now,updatedAt:h.now,sourceUpdatedAt:null,auditLogId:null,auditedAt:null,disclosureUntil:null,documentId:null,state:'committed',payloadHash:null,committedUpdatedAt:null,committedTargetsJson:null,scrubbedAt:null,...(model==='youth'?{birthDate:null,age:null,phone:null,familyContact:null,familyPhone:null,familyRelationship:null,initialDischargeDate:null,actualDischargeDate:null,purgeStartedAt:null,purgedAt:null}:{}),...structuredClone(data)};h.state[model].push(row);h.writes.push({model,action:'create',data});return project(related(model,row),args);},async createMany({data}:Row){for(const row of data)await this.create({data:row});return{count:data.length};},async update({where,data,...args}:Row){const row=h.state[model].find((r:Row)=>match(r,where));if(!row)throw Error('missing');change(row,data);h.writes.push({model,action:'update',data});return project(related(model,row),args);},async updateMany({where,data}:Row){const rows=h.state[model].filter((r:Row)=>match(r,where));for(const row of rows)change(row,data);h.writes.push({model,action:'updateMany',data});return{count:rows.length};},async deleteMany({where}:Row){const old=h.state[model].length;h.state[model]=h.state[model].filter((r:Row)=>!match(r,where));h.writes.push({model,action:'deleteMany'});return{count:old-h.state[model].length};}};
const key='__actualMobileYouthServer';(globalThis as Row)[key]={h,db};
const url=(source:string)=>`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`;
const mocks=url(`const {h,db}=globalThis.${key};export const prisma=db;export function getAuditLogRequestData(){return {ipAddress:'PRIVATE_IP'};}export async function consumeYouthDecisionUploads(tx,actorId,youthId,receiptId,ids,at,options){if(tx!==db)throw Error('escaped injected transaction');if(h.consumeFailure)throw Error('PRIVATE_STORAGE');h.writes.push({model:'consume',actorId,youthId,receiptId,ids,at,options});return [];}`);
function compile(file:string,aliases:Record<string,string>={}){let source=readFileSync(new URL('../src/'+file,import.meta.url),'utf8');for(const[a,b]of Object.entries(aliases))source=source.replaceAll(JSON.stringify(a),JSON.stringify(b));return url(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);}
const base={'@/lib/prisma':mocks,'@/lib/audit-log-request':mocks,'@/lib/youth-decision-uploads':mocks};
const contextURL=compile('lib/youth-mobile-context.ts',base), queryURL=compile('lib/youth-mobile-queries.ts',{...base,'@/lib/youth-mobile-context':contextURL}), mutationURL=compile('lib/youth-mobile-mutations.ts',{...base,'@/lib/youth-mobile-context':contextURL,'@/lib/youth-mobile-queries':queryURL}), authURL=compile('lib/mobile-auth.ts',base), apiURL=compile('lib/mobile-youth.ts',{...base,'@/lib/mobile-auth':authURL,'@/lib/youth-mobile-context':contextURL,'@/lib/youth-mobile-queries':queryURL,'@/lib/youth-mobile-mutations':mutationURL});
const context=await import(contextURL),queries=await import(queryURL),mutations=await import(mutationURL),api=await import(apiURL),core=await import('../src/lib/mobile-youth-core.ts');
const listRoute=await import(compile('app/api/mobile/youth/route.ts',{'@/lib/mobile-youth':apiURL}));
const ctx=()=>({actorId:actor.id,db,now:()=>new Date(h.now)});
const input=(extra:Row={})=>({requestId:'create-key-one',name:'가상 학생',admissionDate:'2026-01-01',dischargeDate:'9999-12-31',uploadIds:[],...extra});
function youth(extra:Row={}){const row={id:'youth',name:'가상 학생',admissionDate:'2026-01-01',dischargeDate:'9999-12-31',initialDischargeDate:'9999-01-01',birthDate:'2009-01-01',phone:'010-1234-5678',familyPhone:'010-2222-3333',familyContact:'PRIVATE_LEGACY',familyRelationship:'보호자',age:16,actualDischargeDate:null,purgeStartedAt:null,purgedAt:null,updatedAt:now,createdAt:now,...extra};h.state.youth.push(row);return row;}
describe('actual mobile youth server',()=>{
beforeEach(()=>{h.state=Object.fromEntries(tables.map(model=>[model,[]]));h.state.user=[structuredClone(actor)];Object.assign(h,{reads:[],writes:[],sql:[],next:0,auditFailure:false,consumeFailure:false,txErrors:[],beforeTx:null,now:new Date(now)});h.session={userId:actor.id,user:{...actor,position:{name:'시설장'}},expiresAt:new Date(Date.now()+60000)};});
after(()=>delete(globalThis as Row)[key]);
test('unauthenticated all method families reject before params/query/body and no reads',async()=>{h.session=null;for(const action of ['list','detail','create','patch','extension','details','contacts','view-status','mutation-status','history']){let accessed=false;const response=await api.mobileYouthResponse(new Request('https://fixture.invalid?unknown=1',{method:'POST',body:'invalid'}),action,()=>{accessed=true;throw Error('must not access');});assert.equal(response.status,401);assert.equal(accessed,false);assert.equal(response.headers.get('cache-control'),'private, no-store');assert.equal(response.headers.get('x-content-type-options'),'nosniff');assert.equal(response.headers.get('location'),null);assert.doesNotMatch(await response.text(),/PRIVATE|storageKey/);}assert.deepEqual(h.reads,[]);});
test('all16 flags basic safe projection plus current scope before q/count',async()=>{for(let mask=0;mask<16;mask++){Object.assign(h.state.user[0],{canViewYouthDetails:Boolean(mask&1),canViewYouthContacts:Boolean(mask&2),canDownloadYouthDocuments:Boolean(mask&4),canManageYouth:Boolean(mask&8)});h.state.youth=[];youth();youth({id:'old',name:'PRIVATE_RETAINED',dischargeDate:'2026-10-03'});const result=await queries.getMobileYouthList(ctx(),{q:'',page:99});assert.equal(result.total,1);assert.equal(result.page,1);assert.deepEqual(Object.keys(result.items[0]).sort(),['admissionDate','dischargeDate','id','name','updatedAt']);assert.doesNotMatch(JSON.stringify(result),/birthDate|"age":|family|phone|initial|PRIVATE|decision/);assert.equal(result.permissions.canDeleteYouth,false);}assert.deepEqual(h.writes,[]);});
test('fresh actor ACTIVE actual ADMIN override but head has no extra flags',async()=>{youth();await assert.rejects(queries.viewMobileYouth(ctx(),'youth','details','view-key-one'),{code:'FORBIDDEN'});h.state.user[0].role='ADMIN';const view=await queries.viewMobileYouth(ctx(),'youth','details','view-key-one');assert.equal(view.details.birthDate,'2009-01-01');h.state.user[0].status='INACTIVE';await assert.rejects(queries.getMobileYouthDetail(ctx(),'youth'),{code:'UNAUTHORIZED'});});
test('today inclusion yesterday/actual discharge/purge exclude independent old date',async()=>{for(const extra of[{dischargeDate:'2026-10-03'},{actualDischargeDate:'2026-10-04'},{purgeStartedAt:now},{purgedAt:now}]){h.state.youth=[];youth(extra);await assert.rejects(queries.getMobileYouthDetail(ctx(),'youth'),{code:'NOT_FOUND'});}h.state.youth=[];youth({dischargeDate:'2026-10-04'});assert.equal((await queries.getMobileYouthDetail(ctx(),'youth')).youth.id,'youth');});
test('stable detail receipt5min is independent of collapsed30min audit and never extended',async()=>{youth();h.state.user[0].canViewYouthDetails=true;const prior=new Date(now.getTime()-1200000);h.state.auditLog.push({id:'old-audit',actorId:actor.id,action:'VIEW_YOUTH_DETAIL',targetType:'Youth',targetId:'youth',createdAt:prior});const first=await queries.viewMobileYouth(ctx(),'youth','details','details-key');assert.equal(first.auditedAt,prior.toISOString());assert.equal(first.disclosureUntil,new Date(now.getTime()+300000).toISOString());assert.equal(h.state.auditLog.length,1);h.now=new Date(now.getTime()+299999);const replay=await queries.viewMobileYouth(ctx(),'youth','details','details-key');assert.equal(replay.replayed,true);assert.equal(replay.disclosureUntil,first.disclosureUntil);h.now=new Date(now.getTime()+300000);await assert.rejects(queries.viewMobileYouth(ctx(),'youth','details','details-key'),{code:'VIEW_REQUEST_EXPIRED'});const status=await queries.getMobileYouthViewStatus(ctx(),'details-key');assert.equal(status.state,'expired');assert.doesNotMatch(JSON.stringify(status),/birthDate|initial|reason/);});
test('contacts same key once newlogical newaudit legacy normalization no raw fields',async()=>{youth();h.state.user[0].canViewYouthContacts=true;const first=await queries.viewMobileYouth(ctx(),'youth','contacts','contacts-key-A');await queries.viewMobileYouth(ctx(),'youth','contacts','contacts-key-A');await queries.viewMobileYouth(ctx(),'youth','contacts','contacts-key-B');assert.equal(h.state.auditLog.length,2);assert.deepEqual(first.contacts.familyContacts,[{id:'legacy-family-youth',relationship:'보호자',phone:'010-2222-3333'}]);assert.equal(h.state.youthViewRequest.length,2);assert.doesNotMatch(JSON.stringify(h.state.youthViewRequest),/010-|2009-|PRIVATE/);});
test('view source change oldkey409 no new audit and revoked permission no payload',async()=>{youth();h.state.user[0].canViewYouthContacts=true;await queries.viewMobileYouth(ctx(),'youth','contacts','contacts-key');h.state.youth[0].updatedAt=new Date(now.getTime()+1);await assert.rejects(queries.viewMobileYouth(ctx(),'youth','contacts','contacts-key'),{code:'VIEW_SNAPSHOT_CHANGED'});await assert.rejects(queries.getMobileYouthViewStatus(ctx(),'contacts-key'),{code:'VIEW_SNAPSHOT_CHANGED'});assert.equal(h.state.auditLog.length,1);h.state.user[0].canViewYouthContacts=false;await assert.rejects(queries.viewMobileYouth(ctx(),'youth','contacts','new-contact-key'),{code:'FORBIDDEN'});});
test('audit failure produces no sensitive body and rolls back ledger',async()=>{youth();h.state.user[0].canViewYouthDetails=true;h.auditFailure=true;await assert.rejects(queries.viewMobileYouth(ctx(),'youth','details','failed-view'),{code:'AUDIT_UNAVAILABLE'});assert.equal(h.state.youthViewRequest.length,0);assert.equal(h.state.auditLog.length,0);});
test('create writeonly manager fields idempotent safe result receipt no PII and changedpayload409',async()=>{const value=input({birthDate:'2009-01-01',phone:'010-1234-5678',familyContacts:[{relationship:'보호자',phone:'010-2222-3333'}]});const first=await mutations.createMobileYouth(ctx(),value), replay=await mutations.createMobileYouth(ctx(),value);assert.equal(first.targetId,replay.targetId);assert.equal(replay.replayed,true);assert.equal(h.state.youth.length,1);assert.equal(h.state.auditLog.length,1);assert.doesNotMatch(JSON.stringify(first),/010-|2009-|birth|family/);assert.doesNotMatch(JSON.stringify(h.state.youthMutationReceipt),/010-|2009-|보호자/);await assert.rejects(mutations.createMobileYouth(ctx(),{...value,name:'다른 이름'}),{code:'REQUEST_CONFLICT'});});
test('create past scheduled discharge gives owner minimal immutable proof and no recreate',async()=>{const value=input({dischargeDate:'2026-10-03'});const first=await mutations.createMobileYouth(ctx(),value), replay=await mutations.createMobileYouth(ctx(),value), status=await mutations.getYouthMutationStatus(ctx(),value.requestId);for(const response of[first,replay,status]){assert.equal(response.outcome,'unavailable');assert.equal(response.result,null);assert.equal(response.committedUpdatedAt,null);assert.doesNotMatch(JSON.stringify(response),/가상|2026-01|dischargeDate/);}await assert.rejects(queries.getMobileYouthDetail(ctx(),first.targetId),{code:'NOT_FOUND'});assert.equal(h.state.youth.length,1);});
test('masked patch omission preserves DOB contacts legacy initial and stale identical is409',async()=>{const row=youth(), value={requestId:'patch-key-one',expectedUpdatedAt:row.updatedAt.toISOString(),patch:{name:'새 이름'}};const first=await mutations.patchMobileYouth(ctx(),'youth',value);assert.equal(h.state.youth[0].birthDate,'2009-01-01');assert.equal(h.state.youth[0].phone,'010-1234-5678');assert.equal(h.state.youth[0].initialDischargeDate,'9999-01-01');assert.equal(first.committedUpdatedAt,new Date(now.getTime()+1).toISOString());await assert.rejects(mutations.patchMobileYouth(ctx(),'youth',{...value,requestId:'patch-stale-key'}),{code:'YOUTH_CONFLICT'});await assert.rejects(mutations.patchMobileYouth(ctx(),'youth',{requestId:'private-patch',expectedUpdatedAt:first.committedUpdatedAt,patch:{birthDate:null}}),{code:'FORBIDDEN'});});
test('permitted explicit null clears contacts/birth and audit+receipt rollback on error',async()=>{const row=youth(),baseline=row.updatedAt.toISOString();Object.assign(h.state.user[0],{canViewYouthDetails:true,canViewYouthContacts:true});h.auditFailure=true;await assert.rejects(mutations.patchMobileYouth(ctx(),'youth',{requestId:'rollback-patch',expectedUpdatedAt:baseline,patch:{birthDate:null,phone:null,familyContacts:[]}}));assert.equal(h.state.youth[0].birthDate,'2009-01-01');assert.equal(h.state.youthMutationReceipt.length,0);h.auditFailure=false;await mutations.patchMobileYouth(ctx(),'youth',{requestId:'clear-patch',expectedUpdatedAt:baseline,patch:{birthDate:null,phone:null,familyContacts:[]}});assert.equal(h.state.youth[0].birthDate,null);assert.equal(h.state.youth[0].familyPhone,null);});
test('retired/purging scope stops mutation before writes and persisted proof cannot revive',async()=>{const row=youth();await mutations.patchMobileYouth(ctx(),'youth',{requestId:'prior-patch',expectedUpdatedAt:row.updatedAt.toISOString(),patch:{name:'changed'}});h.state.youth[0].purgeStartedAt=now;const writes=h.writes.length;await assert.rejects(mutations.patchMobileYouth(ctx(),'youth',{requestId:'prior-patch',expectedUpdatedAt:row.updatedAt.toISOString(),patch:{name:'changed'}}),{code:'NOT_FOUND'});assert.equal(h.writes.length,writes);await assert.rejects(mutations.getYouthMutationStatus(ctx(),'prior-patch'),{code:'NOT_FOUND'});});
test('extension version monotonic/max2/settlement/reason policy and manager result basiconly',async()=>{const row=youth({dischargeDate:'2026-11-01',initialDischargeDate:'2026-11-01'});const one=await mutations.extendMobileYouth(ctx(),'youth',{requestId:'extend-one',expectedUpdatedAt:row.updatedAt.toISOString(),extendedDischargeDate:'2026-12-01',reason:'제출 사유'});assert.doesNotMatch(JSON.stringify(one),/제출|initial|extension/);const two=await mutations.extendMobileYouth(ctx(),'youth',{requestId:'extend-two',expectedUpdatedAt:one.committedUpdatedAt,extendedDischargeDate:'2027-01-01',reason:'둘째'});await assert.rejects(mutations.extendMobileYouth(ctx(),'youth',{requestId:'extend-three',expectedUpdatedAt:two.committedUpdatedAt,extendedDischargeDate:'2027-02-01',reason:'셋째'}),{code:'VALIDATION_ERROR'});assert.equal(h.state.youthDischargeExtension.length,2);});
test('own status foreign404 fresh401 or manage403 no writes',async()=>{await mutations.createMobileYouth(ctx(),input());h.writes=[];assert.doesNotMatch(JSON.stringify(await mutations.getYouthMutationStatus(ctx(),'create-key-one')),/payloadHash|IP|PRIVATE/);await assert.rejects(mutations.getYouthMutationStatus(ctx(),'unknown-key'),{code:'NOT_FOUND'});h.state.user[0].canManageYouth=false;await assert.rejects(mutations.getYouthMutationStatus(ctx(),'create-key-one'),{code:'FORBIDDEN'});h.state.user[0].status='INACTIVE';await assert.rejects(mutations.getYouthMutationStatus(ctx(),'create-key-one'),{code:'UNAUTHORIZED'});assert.deepEqual(h.writes,[]);});
test('history sensitive allowlist filters raw message metadata/IP/avatar and flags independently',async()=>{youth();h.state.auditLog.push({id:'log',actorId:actor.id,action:'UPDATE_YOUTH',targetType:'Youth',targetId:'youth',createdAt:now,message:'PRIVATE_MESSAGE',metadata:{changes:[{field:'name',label:'PRIVATE_LABEL',from:'이전',to:'이름'},{field:'birthDate',from:'2009-01-01',to:'2009-02-01'},{field:'phone',from:'010-1111-2222',to:'010-2222-3333'},{field:'storageKey',from:'PRIVATE_KEY',to:'x'}],IP:'PRIVATE_IP'}});const basic=await queries.getMobileYouthHistory(ctx(),'youth',1);assert.equal(basic.items[0].changes.length,1);assert.doesNotMatch(JSON.stringify(basic),/PRIVATE|010-|2009-|profile|email|message|metadata/);h.state.user[0].canViewYouthContacts=true;assert.equal((await queries.getMobileYouthHistory(ctx(),'youth',1)).items[0].changes.length,2);});
test('closed document history summaries require current file permission and never expose names or raw metadata',async()=>{youth();for(const changeType of['youth.documents.add','youth.documents.delete','youth.documents.reencrypt','youth.documents.future'])h.state.auditLog.push({id:changeType,actorId:actor.id,action:'UPDATE_YOUTH',targetType:'Youth',targetId:'youth',createdAt:now,metadata:{changeType,decisionDocumentCount:2,deletedDocumentNames:['PRIVATE_NAME.pdf'],storageKey:'PRIVATE_KEY',reason:'PRIVATE_REASON'}});let history=await queries.getMobileYouthHistory(ctx(),'youth',1);assert.ok(history.items.every((row:Row)=>row.changes.length===0));h.state.user[0].canDownloadYouthDocuments=true;history=await queries.getMobileYouthHistory(ctx(),'youth',1);const summaries=history.items.flatMap((row:Row)=>row.changes);assert.equal(summaries.length,3);assert.deepEqual(summaries.map((row:Row)=>row.label).sort(),['결정문 삭제','결정문 재암호화','결정문 첨부'].sort());assert.ok(summaries.every((row:Row)=>row.field==='decisionDocuments'&&row.to.startsWith('2개')));assert.doesNotMatch(JSON.stringify(history),/PRIVATE|deletedDocumentNames|changeType|storageKey|reason|metadata/);h.state.user[0].canDownloadYouthDocuments=false;assert.ok((await queries.getMobileYouthHistory(ctx(),'youth',1)).items.every((row:Row)=>row.changes.length===0));});
test('strict canonical dates, unknown keys, duplicate decoded JSON, unicode and caps',async()=>{for(const date of['0001-01-01','0099-12-31','0100-02-28','9999-12-31'])assert.equal(core.isMobileYouthDate(date),true);for(const date of['0000-01-01','2026-02-29','2026-1-01'])assert.equal(core.isMobileYouthDate(date),false);assert.throws(()=>core.parseYouthPatch({requestId:'valid-key',expectedUpdatedAt:now.toISOString(),patch:{dischargeDate:'9999-12-31'}}));for(const body of['{"x":1,"\\u0078":2}','{bad}'])await assert.rejects(core.readYouthJson(new Request('https://fixture.invalid',{method:'POST',headers:{'content-type':'application/json'},body})));await assert.rejects(core.readYouthJson(new Request('https://fixture.invalid',{method:'POST',headers:{'content-type':'application/json','content-length':'2'},body:'{} '})));await assert.rejects(core.readYouthJson(new Request('https://fixture.invalid',{method:'POST',headers:{'content-type':'application/json'},body:' '.repeat(65537)})),{code:'PAYLOAD_TOO_LARGE'});});
test('exact retry boundaries known adapter conflict retries3; arbitrary errors once',async()=>{const error=Object.assign(Error('driver'),{name:'DriverAdapterError',cause:{kind:'TransactionWriteConflict'}});h.txErrors=[error,error];await mutations.createMobileYouth(ctx(),input());assert.equal(h.state.youth.length,1);for(const unknown of[Object.assign(Error(),{code:'P2034'}),Object.assign(Error(),{name:'DriverAdapterError',cause:{kind:'PostgresError',code:'23514'}})])assert.equal(context.youthTransactionConflict(unknown),false);});
test('same-key name unique race resolves only matching committed own proof after rollback',async()=>{const first=await mutations.createMobileYouth(ctx(),input());const error=Object.assign(Error('unique'),{name:'PrismaClientKnownRequestError',code:'P2002',meta:{modelName:'Youth',target:['name']}});h.txErrors=[error];const replay=await mutations.createMobileYouth(ctx(),input());assert.equal(replay.replayed,true);assert.equal(replay.targetId,first.targetId);assert.equal(h.state.youth.length,1);assert.equal(h.state.auditLog.length,1);h.txErrors=[error];await assert.rejects(mutations.createMobileYouth(ctx(),input({requestId:'another-owner-key'})),{code:'VALIDATION_ERROR'});h.txErrors=[Object.assign(Error('other'),{name:'PrismaClientKnownRequestError',code:'P2002',meta:{modelName:'User',target:['name']}})];await assert.rejects(mutations.createMobileYouth(ctx(),input()),{code:'P2002'});});
test('web-only document projection contains exact updated token and keeps contacts masked',async()=>{youth();Object.assign(h.state.user[0],{canDownloadYouthDocuments:true,canViewYouthContacts:true});h.state.youthDecisionDocument.push({id:'doc',youthId:'youth',originalName:'가상.pdf',size:4,createdAt:now,updatedAt:new Date(now.getTime()+1),storageKey:'PRIVATE_KEY'});const value=await queries.getWebYouthProfile(ctx(),'youth');assert.equal(value.decisionDocuments[0].updatedAt,new Date(now.getTime()+1).toISOString());assert.equal(value.phone,null);assert.deepEqual(value.familyContacts,[]);assert.doesNotMatch(JSON.stringify(value),/PRIVATE|storageKey/);});
test('actual thin route executes shared auth boundary and strict query',async()=>{h.session=null;const response=await listRoute.POST(new Request('https://fixture.invalid/api/mobile/youth?bad=1',{method:'POST',body:'not json'}));assert.equal(response.status,401);h.session={userId:actor.id,user:actor,expiresAt:new Date(Date.now()+60000)};const query=await listRoute.GET(new Request('https://fixture.invalid/api/mobile/youth?page=01',{headers:{authorization:'Bearer '+'t'.repeat(43)}}));assert.equal(query.status,400);});
});
