import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { test } from "node:test";
const ciUrl="postgresql://postgres:postgres@127.0.0.1:5432/e_approval_test";
function disposable(){if(process.env.GITHUB_ACTIONS!=="true"||process.env.DATABASE_URL!==ciUrl||process.env.DIRECT_URL!==ciUrl)throw Error("Resource PG tests require the exact disposable CI database.");}
async function setup(){disposable();const[{PrismaClient},{PrismaPg},domain,queries,uploads,cleanup]=await Promise.all([import("../src/generated/prisma/client.ts"),import("@prisma/adapter-pg"),import("../src/lib/resource-library-mutations.ts"),import("../src/lib/resource-library-queries.ts"),import("../src/lib/resource-uploads.ts"),import("../src/lib/resource-file-cleanup.ts")]);const db=new PrismaClient({adapter:new PrismaPg({connectionString:ciUrl,max:4})}),prefix="ci-resource-"+randomUUID();await db.department.create({data:{id:prefix+"-dept",name:"자료실 합성 검증",code:prefix}});await db.position.create({data:{id:prefix+"-position",name:"자료실 검증",level:1}});const actor=await db.user.create({data:{id:prefix+"-actor",name:"합성 직원",departmentId:prefix+"-dept",positionId:prefix+"-position"}});let deleteFails=false;const storage={async deleteResourceStoredFile(){if(deleteFails)throw Error("synthetic storage failure");},async resourceStoredFileExists(){return false;}};return{db,prefix,actor,domain,queries,uploads,cleanup,storage,setDeleteFails:(yes:boolean)=>{deleteFails=yes;},async dispose(){const receipts=await db.resourceMutationReceipt.findMany({where:{actorId:actor.id}});const ids=receipts.map(row=>row.targetResourceId);await db.resourcePost.deleteMany({where:{OR:[{authorId:actor.id},{id:{in:ids}}]}});await db.resourceFileCleanup.deleteMany({where:{OR:[{sourceMutationId:{in:receipts.map(row=>row.id)}},{storageKey:{startsWith:prefix}}]}});await db.resourceUpload.deleteMany({where:{actorId:actor.id}});await db.resourceMutationReceipt.deleteMany({where:{actorId:actor.id}});await db.auditLog.deleteMany({where:{actorId:actor.id}});await db.user.delete({where:{id:actor.id}});await db.position.delete({where:{id:prefix+"-position"}});await db.department.delete({where:{id:prefix+"-dept"}});await db.$disconnect();}};}
const values=(requestId:string)=>({requestId,title:"실제 도메인 자료",summary:"합성 내용만 기록합니다.",category:"bajaul"as const,educationLevel:null,uploadIds:[]as string[]});
test("CI PostgreSQL actual resource domain content CAS, visits, indefinite receipts, atomic rollback and postcommit cleanup",{skip:process.env.GITHUB_ACTIONS!=="true",timeout:60000},async()=>{
 const s=await setup();try{
  const now=new Date("2026-10-03T03:00:00Z"),ctx={actorId:s.actor.id,db:s.db,now:()=>now,storage:s.storage}as unknown as Parameters<typeof s.domain.mutateResource>[0];
  const created=await s.domain.mutateResource(ctx,{operation:"create",data:values("pg-create")});assert.equal(created.replayed,false);assert.ok(created.resource);const id=created.resourceId,baseline=created.resource.updatedAt;
  await s.domain.recordResourceView(ctx,{resourceId:id,requestId:"pg-visit-A"});await s.domain.recordResourceView(ctx,{resourceId:id,requestId:"pg-visit-B"});const late=await s.domain.recordResourceView(ctx,{resourceId:id,requestId:"pg-visit-A"});assert.equal(late.viewer.visitCount,2);assert.equal(late.replayed,true);assert.equal((await s.db.resourcePost.findUniqueOrThrow({where:{id}})).updatedAt.toISOString(),baseline);
  const updated=await s.domain.mutateResource(ctx,{operation:"update",resourceId:id,data:{...values("pg-update"),expectedUpdatedAt:baseline,removeAttachmentIds:[]}});assert.equal(updated.resource!.updatedAt,new Date(now.getTime()+1).toISOString());
  await assert.rejects(s.domain.mutateResource(ctx,{operation:"update",resourceId:id,data:{...values("pg-stale-update"),expectedUpdatedAt:baseline,removeAttachmentIds:[]}}),{code:"RESOURCE_CONFLICT"});assert.equal(await s.db.resourceMutationReceipt.count({where:{actorId:s.actor.id}}),2);
  const ready=await s.db.resourceUpload.create({data:{actorId:s.actor.id,startRequestId:"pg-upload",startPayloadHash:"a".repeat(64),storageProvider:"local",stagingKey:s.prefix+"-staging",finalKey:s.prefix+"-final",state:"ready",originalName:"증명.pdf",mimeType:"application/pdf",size:3,expectedSha256:"a".repeat(64),plaintextSha256:"a".repeat(64),storedSha256:"b".repeat(64),storedSize:35,expiresAt:new Date(now.getTime()+100000),completedAt:now,finalizeWriteEvidence:"confirmed",hadUnknownWrite:true}});
  // A real audit foreign-key failure must roll back post, consume and receipt in the same tx.
  const failDb={$transaction:(operation:(tx:unknown)=>Promise<unknown>,options:object)=>s.db.$transaction(tx=>operation(new Proxy(tx,{get(target,key){if(key==="auditLog")return new Proxy(target.auditLog,{get(delegate,name){if(name==="create")return(args:Parameters<typeof delegate.create>[0])=>delegate.create({...args,data:{...args.data,actorId:s.prefix+"-missing-actor"}as unknown as typeof args.data});const v=Reflect.get(delegate,name);return typeof v==="function"?v.bind(delegate):v;}});const v=Reflect.get(target,key);return typeof v==="function"?v.bind(target):v;}})),options)}as unknown as NonNullable<typeof ctx.db>;
  await assert.rejects(s.domain.mutateResource({...ctx,db:failDb},{operation:"create",data:{...values("pg-audit-rollback"),uploadIds:[ready.id]}}));assert.equal((await s.db.resourceUpload.findUniqueOrThrow({where:{id:ready.id}})).state,"ready");assert.equal(await s.db.resourceMutationReceipt.count({where:{actorId:s.actor.id,requestId:"pg-audit-rollback"}}),0);assert.equal(await s.db.resourceAttachment.count({where:{storageKey:ready.finalKey!}}),0);
  const consumed=await s.domain.mutateResource(ctx,{operation:"create",data:{...values("pg-consume"),uploadIds:[ready.id]}});assert.equal(consumed.resource!.attachments.length,1);
  // Sticky unknown evidence predates ready/consume. A known staging deletion may
  // legitimately be done before a later synthetic flag change, so seed the actual
  // protocol state and prove that consume keeps its uncertain key and queue live.
  const consumedUpload=await s.db.resourceUpload.findUniqueOrThrow({where:{id:ready.id}});assert.equal(consumedUpload.hadUnknownWrite,true);assert.equal(consumedUpload.stagingKey,ready.stagingKey);
  const consumedStaging=await s.db.resourceFileCleanup.findUniqueOrThrow({where:{storageProvider_storageKey:{storageProvider:"local",storageKey:ready.stagingKey!}}});assert.equal(consumedStaging.state,"pending");assert.equal(consumedStaging.lastErrorCode,"WRITE_PENDING");assert.equal(consumedStaging.sourceUploadId,ready.id);
  s.setDeleteFails(true);
  const removed=await s.domain.mutateResource(ctx,{operation:"delete",resourceId:consumed.resourceId,data:{requestId:"pg-delete",expectedUpdatedAt:consumed.resource!.updatedAt}});assert.equal(removed.ok,true);assert.equal(removed.cleanupPending,true);const queued=await s.db.resourceFileCleanup.findUniqueOrThrow({where:{storageProvider_storageKey:{storageProvider:"local",storageKey:ready.finalKey!}}});assert.equal(queued.sourceUploadId,ready.id);assert.equal(queued.state,"pending");assert.equal((await s.domain.mutateResource(ctx,{operation:"create",data:{...values("pg-consume"),uploadIds:[ready.id]}})).outcome,"deleted");assert.equal(await s.db.resourcePost.count({where:{id:consumed.resourceId}}),0);
  s.setDeleteFails(false);await s.db.resourceFileCleanup.updateMany({where:{sourceUploadId:ready.id},data:{nextAttemptAt:now}});const reconciled=await s.cleanup.reconcileResourceFileQueue(ctx);assert.equal(reconciled.checked,2);assert.equal(reconciled.completed,0);const rows=await s.db.resourceFileCleanup.findMany({where:{sourceUploadId:ready.id}});assert.equal(rows.length,2);assert.deepEqual(new Set(rows.map(row=>row.storageKey)),new Set([ready.stagingKey,ready.finalKey]));assert.ok(rows.every(row=>row.state==="pending"&&row.lastErrorCode==="WRITE_PENDING"));assert.equal((await s.db.resourceUpload.findUniqueOrThrow({where:{id:ready.id}})).originalName,null);
  await s.db.user.update({where:{id:s.actor.id},data:{status:"INACTIVE"}});await assert.rejects(s.queries.getResourceDetail(ctx,id),{code:"UNAUTHORIZED"});assert.equal(await s.db.resourceMutationReceipt.count({where:{actorId:s.actor.id}}),4);
 }finally{await s.dispose();}
});
test("CI PostgreSQL real shared actor snapshot + request lock races yield one mutation, one visit and one upload",{skip:process.env.GITHUB_ACTIONS!=="true",timeout:60000},async()=>{
 const s=await setup();try{
  function pairStore(){let entered=0,release:()=>void=()=>{};const ready=new Promise<void>(resolve=>{release=resolve;});return{$transaction:(operation:(tx:unknown)=>Promise<unknown>,options:object)=>s.db.$transaction(async tx=>operation(new Proxy(tx,{get(target,key){if(key==="$queryRaw")return async(...args:Parameters<typeof target.$queryRaw>)=>{const result=await target.$queryRaw(...args);const statement=args[0]as {strings?:string[]};if(statement.strings?.join("").includes('FROM "User"')&&entered<2){entered++;if(entered===2)release();await ready;}return result;};const value=Reflect.get(target,key);return typeof value==="function"?value.bind(target):value;}})),options)};}
  const ctx={actorId:s.actor.id,db:pairStore(),storage:s.storage}as unknown as Parameters<typeof s.domain.mutateResource>[0];const result=await Promise.all([s.domain.mutateResource(ctx,{operation:"create",data:values("pg-parallel-create")}),s.domain.mutateResource(ctx,{operation:"create",data:values("pg-parallel-create")})]);assert.equal(result[0].resourceId,result[1].resourceId);assert.equal(result.filter(row=>row.replayed).length,1);assert.equal(await s.db.auditLog.count({where:{actorId:s.actor.id}}),1);
  const visitDb=pairStore();const visits=await Promise.all([s.domain.recordResourceView({...ctx,db:visitDb as typeof ctx.db},{resourceId:result[0].resourceId,requestId:"pg-parallel-visit"}),s.domain.recordResourceView({...ctx,db:visitDb as typeof ctx.db},{resourceId:result[0].resourceId,requestId:"pg-parallel-visit"})]);assert.ok(visits.every(row=>row.viewer.visitCount===1));
  const db=pairStore(),uploadCtx={...ctx,db:db as typeof ctx.db};const input={requestId:"pg-parallel-upload",targetResourceId:null,name:"test.pdf",mimeType:"application/pdf",size:3,wholeSha256:"a".repeat(64)};
  const uploads=await Promise.all([s.uploads.startResourceUpload(uploadCtx,input,{server:true}),s.uploads.startResourceUpload(uploadCtx,input,{server:true})]);assert.equal(uploads[0].upload.id,uploads[1].upload.id);assert.equal(await s.db.resourceUpload.count({where:{actorId:s.actor.id}}),1);
 }finally{await s.dispose();}
});
