import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { after, beforeEach, test } from "node:test";
import ts from "typescript";
// Execute the current TSX; replace only React/browser/navigation/network boundaries.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row = Record<string, any>;
const filename=new URL("../src/components/resource-form.tsx",import.meta.url),source=readFileSync(filename,"utf8");
export const resourceFormSourceSha256=createHash("sha256").update(source).digest("hex");
const key="__resourceFormFlow",h:Row={current:null,api:{},calls:[],prepare:null};(globalThis as Row)[key]=h;
const dataUrl=(text:string)=>`data:text/javascript;base64,${Buffer.from(text).toString("base64")}`;
const hooks=dataUrl(`const h=globalThis.${key};export function useState(initial){const r=h.current,i=r.index++;if(!(i in r.slots))r.slots[i]=typeof initial==='function'?initial():initial;return [r.slots[i],next=>{r.slots[i]=typeof next==='function'?next(r.slots[i]):next;}];}export function useRef(initial){const r=h.current,i=r.index++;if(!(i in r.slots))r.slots[i]={current:initial};return r.slots[i];}export function useEffect(fn,deps){const r=h.current,i=r.index++,old=r.effects[i];if(!old||deps?.some((v,j)=>v!==old.deps?.[j]))r.scheduled.push(()=>{old?.cleanup?.();r.effects[i]={deps,cleanup:fn()};});}export function useActionState(){return [{},()=>{},false];}export function startTransition(fn){const r=h.current,job=Promise.resolve(fn());r.jobs.push(job);job.catch(()=>{});}export default {};`);
const jsx=dataUrl(`export const Fragment='Fragment';export function jsx(type,props){return {type,props:props??{}};}export const jsxs=jsx;`);
const boundaries=dataUrl(`const h=globalThis.${key};export const Link='a';export default Link;export function useRouter(){return {replace:path=>h.calls.push(['replace',path]),refresh:()=>h.calls.push(['refresh'])};}export const AttachmentFileRow='FileRow';export const PendingOverlay='Overlay';export function useAttachmentThumbnailUrls(){return {};}export function startResourceUploadAction(...args){return h.api.start?.(...args);}export function getResourceUploadStatusAction(...args){return h.api.status?.(...args);}export function grantResourceUploadAction(...args){return h.api.grant?.(...args);}export function completeResourceUploadAction(...args){return h.api.complete?.(...args);}export function getResourceMutationStatusAction(...args){h.calls.push(['status',...args]);return h.api.mutationStatus(...args);}export function getResourceEditorAction(...args){h.calls.push(['editor',...args]);return h.api.editor(...args);}export class ResourceWebUploadError extends Error{constructor(message,code='UNKNOWN',status=0){super(message);this.code=code;this.status=status;}}export async function prepareResourceWebUpload(...args){h.calls.push(['prepare',args[0]]);return h.prepare(...args);}`);
let transformed=source;for(const alias of["react","next/link","next/navigation","@/app/resources/upload-actions","@/lib/resource-web-upload","@/components/attachment-file-row","@/components/form-pending-overlay","@/components/use-attachment-thumbnail-urls"])transformed=transformed.replaceAll(JSON.stringify(alias),JSON.stringify(alias==="react"?hooks:boundaries));
const output=ts.transpileModule(transformed,{fileName:filename.pathname,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText.replaceAll('"react/jsx-runtime"',JSON.stringify(jsx));
const {ResourceForm}=await import(dataUrl(output));
class ElementMock{type="";files:File[]=[];private v="";focus(){h.calls.push(["focus"]);}get value(){return this.v;}set value(value:string){this.v=value;if(this.type==="file"&&value==="")this.files=[];}}
const NativeFormData=globalThis.FormData,oldWindow=(globalThis as Row).window,oldElement=(globalThis as Row).HTMLElement;
class BrowserFormData extends NativeFormData{constructor(form?:Row){super();if(form)for(const node of form.fields){const p=node.props;if(!p.name||p.disabled||p.type==="checkbox"&&!p.checked)continue;if(p.type==="file"){for(const file of p.ref?.current?.files??[])this.append(p.name,file);}else this.append(p.name,String(p.value??""));}}}
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(cause:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return{promise,resolve,reject};}
function walk(node:Row|Row[]|unknown):Row[]{if(Array.isArray(node))return node.flatMap(walk);if(!node||typeof node!=="object"||!("type"in node))return[];return[node as Row,...Object.values((node as Row).props??{}).flatMap(walk)];}
function text(node:unknown):string{if(Array.isArray(node))return node.map(text).join("");if(node&&typeof node==="object"&&"type"in node)return text((node as Row).props.children);return typeof node==="string"||typeof node==="number"?String(node):"";}
class Screen{
 slots:Row[]=[];index=0;effects:Row[]=[];scheduled:Array<()=>void>=[];jobs:Promise<unknown>[]=[];nodes:Row[]=[];tree:Row|null=null;elements=new Map<string,ElementMock>();props:Row;mounted=true;
 constructor(extra:Row={}){this.props={actorId:"actor",initialRequestId:"form-request-key",directUploadSupported:false,mode:"create",attachmentPolicy:{maxFileCount:10,maxFileSizeMb:30,allowedExtensions:[".pdf",".png"]},initialValues:{title:"입력한 제목",summary:"입력한 내용입니다.",category:"bajaul",educationLevel:""},action:async(_state:unknown,form:FormData)=>{h.calls.push(["parent",form]);return{errors:{form:"응답 유실"},attemptDisposition:"unknown"};},...extra};this.render();}
 render(){this.index=0;this.scheduled=[];h.current=this;const expand=(node:Row|unknown):Row|unknown=>{if(Array.isArray(node))return node.map(expand);if(!node||typeof node!=="object"||!("type"in node))return node;if(typeof(node as Row).type==="function")return expand((node as Row).type((node as Row).props));const result={...(node as Row),props:{...(node as Row).props}};for(const[k,v]of Object.entries(result.props))if(k!=="ref")result.props[k]=expand(v);return result;};this.tree=expand(ResourceForm(this.props))as Row;this.nodes=walk(this.tree);for(const node of this.nodes){const p=node.props;if(p.ref){const key=p.name??node.type;let element=this.elements.get(key);if(!element){element=new ElementMock();this.elements.set(key,element);}element.type=p.type??"";if(p.type!=="file")element.value=String(p.value??"");p.ref.current=node.type==="form"?{fields:this.nodes.filter(n=>["input","select","textarea"].includes(n.type)),elements:{namedItem:(name:string)=>this.elements.get(name)}}:element;}}for(const effect of this.scheduled)effect();return this;}
 field(name:string){const row=this.nodes.find(node=>node.props.name===name);assert.ok(row,`missing ${name}`);return row;}
 button(label:string){const row=this.nodes.find(node=>node.type==="button"&&text(node).includes(label));assert.ok(row,`missing ${label}`);return row;}
 change(name:string,value:string){this.field(name).props.onChange({target:{value}});return this.render();}
 select(file:File){const node=this.field("attachments");node.props.ref.current.files=[file];node.props.onChange({currentTarget:{files:[file]}});return this.render();}
 submit(){this.nodes.find(node=>node.type==="form")!.props.onSubmit({preventDefault(){},currentTarget:this.nodes.find(node=>node.type==="form")!.props.ref.current});this.render();}
 async flush(){await Promise.allSettled(this.jobs);if(this.mounted)this.render();await Promise.resolve();}
 unmount(){this.mounted=false;for(const effect of this.effects)effect?.cleanup?.();}
}
beforeEach(()=>{Object.assign(h,{api:{mutationStatus:async()=>({ok:false,status:404,code:"NOT_FOUND",error:"미확인"}),editor:async()=>({ok:true,data:{resource:{id:"resource",title:"서버 제목",summary:"서버 최신 내용",category:"bajaul",educationLevel:null,updatedAt:"2026-10-03T04:00:00.000Z",attachments:[],canManage:true}}})},calls:[],prepare:async()=>"ready-upload"});(globalThis as Row).window={addEventListener(){},removeEventListener(){},confirm:()=>true};(globalThis as Row).HTMLElement=ElementMock;(globalThis as Row).FormData=BrowserFormData;});
after(()=>{(globalThis as Row).FormData=NativeFormData;(globalThis as Row).window=oldWindow;(globalThis as Row).HTMLElement=oldElement;delete(globalThis as Row)[key];});
test("current ResourceForm TSX source fingerprint and synchronous double-submit dispatch one parent",async(t)=>{t.diagnostic(`ResourceForm source SHA256: ${resourceFormSourceSha256}`);assert.match(resourceFormSourceSha256,/^[a-f0-9]{64}$/);assert.match(source,/function handleSubmit/);const gate=deferred<Row>();const screen=new Screen({action:async(_s:unknown,form:FormData)=>{h.calls.push(["parent",form]);return gate.promise;}});screen.submit();screen.submit();assert.equal(h.calls.filter((c:Row)=>c[0]==="parent").length,1);gate.resolve({errors:{form:"응답 유실"},attemptDisposition:"unknown"});await screen.flush();assert.equal(screen.field("title").props.value,"입력한 제목");screen.unmount();});
test("unknown response freezes same payload request/files and retry checks receipt before parent",async()=>{const screen=new Screen(),file=new File(["bytes"],"original.pdf",{type:"application/pdf"});screen.select(file);screen.submit();await screen.flush();const first=h.calls.find((call:Row)=>call[0]==="parent")[1];screen.submit();await screen.flush();const calls=h.calls.filter((c:Row)=>["parent","status"].includes(c[0]));assert.deepEqual(calls.map((c:Row)=>c[0]),["parent","status","parent"]);assert.equal(calls[2][1],first);assert.equal(first.get("requestId"),"form-request-key");assert.equal(first.get("title"),"입력한 제목");assert.equal(first.getAll("attachments")[0].name,file.name);assert.equal(first.get("resourceAttemptWasUnknown"),"true");assert.equal(screen.field("title").props.readOnly,true);screen.unmount();});
test("committed deleted receipt recovery never uploads or dispatches parent again",async()=>{const screen=new Screen({directUploadSupported:true}),file=new File(["bytes"],"original.pdf");screen.select(file);screen.submit();await screen.flush();h.api.mutationStatus=async()=>({ok:true,data:{ok:true,operation:"create",outcome:"deleted",resource:null,resourceId:"deleted-resource",committedUpdatedAt:"2026-10-03T03:00:00.000Z"}});screen.submit();await screen.flush();assert.equal(h.calls.filter((c:Row)=>c[0]==="parent").length,1);assert.equal(h.calls.filter((c:Row)=>c[0]==="prepare").length,1);assert.equal(h.calls.filter((c:Row)=>c[0]==="status").length,1);assert.ok(h.calls.some((c:Row)=>c[0]==="replace"));screen.unmount();});
test("RESOURCE_CONFLICT preserves input and baseline until explicit fresh-editor choice",async()=>{const baseline="2026-10-03T03:00:00.000Z",screen=new Screen({mode:"edit",resourceId:"resource",expectedUpdatedAt:baseline,action:async(_s:unknown,form:FormData)=>{h.calls.push(["parent",form]);return{errors:{form:"충돌"},attemptDisposition:"conflict"};}});screen.change("title","내 수정 제목");screen.submit();await screen.flush();assert.equal(screen.field("title").props.value,"내 수정 제목");assert.equal(screen.field("expectedUpdatedAt").props.value,baseline);assert.equal(h.calls.some((c:Row)=>c[0]==="editor"),false);screen.submit();assert.equal(h.calls.filter((c:Row)=>c[0]==="parent").length,1);screen.button("입력 유지하고 최신 기준 사용").props.onClick();await Promise.resolve();await Promise.resolve();screen.render();assert.equal(screen.field("title").props.value,"내 수정 제목");assert.equal(screen.field("expectedUpdatedAt").props.value,"2026-10-03T04:00:00.000Z");assert.notEqual(screen.field("requestId").props.value,"form-request-key");screen.unmount();});
test("403 or account change clears private fields and selected file state",async()=>{const screen=new Screen({action:async()=>({errors:{form:"계정 변경"},attemptDisposition:"forbidden"})}),file=new File(["private"],"private.pdf");screen.select(file);screen.submit();await screen.flush();assert.match(text(screen.tree),/계정 변경/);assert.equal(screen.nodes.some(node=>node.props.name==="title"),false);assert.equal(screen.slots.includes("입력한 제목"),false);assert.equal(screen.slots.includes("입력한 내용입니다."),false);assert.ok(screen.slots.filter(Array.isArray).every((items:Row[])=>!items.includes(file)));assert.equal(screen.elements.get("attachments")!.files.length,0);assert.equal(screen.button("저장 결과 확인").props.disabled,false);screen.unmount();});
test("unmount aborts held upload and late completion cannot dispatch parent",async()=>{const gate=deferred<string>(),screen=new Screen({directUploadSupported:true});h.prepare=async()=>gate.promise;screen.select(new File(["bytes"],"held.pdf"));screen.submit();assert.equal(h.calls.filter((c:Row)=>c[0]==="prepare").length,1);screen.unmount();gate.resolve("ready-upload");await screen.flush();assert.equal(h.calls.filter((c:Row)=>c[0]==="parent").length,0);assert.equal(h.calls.filter((c:Row)=>c[0]==="replace").length,0);});
