import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { test } from "node:test";
const ciUrl="postgresql://postgres:postgres@127.0.0.1:5432/e_approval_test";
async function setup(){
  if(process.env.GITHUB_ACTIONS!=="true"||process.env.DATABASE_URL!==ciUrl||process.env.DIRECT_URL!==ciUrl)throw Error("Youth activity PostgreSQL tests require the exact disposable CI database.");
  const [{PrismaClient},{PrismaPg},schedules,learning,rules]=await Promise.all([import("../src/generated/prisma/client.ts"),import("@prisma/adapter-pg"),import("../src/lib/youth-mobile-schedules.ts"),import("../src/lib/youth-mobile-learning.ts"),import("../src/lib/youth-mobile-rules.ts")]);
  const prefix="ci-youth-activity-"+randomUUID(),db=new PrismaClient({adapter:new PrismaPg({connectionString:ciUrl,max:4})});
  await db.department.create({data:{id:prefix+"-dept",name:"합성 활동 검증",code:prefix}});await db.position.create({data:{id:prefix+"-position",name:"합성 직원",level:1}});
  const actor=await db.user.create({data:{id:prefix+"-actor",name:"합성 직원",departmentId:prefix+"-dept",positionId:prefix+"-position",canManageYouth:true}}),now=new Date("2026-10-04T03:00:00.000Z");
  const youths=await Promise.all(["a","b"].map(suffix=>db.youth.create({data:{id:prefix+"-"+suffix,name:prefix+"-"+suffix,admissionDate:"2026-01-01",dischargeDate:"9999-12-31",updatedAt:now}})));
  const ctx={actorId:actor.id,db,now:()=>now};
  return{prefix,db,actor,now,youths,ctx,schedules,learning,rules,async dispose(){const receipts=await db.youthMutationReceipt.findMany({where:{actorId:actor.id}});const concepts=receipts.filter(row=>row.targetType==="StudyConcept").map(row=>row.targetId);await db.studyConcept.deleteMany({where:{id:{in:concepts}}});await db.youthCommonSchedule.deleteMany({where:{content:{startsWith:prefix}}});await db.youth.deleteMany({where:{id:{in:youths.map(row=>row.id)}}});await db.youthMutationReceipt.deleteMany({where:{actorId:actor.id}});await db.auditLog.deleteMany({where:{actorId:actor.id}});await db.user.delete({where:{id:actor.id}});await db.position.delete({where:{id:prefix+"-position"}});await db.department.delete({where:{id:prefix+"-dept"}});await db.$disconnect();}};
}
const input=(content:string)=>({content,startMinute:540,endMinute:600,selectionMode:"DATES",occurrenceDates:["2026-10-04"],recurrenceWeekdays:[],recurrenceStartDate:"",recurrenceEndDate:"",scheduleType:"GENERAL"});
test("CI PostgreSQL activity actual CAS, all-concept cascade, audit rollback and vector ABA",{skip:process.env.GITHUB_ACTIONS!=="true",timeout:60000},async()=>{
 const s=await setup();try{
  const [a,b]=s.youths,first=await s.schedules.createMobilePersonalSchedule(s.ctx,a.id,{requestId:"pg-personal-create",input:input("합성 개인 일정")});
  const replay=await s.schedules.createMobilePersonalSchedule(s.ctx,a.id,{requestId:"pg-personal-create",input:input("합성 개인 일정")});assert.equal(replay.replayed,true);assert.equal(first.targetId,replay.targetId);
  await assert.rejects(s.schedules.updateMobilePersonalSchedule(s.ctx,first.targetId,{requestId:"pg-wrong-parent",youthId:b.id,expectedUpdatedAt:first.committedUpdatedAt,input:input("합성 개인 일정")}),{code:"NOT_FOUND"});
  const changed=await s.schedules.updateMobilePersonalSchedule(s.ctx,first.targetId,{requestId:"pg-personal-update",youthId:a.id,expectedUpdatedAt:first.committedUpdatedAt,input:input("변경 일정")});assert.equal(changed.committedUpdatedAt,new Date(s.now.getTime()+1).toISOString());
  await assert.rejects(s.schedules.updateMobilePersonalSchedule(s.ctx,first.targetId,{requestId:"pg-stale-equality",youthId:a.id,expectedUpdatedAt:first.committedUpdatedAt,input:input("변경 일정")}),{code:"YOUTH_CONFLICT"});
  const concept=await s.learning.createMobileYouthConcept(s.ctx,{requestId:"pg-concept",subject:"math",subunitId:"1-1",content:"합성 개념"});
  for(const youth of s.youths)await s.learning.checkMobileYouthConcept(s.ctx,youth.id,concept.targetId,{requestId:"pg-check-"+youth.id.slice(-1),checked:true,expectedYouthUpdatedAt:youth.updatedAt.toISOString(),expectedConceptUpdatedAt:concept.committedUpdatedAt});assert.equal(await s.db.studyConceptCheck.count({where:{conceptId:concept.targetId}}),2);
  const afterCheck=await s.db.youth.findUniqueOrThrow({where:{id:a.id}});await assert.rejects(s.learning.checkMobileYouthConcept(s.ctx,a.id,concept.targetId,{requestId:"pg-parent-ABA",checked:true,expectedYouthUpdatedAt:a.updatedAt.toISOString(),expectedConceptUpdatedAt:concept.committedUpdatedAt}),{code:"YOUTH_CONFLICT"});
  const badDb={$transaction:(operation: (tx:unknown)=>Promise<unknown>,options:object)=>s.db.$transaction(tx=>operation(new Proxy(tx,{get(target,key){if(key==="auditLog")return new Proxy(target.auditLog,{get(delegate,name){if(name==="create")return(args:Parameters<typeof delegate.create>[0])=>delegate.create({...args,data:{...args.data,actorId:s.prefix+"-missing"}});const value=Reflect.get(delegate,name);return typeof value==="function"?value.bind(delegate):value;}});const value=Reflect.get(target,key);return typeof value==="function"?value.bind(target):value;}})),options)} as unknown as NonNullable<typeof s.ctx.db>;
  await assert.rejects(s.learning.checkMobileYouthConcept({...s.ctx,db:badDb},a.id,concept.targetId,{requestId:"pg-check-auditfail",checked:false,expectedYouthUpdatedAt:afterCheck.updatedAt.toISOString(),expectedConceptUpdatedAt:concept.committedUpdatedAt}));assert.equal(await s.db.studyConceptCheck.count({where:{conceptId:concept.targetId,youthId:a.id}}),1);assert.equal((await s.db.youth.findUniqueOrThrow({where:{id:a.id}})).updatedAt.toISOString(),afterCheck.updatedAt.toISOString());assert.equal(await s.db.youthMutationReceipt.count({where:{actorId:s.actor.id,requestId:"pg-check-auditfail"}}),0);
  await s.learning.deleteMobileYouthConcept(s.ctx,concept.targetId,{requestId:"pg-concept-delete",expectedUpdatedAt:concept.committedUpdatedAt});assert.equal(await s.db.studyConceptCheck.count({where:{conceptId:concept.targetId}}),0);
  const batch={requestId:"pg-common-vector",operation:"save",targetWeekdays:[1,2],baselines:[1,2].map(weekday=>({weekday,startMinute:1200,scheduleId:null,expectedUpdatedAt:null})),startMinute:1200,endMinute:1260,content:s.prefix+"-vector"};const common=await s.schedules.mutateMobileCommonSchedules(s.ctx,batch),rows=common.result!.items;
  await s.db.youthCommonSchedule.delete({where:{id:rows[1].id}});const replacement=await s.db.youthCommonSchedule.create({data:{id:s.prefix+"-replacement",weekday:2,startHour:20,endHour:21,startMinute:1200,endMinute:1260,content:s.prefix+"-replacement",updatedAt:s.now}});
  await assert.rejects(s.schedules.mutateMobileCommonSchedules(s.ctx,{...batch,requestId:"pg-common-ABA",content:s.prefix+"-new",baselines:rows.map(row=>({weekday:row.weekday,startMinute:1200,scheduleId:row.id,expectedUpdatedAt:row.updatedAt}))}),{code:"YOUTH_CONFLICT"});assert.equal((await s.db.youthCommonSchedule.findUniqueOrThrow({where:{id:rows[0].id}})).content,batch.content);assert.equal((await s.db.youthCommonSchedule.findUniqueOrThrow({where:{id:replacement.id}})).content,s.prefix+"-replacement");assert.equal(await s.db.youthMutationReceipt.count({where:{actorId:s.actor.id,requestId:"pg-common-ABA"}}),0);
  await s.db.user.update({where:{id:s.actor.id},data:{status:"INACTIVE"}});await assert.rejects(s.rules.createMobileYouthRule(s.ctx,{requestId:"pg-retired-rule",targetYouthId:null,category:"생활",detail:"금지"}),{code:"UNAUTHORIZED"});
 }finally{await s.dispose();}
});
test("CI PostgreSQL concurrent same-key activity serializes actual parent/advisory locks to one child",{skip:process.env.GITHUB_ACTIONS!=="true",timeout:60000},async()=>{
 const s=await setup();try{let entered=0,release=()=>{};const barrier=new Promise<void>(yes=>{release=yes;});const pairDb={$transaction:(operation:(tx:unknown)=>Promise<unknown>,options:object)=>s.db.$transaction(tx=>operation(new Proxy(tx,{get(target,key){if(key==="$queryRaw")return async(...args:Parameters<typeof target.$queryRaw>)=>{const result=await target.$queryRaw(...args),sql=args[0] as {strings?:string[]};if(sql.strings?.join("").includes('FROM "User"')&&entered<2){entered++;if(entered===2)release();await barrier;}return result;};const value=Reflect.get(target,key);return typeof value==="function"?value.bind(target):value;}})),options)} as unknown as typeof s.ctx.db;
 const body={requestId:"pg-parallel-personal",input:input("동시 합성")},results=await Promise.all([s.schedules.createMobilePersonalSchedule({...s.ctx,db:pairDb},s.youths[0].id,body),s.schedules.createMobilePersonalSchedule({...s.ctx,db:pairDb},s.youths[0].id,body)]);assert.equal(entered,2);assert.equal(results[0].targetId,results[1].targetId);assert.equal(results.filter(row=>row.replayed).length,1);assert.equal(await s.db.youthPersonalSchedule.count({where:{youthId:s.youths[0].id}}),1);assert.equal(await s.db.youthMutationReceipt.count({where:{actorId:s.actor.id,requestId:body.requestId}}),1);assert.equal(await s.db.auditLog.count({where:{actorId:s.actor.id,targetType:"YouthPersonalSchedule",targetId:results[0].targetId}}),1);
 }finally{await s.dispose();}
});
