import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createActivityUI, settle, text } from './helpers/youth-activity-ui.mjs';
const stamp='2026-10-04T00:00:00.000Z',newStamp='2026-10-04T00:00:00.001Z';
const fail=(status=503)=>({ok:false,status,error:'합성 오류'}),ok=(data)=>({ok:true,data});
const event=(fields={})=>({preventDefault(){},stopPropagation(){},currentTarget:{fields},target:{fields}});
const receipt=(r,operation,targetId='old')=>ok({ok:true,requestId:r.args[0],operation,targetId,outcome:'present'});
const personalRow={id:'old',youthId:'youth-a',content:'입력 보존',startMinute:540,endMinute:600,selectionMode:'DATES',occurrenceDates:['2026-10-04'],recurrenceWeekdays:[],recurrenceStartDate:'',recurrenceEndDate:'',scheduleType:'GENERAL',hospitalName:null,escortType:null,escortUserId:null,escortName:null,nextAppointmentDate:null,updatedAt:stamp};
function personal(){const h=createActivityUI('personal',{actorId:'actor-a',canManage:true,selectedMonth:'2026-10',selectedYouthId:'youth-a',youths:[{id:'youth-a',name:'합성 청소년'}],staffDirectory:[],schedules:[personalRow],createSchedule:(...a)=>h.request('create')(...a),updateSchedule:(...a)=>h.request('update')(...a),deleteSchedule:(...a)=>h.request('delete')(...a)});return h;}
async function openPersonal(h){h.all('button').find(n=>n.props['aria-label']?.includes('전체 일정 묶음 수정')).props.onClick(event());await settle();}
function common(canManage=true){const h=createActivityUI('common',{actorId:'actor-a',canManage,schedules:[{id:'common-old',weekday:1,startHour:9,endHour:10,startMinute:540,endMinute:600,content:'원본 공통',updatedAt:stamp}],changeLogActors:[],changeLogs:[],changeLogFilters:{actorId:'all',weekday:'all',page:1,pageSize:10,total:0,totalPages:1},saveSchedule:(...a)=>h.request('commonSave')(...a),deleteSchedule:(...a)=>h.request('commonDelete')(...a)});return h;}
async function openCommon(h){h.all('button').find(n=>n.props['aria-label']?.includes('원본 공통')).props.onKeyDown({key:'Enter',preventDefault(){}});await settle();}
const submit=h=>h.find('form').props.onSubmit(event());
test('personal captures original ID/parent/token and blocks duplicate submission',async()=>{const h=personal();await openPersonal(h);const first=submit(h);submit(h);await settle();const r=h.pending('update');assert.equal(h.requests.filter(r=>r.name==='update').length,1);assert.equal(r.args[0],'old');assert.deepEqual({...r.args[2],requestId:'fixed'}, {youthId:'youth-a',expectedUpdatedAt:stamp,expectedActorId:'actor-a',requestId:'fixed'});h.resolve(ok({schedule:{...personalRow,updatedAt:newStamp}}),'update');await first;await settle();assert.equal(h.all('form').length,0);h.destroy();});
test('personal validation preserves edited input and focuses actual error region',async()=>{const h=personal();await openPersonal(h);h.all('textarea')[0].props.onChange({currentTarget:{value:'수정 유지'}});await settle();const work=submit(h);h.resolve(fail(400),'update');await work;await settle();assert.equal(h.all('textarea')[0].props.value,'수정 유지');assert(h.all('p').some(n=>n.props.role==='alert'));assert(h.events.some(e=>e.kind==='focus'));h.destroy();});
test('personal unknown retries receipt first with same key and never mutates after known commit',async()=>{const h=personal();await openPersonal(h);let work=submit(h);const key=h.pending('update').args[2].requestId;h.reject(Error('lost'),'update');await work;await settle();assert.equal(h.all('textarea')[0].props.disabled,true);work=submit(h);const r=h.pending('receipt');assert.equal(r.args[0],key);h.resolve(receipt(r,'personal.update'),'receipt');await settle();h.resolve(ok({youth:{id:'youth-a'},schedule:{...personalRow,updatedAt:newStamp}}),'personalBaseline');await work;await settle();assert.equal(h.requests.filter(r=>r.name==='update').length,1);h.destroy();});
test('personal 409 cannot overwrite until fresh GET is explicitly accepted',async()=>{const h=personal();await openPersonal(h);let work=submit(h);h.resolve(fail(409),'update');await work;await settle();await submit(h);assert.equal(h.requests.filter(r=>r.name==='update').length,1);h.controls.confirm=false;work=h.find('button','최신 내용 확인').props.onClick();h.resolve(ok({youth:{id:'youth-a'},schedule:{...personalRow,updatedAt:newStamp}}),'personalBaseline');await work;await settle();assert.equal(h.all('button').find(n=>text(n)==='저장').props.disabled,true);h.controls.confirm=true;work=h.find('button','최신 내용 확인').props.onClick();h.resolve(ok({youth:{id:'youth-a'},schedule:{...personalRow,updatedAt:newStamp}}),'personalBaseline');await work;await settle();work=submit(h);assert.equal(h.pending('update').args[2].expectedUpdatedAt,newStamp);h.resolve(ok({schedule:personalRow}),'update');await work;h.destroy();});
test('personal cancel deletion dispatches nothing and unmount ignores late private update',async()=>{const h=personal();await openPersonal(h);h.controls.confirm=false;await h.all('button').find(n=>text(n)==='전체 일정 삭제').props.onClick();assert.equal(h.requests.length,0);const work=submit(h),before=h.tree;h.destroy();h.resolve(ok({schedule:{...personalRow,content:'늦은 개인 내용'}}),'update');await work;assert.equal(h.tree,before);});
test('common readonly keeps the actual timetable visible without mutation skeleton',()=>{const h=common(false);assert(text(h.tree).includes('원본 공통'));assert(!h.all('div').some(n=>n.props.inert));assert(!h.all('CommonTimetableSkeleton').length);h.destroy();});
test('common frozen vector survives newer props and duplicate submit makes one batch',async()=>{const h=common();await openCommon(h);h.find('textarea','일정 내용').props.onChange({target:{value:'변경'}});await settle();h.setProps({schedules:[{id:'replacement',weekday:1,startMinute:540,endMinute:600,startHour:9,endHour:10,content:'새 서버 내용',updatedAt:newStamp}]});submit(h);submit(h);await settle();const r=h.pending('commonSave');assert.equal(h.requests.filter(r=>r.name==='commonSave').length,1);assert.deepEqual(r.args[6].baselines,[{weekday:1,startMinute:540,scheduleId:'common-old',expectedUpdatedAt:stamp}]);h.resolve(ok({schedules:[],sourceStartMinute:540,targetWeekdays:[1]}),'commonSave');await settle();h.destroy();});
test('common unknown delete uses original delete operation on result-confirm button',async()=>{const h=common();await openCommon(h);h.find('button','삭제').props.onClick();await settle();const key=h.pending('commonDelete').args[2].requestId;h.reject(Error('lost'),'commonDelete');await settle();assert.equal(h.find('textarea','일정 내용').props.disabled,true);submit(h);await settle();const r=h.pending('receipt');assert.equal(r.args[0],key);h.resolve(receipt(r,'common.batch','receipt-target'),'receipt');await settle();assert.equal(h.requests.filter(r=>r.name==='commonDelete').length,1);assert.equal(h.requests.filter(r=>r.name==='commonSave').length,0);assert(h.events.some(e=>e.kind==='reload'));h.destroy();});
test('desired check freezes both original tokens and late old-account result is ignored',async()=>{const unavailable=[],tokens=[],errors=[];const h=createActivityUI('check',{conceptId:'concept-a',conceptUpdatedAt:stamp,actorId:'actor-a',canManage:true,youth:{id:'youth-a',name:'가상',updatedAt:stamp},checked:false,conceptContent:'개념',onToggleError:v=>errors.push(v),onYouthToken:(...v)=>tokens.push(v),onYouthUnavailable:v=>unavailable.push(v)});const checkbox=h.find('input');checkbox.props.onChange({target:{checked:true}});checkbox.props.onChange({target:{checked:false}});await settle();const r=h.pending('check');assert.equal(r.args[2],true);assert.equal(r.args[3].expectedYouthUpdatedAt,stamp);assert.equal(r.args[3].expectedConceptUpdatedAt,stamp);assert.equal(h.requests.length,1);h.destroy();h.resolve(ok({isChecked:true,youthUpdatedAt:newStamp}),'check');await settle();assert.equal(tokens.length,0);assert.equal(errors.length,0);});
test('desired check 403 removes the parent column and 409 never toggles automatically',async()=>{const removed=[];const props={conceptId:'concept-a',conceptUpdatedAt:stamp,actorId:'actor-a',canManage:true,youth:{id:'youth-a',name:'가상',updatedAt:stamp},checked:false,conceptContent:'개념',onToggleError(){},onYouthToken(){},onYouthUnavailable:v=>removed.push(v)};const h=createActivityUI('check',props);h.find('input').props.onChange({target:{checked:true}});await settle();h.resolve(fail(403),'check');await settle();assert.deepEqual(removed,['youth-a']);assert.equal(h.find('input').props.disabled,true);h.destroy();const c=createActivityUI('check',props);c.find('input').props.onChange({target:{checked:true}});await settle();c.resolve(fail(409),'check');await settle();c.find('input').props.onChange({target:{checked:false}});assert.equal(c.requests.length,1);c.destroy();});
test('rules retains form after validation, unknown freezes controls and recovery cannot send new payload',async()=>{const h=createActivityUI('rules',{actorId:'actor-a',canManage:true,createRuleAction(){},deleteRuleAction(){},rules:[],targets:[],selectedCategory:'all',selectedTarget:'all',page:1,pageSize:10,total:0,totalPages:1});const form=h.find('form');let work=form.props.onSubmit(event({category:'생활',detail:'원본 규칙',targetYouthId:''}));h.resolve(fail(400),'ruleCreate');await work;await settle();assert(!h.events.some(e=>e.kind==='reset'));work=h.find('form').props.onSubmit(event({category:'안전',detail:'수정 규칙',targetYouthId:''}));h.reject(Error('lost'),'ruleCreate');await work;await settle();assert.equal(h.find('fieldset').props.disabled,true);work=h.find('form').props.onSubmit(event({category:'학습',detail:'임의 새 입력',targetYouthId:''}));assert(h.pending('receipt'));h.resolve(fail(404),'receipt');await settle();assert.equal(h.pending('ruleCreate').args[0].detail,'수정 규칙');h.resolve(ok({rule:{}}),'ruleCreate');await work;h.destroy();});
test('actual shared delete cancel is zero request, unknown same receipt and confirmed forbidden removes content',async()=>{const removed=[];const h=createActivityUI('delete',{operation:'rule.delete',actorId:'actor-a',id:'rule-a',expectedUpdatedAt:stamp,targetYouthId:'youth-a',message:'삭제 확인',dispatch:(...a)=>h.request('delete')(...a),onUnavailable:()=>removed.push(true)});h.controls.confirm=false;await submit(h);assert.equal(h.requests.length,0);h.controls.confirm=true;let work=submit(h);h.reject(Error('lost'),'delete');await work;await settle();work=submit(h);assert(h.pending('receipt'));h.resolve(fail(403),'receipt');await work;await settle();assert.deepEqual(removed,[true]);assert.equal(h.requests.filter(r=>r.name==='delete').length,1);h.destroy();});

test('personal typed403 immediately masks edit body, removes management actions and never resends',async()=>{const h=personal();await openPersonal(h);const work=submit(h);h.resolve(fail(403),'update');await work;await settle();assert.equal(h.all('form').length,0);assert.equal(h.all('textarea').length,0);assert.equal(h.requests.filter(r=>r.name==='update').length,1);h.all('button').find(n=>n.props['aria-label']?.includes('전체 일정 묶음 수정')).props.onClick(event());await settle();assert.equal(h.all('form').length,0);h.destroy();});

const commonScheduleButton=h=>h.all('button').find(n=>n.props['aria-label']?.includes('원본 공통'));
const pointerEvent=clientY=>({clientY,pointerId:1,preventDefault(){},stopPropagation(){},currentTarget:{setPointerCapture(){},hasPointerCapture(){return true;},releasePointerCapture(){}}});
test('common short slots keep one 48px editing target and all modal time/weekday controls are 44px',async()=>{
 const h=common();h.setProps({schedules:[{id:'common-old',weekday:1,startHour:9,endHour:10,startMinute:540,endMinute:550,content:'원본 공통',updatedAt:stamp}]});await settle();
 assert.equal(h.all('button').filter(n=>n.props['aria-label']?.includes('원본 공통')).length,1);
 assert(!h.all('button').some(n=>/시작 시간 조절|종료 시간 조절/.test(n.props['aria-label']??'')));
 assert(h.all('div').some(n=>n.props.style?.height===48));
 commonScheduleButton(h).props.onPointerDown(pointerEvent(100));await settle();commonScheduleButton(h).props.onPointerUp(pointerEvent(100));await settle();
 for(const label of ['시작 시간','종료 시간'])assert.match(h.find('select',label).props.className,/h-11/);
 const weekdays=h.all('button').filter(n=>n.props['aria-pressed']!==undefined);assert.equal(weekdays.length,5);
 for(const button of weekdays)assert.match(button.props.className,/h-11 min-w-11/);
 assert.equal(h.requests.length,0);h.destroy();
});
test('common duration changes use modal ten-minute controls with original source CAS',async()=>{
 const h=common();await openCommon(h);h.find('select','시작 시간').props.onChange({target:{value:'550'}});await settle();
 h.find('select','종료 시간').props.onChange({target:{value:'620'}});await settle();const work=submit(h);await settle();const r=h.pending('commonSave');
 assert.equal(r.args[1],550);assert.equal(r.args[2],620);assert.deepEqual(r.args[6].baselines,[{weekday:1,startMinute:540,scheduleId:'common-old',expectedUpdatedAt:stamp}]);
 h.resolve(ok({schedules:[],sourceStartMinute:540,targetWeekdays:[1]}),'commonSave');await work;h.destroy();
});
test('common whole-block drag retains duration and source ID/token when moved',async()=>{
 const h=common();commonScheduleButton(h).props.onPointerDown(pointerEvent(100));await settle();commonScheduleButton(h).props.onPointerMove(pointerEvent(188));await settle();
 commonScheduleButton(h).props.onPointerUp(pointerEvent(188));await settle();const r=h.pending('commonSave');
 assert.equal(r.args[1],600);assert.equal(r.args[2],660);assert.equal(r.args[2]-r.args[1],60);
 assert.deepEqual(r.args[6].baselines,[{weekday:1,startMinute:540,scheduleId:'common-old',expectedUpdatedAt:stamp}]);
 h.resolve(ok({schedules:[],sourceStartMinute:540,targetWeekdays:[1]}),'commonSave');await settle();h.destroy();
});
