import assert from 'node:assert/strict';
import { test } from 'node:test';
import { cleanupHarness } from './helpers/youth-decision-maintenance.mjs';
for(const kind of ['youth','resource']) {
 test(`${kind}: caller abort before candidate reads makes DB/storage0`,async()=>{const f=cleanupHarness(kind);f.upload('one');f.queue('one');const controller=new AbortController();controller.abort();assert.equal((await f.run({signal:controller.signal})).completed,0);assert.equal((await f.expire({signal:controller.signal})).expired,0);assert.equal(f.h.reads.length,0);assert.equal(f.h.writes.length,0);assert.equal(f.h.deleted.length,0);});
 test(`${kind}: aborted upload FOR UPDATE prevents expiry writes`,async()=>{const f=cleanupHarness(kind),controller=new AbortController();f.upload('one',{state:'ready'});f.h.before=({model,args})=>{if(model==='sql'&&args.strings.join('').includes('Upload'))controller.abort();};await f.expire({signal:controller.signal});assert.equal(f.h.state[f.uploadModel][0].state,'ready');assert.equal(f.h.state[f.queueModel].length,0);assert.equal(f.h.writes.length,0);assert.equal(f.h.deleted.length,0);});
 test(`${kind}: late physical delete after caller abort never proves DONE`,async()=>{const f=cleanupHarness(kind),controller=new AbortController();f.upload('one');f.queue('one');f.h.onDelete=(_row,options)=>{assert.equal(options.signal.aborted,false);controller.abort();assert.equal(options.signal.aborted,true);};const result=await f.run({signal:controller.signal});assert.equal(result.completed,0);assert.equal(f.h.deleted.length,1);assert.equal(f.h.exists.length,0);assert.equal(f.h.state[f.queueModel][0].state,'pending');assert.equal(f.h.state[f.uploadModel][0].state,'deleting');});
 test(`${kind}: wall-clock expiry after provider return fences DONE even before timer fires`,async()=>{const f=cleanupHarness(kind);f.upload('one');f.queue('one');f.h.onDelete=()=>{f.h.clock=1000;};const result=await f.run({budgetMs:1000});assert.equal(result.completed,0);assert.equal(f.h.exists.length,0);assert.equal(f.h.state[f.queueModel][0].state,'pending');assert.equal(f.h.state[f.uploadModel][0].state,'deleting');});
 test(`${kind}: old worker cannot publish after new queue claim replaces it`,async()=>{const f=cleanupHarness(kind);f.upload('one');f.queue('one');f.h.onDelete=()=>{f.h.state[f.queueModel][0].claimId='new-claim';};const result=await f.run();assert.equal(result.completed,0);assert.equal(f.h.state[f.queueModel][0].state,'running');assert.equal(f.h.state[f.queueModel][0].claimId,'new-claim');assert.equal(f.h.state[f.uploadModel][0].state,'deleting');});
 test(`${kind}: deadline during terminal scrub rolls back DONE and terminal state`,async()=>{const f=cleanupHarness(kind);f.upload('one');f.queue('one');f.h.after=({model,method,args})=>{if(model===f.uploadModel&&method==='updateMany'&&args.data.state==='expired')f.h.clock=1000;};await assert.rejects(f.run({budgetMs:1000}),/CLEANUP_CANCELLED/);assert.equal(f.h.state[f.queueModel][0].state,'running');assert.equal(f.h.state[f.queueModel][0].completedAt,null);assert.equal(f.h.state[f.uploadModel][0].state,'deleting');assert.equal(f.h.state[f.uploadModel][0].originalName,'private.pdf');});
 test(`${kind}: default known writer completes and scrubs only after confirmed absence`,async()=>{const f=cleanupHarness(kind);f.upload('one');f.queue('one');const result=await f.run();assert.equal(result.completed,1);assert.equal(f.h.deleted.length,1);assert.equal(f.h.exists.length,1);assert.equal(f.h.state[f.queueModel][0].state,'done');assert.equal(f.h.state[f.uploadModel][0].state,'expired');assert.equal(f.h.state[f.uploadModel][0].originalName,null);});
 test(`${kind}: blocked first40 candidates advance by backoff instead of starving later files`,async()=>{const f=cleanupHarness(kind);for(let i=0;i<40;i++){f.upload('blocked-'+String(i).padStart(2,'0'));f.queue('blocked-'+String(i).padStart(2,'0'));f.h.state.attachment.push({id:'owner-'+i,storageProvider:'synthetic',storageKey:'final/blocked-'+String(i).padStart(2,'0')});}f.upload('z-free');f.queue('z-free');for(let i=0;i<8;i++){const result=await f.run({limit:5});assert.equal(result.checked,5);assert.equal(result.completed,0);}assert.equal(f.h.deleted.length,0);const final=await f.run({limit:5});assert.equal(final.completed,1);assert.equal(f.h.deleted[0].id,'z-free');assert.equal(f.h.state[f.queueModel].filter(row=>row.state==='pending').length,40);});
 test(`${kind}: expired signed capability or unknown finalize never becomes absence proof`,async()=>{const f=cleanupHarness(kind);for(const [id,extra]of [['signed',{lastGrantExpiresAt:new Date(f.h.now.getTime()-1000),stagingKey:'staging/signed'}],['unknown',{hadUnknownWrite:true}]]){f.upload(id,extra);f.queue(id,id==='signed'?{objectKind:'staging',storageKey:'staging/signed'}:{});}const result=await f.run({limit:5});assert.equal(result.completed,0);assert.equal(f.h.deleted.length,2);assert.equal(f.h.exists.length,2);assert(f.h.state[f.queueModel].every(row=>row.state==='pending'&&row.lastErrorCode==='WRITE_PENDING'));assert(f.h.state[f.uploadModel].every(row=>row.state==='deleting'));});
}
test('youth: dedicated expiry lane advances expired uploads without provider or parent purge',async()=>{const f=cleanupHarness('youth');for(let i=0;i<40;i++)f.upload('expired-'+String(i).padStart(2,'0'),{state:'ready',stagingKey:'staging/'+i,lastGrantExpiresAt:new Date(f.h.now.getTime()-500)});let expired=0;for(let i=0;i<4;i++)expired+=(await f.expire({limit:3,budgetMs:1000})).expired;assert.equal(expired,12);assert.equal(f.h.state[f.uploadModel].filter(row=>row.state==='deleting').length,12);assert.equal(f.h.state[f.queueModel].length,24);assert.equal(f.h.deleted.length,0);assert.equal(f.h.state.youth.length,0);assert(f.h.state[f.uploadModel].filter(row=>row.state==='deleting').every(row=>row.originalName===null&&row.stagingKey&&row.finalKey));});
