import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, beforeEach, after, test } from "node:test";
import ts from "typescript";
// Only DB/session/file-consume ports are synthetic. The actual DAL/parser/adapter/route source runs.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row=Record<string,any>;
const now=new Date("2026-10-04T03:00:00Z"), actor={id:"actor",name:"직원",role:"USER",status:"ACTIVE",canViewYouthDetails:false,canViewYouthContacts:false,canDownloadYouthDocuments:true,canManageYouth:true};
const tables=["user","youth","youthFamilyContact","youthDischargeExtension","youthDecisionDocument","mathSettlement","youthMutationReceipt","youthViewRequest","youthDecisionUpload","youthDecisionFileCleanup","resourceAttachment","attachment","mobileDraftUpload","staffChatAttachment","auditLog"];
const h:Row={state:{},reads:[],writes:[],sql:[],next:0,session:null,auditFailure:false,txErrors:[],now};
const equal=(a:unknown,b:unknown)=>a instanceof Date&&b instanceof Date?a.getTime()===b.getTime():a===b;
function match(row:Row,where:Row={}):boolean{return Object.entries(where).every(([key,value])=>{if(key==="AND")return(Array.isArray(value)?value:[value]).every((part:Row)=>match(row,part));if(key==="OR")return value.some((part:Row)=>match(row,part));if(key.includes("_")&&!(key in row))return match(row,value);const current=row[key];if(value===null||value instanceof Date||typeof value!=="object")return equal(current,value);if("not"in value&&equal(current,value.not))return false;if("in"in value&&!value.in.some((v:unknown)=>equal(current,v)))return false;if("lte"in value&&!(current!=null&&current<=value.lte))return false;if("gte"in value&&!(current!=null&&current>=value.gte))return false;if("lt"in value&&!(current!=null&&current<value.lt))return false;if("contains"in value&&!String(current).toLowerCase().includes(String(value.contains).toLowerCase()))return false;if("some"in value)return(current??[]).some((v:Row)=>match(v,value.some));if("name"in value)return match(current,value);return true;});}
function related(model:string,row:Row):Row { if(model==='youth')return {...row,familyContacts:h.state.youthFamilyContact.filter((r:Row)=>r.youthId===row.id),dischargeExtensions:h.state.youthDischargeExtension.filter((r:Row)=>r.youthId===row.id).map((r:Row)=>related('youthDischargeExtension',r)),decisionDocuments:h.state.youthDecisionDocument.filter((r:Row)=>r.youthId===row.id),mathSettlement:h.state.mathSettlement.find((r:Row)=>r.studentId===row.id)??null}; if(model==='youthDischargeExtension')return {...row,processedBy:h.state.user.find((r:Row)=>r.id===row.processedById)}; if(model==='auditLog')return {...row,actor:h.state.user.find((r:Row)=>r.id===row.actorId)}; return row; }
function project(row:Row,args:Row={}):Row{const result:Row=args.select?{}:structuredClone(row);for(const[key,value]of Object.entries(args.select??args.include??{})){if(value===false)continue;else if(value===true)result[key]=structuredClone(row[key]);else if(Array.isArray(row[key]))result[key]=many(row[key],value as Row);else result[key]=row[key]==null?row[key]:project(row[key],value as Row);}return result;}
function many(rows:Row[],args:Row={}):Row[]{const order=Array.isArray(args.orderBy)?args.orderBy:[args.orderBy??{}];return rows.filter(row=>match(row,args.where)).sort((a,b)=>{for(const o of order)for(const[k,d]of Object.entries(o)){const n=a[k]<b[k]?-1:a[k]>b[k]?1:0;if(n)return d==="desc"?-n:n;}return 0;}).slice(args.skip??0,args.take===undefined?undefined:(args.skip??0)+args.take).map(row=>project(row,args));}
function change(row:Row,data:Row){for(const[key,value]of Object.entries(data))row[key]=value&&typeof value==="object"&&"increment"in value?row[key]+value.increment:structuredClone(value);}
const db:Row={mobileSession:{async findUnique(){return h.session;}},async $queryRaw(sql:Row){h.sql.push(sql);const projected=sql.strings.join('?').split(/\bFROM\b/i)[0];if(/\bpg_advisory_xact_lock\s*\(/i.test(projected))throw Object.assign(Error('unsupported void'),{name:'PrismaClientKnownRequestError',code:'P2010'});return [];},async $transaction(callback:(tx:Row)=>Promise<unknown>){h.beforeTx?.();if(h.txErrors.length)throw h.txErrors.shift();const old=structuredClone(h.state),written=h.writes.length;try{return await callback(db);}catch(error){h.state=old;h.writes.length=written;throw error;}}};
for(const model of tables)db[model]={async findMany(args:Row={}){h.reads.push({model,...args});return many(h.state[model].map((r:Row)=>related(model,r)),args);},async findUnique(args:Row){return(await this.findMany(args))[0]??null;},async findFirst(args:Row){return this.findUnique(args);},async findUniqueOrThrow(args:Row){const row=await this.findUnique(args);if(!row)throw Error('synthetic missing');return row;},async count(args:Row={}){return(await this.findMany(args)).length;},async create({data,...args}:Row){if(model==='auditLog'&&h.auditFailure)throw Error('PRIVATE_AUDIT');const row={id:`${model}-${++h.next}`,createdAt:h.now,updatedAt:h.now,sourceUpdatedAt:null,auditLogId:null,auditedAt:null,disclosureUntil:null,documentId:null,state:'committed',notBefore:h.now,nextAttemptAt:h.now,leaseUntil:null,claimId:null,lastErrorCode:null,attemptCount:0,finalizeClaimId:null,finalizeLeaseUntil:null,finalizeIv:null,finalizeWriteEvidence:null,hadUnknownWrite:false,lastGrantExpiresAt:null,stagingKey:null,finalKey:null,targetYouthId:null,consumedYouthId:null,consumedDocumentId:null,consumedMutationId:null,sourceKind:'client-file',purpose:'youth-decision',state2:null,requestHash:null,sourceFileUpdatedAt:null,payloadHash:null,committedUpdatedAt:null,committedTargetsJson:null,scrubbedAt:null,...(model==='youth'?{birthDate:null,age:null,phone:null,familyContact:null,familyPhone:null,familyRelationship:null,initialDischargeDate:null,actualDischargeDate:null,purgeStartedAt:null,purgedAt:null}:{}),...(model==='youthDecisionUpload'?{state:'uploading'}:model==='youthDecisionFileCleanup'?{state:'pending'}:model==='youthViewRequest'?{state:'recorded'}:{}),...structuredClone(data)};h.state[model].push(row);h.writes.push({model,action:'create',data});return project(related(model,row),args);},async createMany({data}:Row){for(const row of data)await this.create({data:row});return{count:data.length};},async update({where,data,...args}:Row){const row=h.state[model].find((r:Row)=>match(r,where));if(!row)throw Error('missing');change(row,data);h.writes.push({model,action:'update',data});return project(related(model,row),args);},async updateMany({where,data}:Row){const rows=h.state[model].filter((r:Row)=>match(r,where));for(const row of rows)change(row,data);h.writes.push({model,action:'updateMany',data});return{count:rows.length};},async upsert({where,create,update}:Row){const old=await this.findUnique({where});return old?this.update({where,data:update}):this.create({data:create});},async delete({where}:Row){const old=await this.findUnique({where});await this.deleteMany({where});return old;},async deleteMany({where}:Row){const old=h.state[model].length;h.state[model]=h.state[model].filter((r:Row)=>!match(r,where));h.writes.push({model,action:'deleteMany'});return{count:old-h.state[model].length};}};
const key='__actualYouthDecisionFiles';(globalThis as Row)[key]={h,db};
const url=(source:string)=>`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`;
const mocks=url(`const {h,db}=globalThis.${key};export const prisma=db;export function getAuditLogRequestData(){return {};}export async function getMobileSession(){return h.session;} `);
function compile(file:string,aliases:Record<string,string>={}){let source=readFileSync(new URL('../src/'+file,import.meta.url),'utf8');for(const[a,b]of Object.entries(aliases))source=source.replaceAll(JSON.stringify(a),JSON.stringify(b));return url(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);}
const base={'@/lib/prisma':mocks,'@/lib/audit-log-request':mocks,'@/lib/mobile-auth':mocks};
const contextURL=compile('lib/youth-mobile-context.ts',base), cleanupURL=compile('lib/youth-decision-file-cleanup.ts',{...base,'@/lib/youth-mobile-context':contextURL});
const uploadURL=compile('lib/youth-decision-uploads.ts',{...base,'@/lib/youth-mobile-context':contextURL,'@/lib/youth-decision-file-cleanup':cleanupURL});
const documentURL=compile('lib/youth-decision-documents.ts',{...base,'@/lib/youth-mobile-context':contextURL,'@/lib/youth-decision-uploads':uploadURL,'@/lib/youth-decision-file-cleanup':cleanupURL});
const reencryptURL=compile('lib/youth-decision-reencrypt.ts',{...base,'@/lib/youth-mobile-context':contextURL,'@/lib/youth-decision-file-cleanup':cleanupURL});
const apiURL=compile('lib/mobile-youth-decision-files.ts',{...base,'@/lib/youth-mobile-context':contextURL,'@/lib/youth-decision-uploads':uploadURL,'@/lib/youth-decision-documents':documentURL});
const reencrypt=await import(reencryptURL),uploads=await import(uploadURL),documents=await import(documentURL),cleanup=await import(cleanupURL),api=await import(apiURL),core=await import('../src/lib/youth-decision-file-core.ts');
const sha='a'.repeat(64), storedSha='b'.repeat(64);
const originalEnv={provider:process.env.ATTACHMENT_STORAGE_DRIVER,url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY,bucket:process.env.SUPABASE_STORAGE_BUCKET,encryption:process.env.ATTACHMENT_ENCRYPTION_KEY};
const storage:Row={async createResourceStagingGrant(){h.storageCalls.push('grant');assert.ok(h.state.youthDecisionUpload[0].lastGrantExpiresAt>h.now);h.beforeGrant?.();return {method:'PUT',url:'https://fixture.invalid/signed',headers:{'Content-Type':'application/pdf'},expiresAt:new Date(h.now.getTime()+7200000).toISOString()};},async finalizeResourceStoredUpload(input:Row){h.storageCalls.push('final');assert.equal(h.state.youthDecisionUpload[0].finalizeWriteEvidence,'pending');assert.ok(h.state.youthDecisionUpload[0].finalizeClaimId);h.beforeFinal?.();if(h.storageError)throw h.storageError;return{writeEvidence:'confirmed',size:input.size,wholeSha256:input.wholeSha256,storedSha256:storedSha,storedSize:input.size+32,...h.proofOverride};},async readResourceStoredFile(_ref:Row,input:Row){h.storageCalls.push('read');h.beforeExpose?.();if(h.storageError)throw h.storageError;await input.beforeExpose();h.exposures++;return{encrypted:h.storageEncrypted,body:new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('safe verified test bytes'));c.close();}}),size:input.expectedSize,verifiedSha256:sha};},async reencryptResourceStoredFile(input:Row){h.storageCalls.push('reencrypt');const claim=h.state.youthDecisionUpload.find((row:Row)=>row.finalKey===input.final.storageKey);assert.equal(claim.sourceKind,'legacy-reencrypt');assert.equal(claim.finalizeWriteEvidence,'pending');h.beforeReencrypt?.();if(h.storageError)throw h.storageError;return{alreadyEncrypted:false,writeEvidence:'confirmed',size:input.size,wholeSha256:input.wholeSha256,storedSha256:storedSha,storedSize:input.size+32,encryptionIvBase64:input.ivBase64};},async deleteResourceStoredFile(ref:Row){h.storageCalls.push('delete');h.deleted.push(ref.storageKey);},async resourceStoredFileExists(){h.storageCalls.push('exists');return h.exists;}};
const ctx=()=>({actorId:actor.id,db,now:()=>new Date(h.now),storage});
function youth(extra:Row={}){const row={id:'youth',name:'가상 학생',admissionDate:'2026-01-01',dischargeDate:'9999-12-31',initialDischargeDate:'9999-12-31',birthDate:null,actualDischargeDate:null,purgeStartedAt:null,purgedAt:null,retentionVersion:1,updatedAt:new Date(now),createdAt:new Date(now),...extra};h.state.youth.push(row);return row;}
const input=(extra:Row={})=>({requestId:'upload-key-one',targetYouthId:'youth',originalName:'결정문.pdf',mimeType:'application/pdf',size:24,wholeSha256:sha,...extra});
function upload(extra:Row={}){const row={id:'upload',actorId:actor.id,startRequestId:'upload-key-one',startPayloadHash:'c'.repeat(64),purpose:'youth-decision',sourceKind:'client-file',targetYouthId:'youth',originalName:'결정문.pdf',mimeType:'application/pdf',size:24,expectedSha256:sha,storageProvider:'supabase-storage',stagingKey:'youth-decision-documents/staging/upload',finalKey:'youth-decision-documents/final/upload',state:'ready',expiresAt:new Date(now.getTime()+7200000),completedAt:now,plaintextSha256:sha,storedSha256:storedSha,storedSize:56,finalizeWriteEvidence:'confirmed',finalizeClaimId:null,finalizeLeaseUntil:null,finalizeIv:null,hadUnknownWrite:false,lastGrantExpiresAt:null,consumedYouthId:null,consumedDocumentId:null,consumedMutationId:null,...extra};h.state.youthDecisionUpload.push(row);return row;}
function document(extra:Row={}){const row={id:'document',youthId:'youth',originalName:'결정문.pdf',storageProvider:'supabase-storage',storageKey:'youth-decision-documents/final/upload',mimeType:'application/pdf',size:24,createdAt:now,updatedAt:now,...extra};h.state.youthDecisionDocument.push(row);return row;}
describe('actual youth decision file DAL and route',()=>{
beforeEach(()=>{h.state=Object.fromEntries(tables.map(model=>[model,[]]));h.state.user=[structuredClone(actor)];Object.assign(h,{reads:[],writes:[],sql:[],next:0,auditFailure:false,txErrors:[],beforeTx:null,now:new Date(now),storageCalls:[],deleted:[],exists:false,exposures:0,storageError:null,beforeGrant:null,beforeFinal:null,beforeExpose:null,beforeReencrypt:null,storageEncrypted:false,proofOverride:{}});h.session={userId:actor.id,user:actor,expiresAt:new Date(Date.now()+60000)};process.env.ATTACHMENT_STORAGE_DRIVER='supabase-storage';process.env.SUPABASE_URL='https://synthetic.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='synthetic-only';process.env.SUPABASE_STORAGE_BUCKET='synthetic-only';process.env.ATTACHMENT_ENCRYPTION_KEY='a'.repeat(64);});
after(()=>{delete(globalThis as Row)[key];for(const[k,v]of Object.entries({ATTACHMENT_STORAGE_DRIVER:originalEnv.provider,SUPABASE_URL:originalEnv.url,SUPABASE_SERVICE_ROLE_KEY:originalEnv.key,SUPABASE_STORAGE_BUCKET:originalEnv.bucket,ATTACHMENT_ENCRYPTION_KEY:originalEnv.encryption})){if(v===undefined)delete process.env[k];else process.env[k]=v;}});
test('30MiB dotted extension policy accepts PDF/JPG and normalized null reason; rejects malicious controls',()=>{for(const name of['결정문.pdf','court.JPG'])assert.equal(core.youthDecisionFilename(name),name);assert.equal(core.parseYouthDecisionDownload({requestId:'download-key',reason:'CASE_SUPPORT',reasonDetail:null}).reasonDetail,null);assert.throws(()=>core.youthDecisionFilename('pdf'));assert.throws(()=>core.youthDecisionFilename('a/secret.pdf'));assert.throws(()=>core.parseYouthDecisionUpload(input({size:31457281})));assert.throws(()=>core.parseYouthDecisionDownload({requestId:'download-key',reason:'OTHER',reasonDetail:' '}));});
test('all file methods missing auth stop before target/body/query/storage and return private401',async()=>{h.session=null;for(const action of['policy','upload-start','upload-status','upload-request','upload-grant','upload-complete','upload-cancel','documents','attach','delete','download']){let touched=false;const response=await api.mobileYouthDecisionResponse(new Request('https://fixture.invalid?invalid=%xx',{method:'POST',body:'not-json'}),action,()=>{touched=true;throw Error('must not resolve');});assert.equal(response.status,401);assert.equal(touched,false);assert.equal(response.headers.get('cache-control'),'private, no-store');assert.equal(response.headers.get('x-content-type-options'),'nosniff');}assert.deepEqual(h.reads,[]);assert.deepEqual(h.storageCalls,[]);});
test('start/status are pure storage reads0 no policy init; samekey hash conflict and binding scope checked',async()=>{youth();const first=await uploads.startYouthDecisionUpload(ctx(),input());assert.equal(first.upload.state,'uploading');const writes=h.writes.length;assert.deepEqual(await uploads.getYouthDecisionUploadStatus(ctx(),{requestId:'upload-key-one'}),{upload:first.upload});assert.equal(h.writes.length,writes);assert.deepEqual(h.storageCalls,[]);assert.equal((await uploads.startYouthDecisionUpload(ctx(),input())).replayed,true);await assert.rejects(uploads.startYouthDecisionUpload(ctx(),input({originalName:'다른.pdf'})),{code:'REQUEST_CONFLICT'});h.state.youth[0].purgeStartedAt=now;await assert.rejects(uploads.getYouthDecisionUploadStatus(ctx(),{id:first.upload.id}),{code:'NOT_FOUND'});});
test('grant persists uncertainty before signing and rechecks revoked actor before response',async()=>{youth();const first=await uploads.startYouthDecisionUpload(ctx(),input());h.beforeGrant=()=>{h.state.user[0].canManageYouth=false;};await assert.rejects(uploads.grantYouthDecisionUpload(ctx(),first.upload.id),{code:'FORBIDDEN'});assert.equal(h.storageCalls.length,1);assert.ok(h.state.youthDecisionUpload[0].lastGrantExpiresAt>h.now);});
test('complete durable claim precedes provider write; actual digest proof required and revoked actor cannot ready',async()=>{youth();const row=upload({state:'uploading',completedAt:null,plaintextSha256:null,storedSha256:null,storedSize:null,finalizeWriteEvidence:null});h.beforeFinal=()=>{h.state.user[0].status='INACTIVE';};await assert.rejects(uploads.completeYouthDecisionUpload(ctx(),row.id),{code:'UNAUTHORIZED'});assert.equal(h.state.youthDecisionUpload[0].state,'finalizing');assert.equal(h.state.youthDecisionUpload[0].finalizeWriteEvidence,'confirmed');assert.equal(h.state.youthDecisionDocument.length,0);});
test('confirmed finalize allows consume exactlyonce atomically; stale identical parent rejects before effect',async()=>{const parent=youth(),row=upload({state:'uploading',completedAt:null,plaintextSha256:null,storedSha256:null,storedSize:null,finalizeWriteEvidence:null});assert.equal((await uploads.completeYouthDecisionUpload(ctx(),row.id)).upload.state,'ready');const body={requestId:'attach-key-one',expectedYouthUpdatedAt:parent.updatedAt.toISOString(),uploadIds:[row.id]};const first=await documents.attachYouthDecisionDocuments(ctx(),'youth',body);assert.equal(h.state.youthDecisionDocument.length,1);assert.equal(h.state.youthMutationReceipt.length,1);assert.equal(h.state.youthDecisionUpload[0].state,'consumed');assert.equal((await documents.attachYouthDecisionDocuments(ctx(),'youth',body)).replayed,true);assert.equal(h.state.youthDecisionDocument.length,1);await assert.rejects(documents.attachYouthDecisionDocuments(ctx(),'youth',{...body,requestId:'attach-stale-key'}),{code:'YOUTH_CONFLICT'});assert.doesNotMatch(JSON.stringify(first),/storageKey|Sha256|결정문/);});
test('audit failure rolls back document consume,parent token,receipt and cleanup ledger',async()=>{const parent=youth(),row=upload();h.auditFailure=true;await assert.rejects(documents.attachYouthDecisionDocuments(ctx(),'youth',{requestId:'attach-fail-key',expectedYouthUpdatedAt:parent.updatedAt.toISOString(),uploadIds:[row.id]}));assert.equal(h.state.youthDecisionDocument.length,0);assert.equal(h.state.youthDecisionUpload[0].state,'ready');assert.equal(h.state.youthMutationReceipt.length,0);assert.equal(h.state.youthDecisionFileCleanup.length,0);assert.equal(h.state.youth[0].updatedAt.getTime(),now.getTime());assert.deepEqual(h.deleted,[]);});
test('download audits only before verified bytes; stablekey audit1, expiry410 and source409 emit0',async()=>{youth();document();const body={requestId:'download-key-one',reason:'OTHER',reasonDetail:'검토'};await documents.downloadYouthDecisionDocument(ctx(),'document',body);await documents.downloadYouthDecisionDocument(ctx(),'document',body);assert.equal(h.exposures,2);assert.equal(h.state.auditLog.length,1);assert.equal(h.state.youthViewRequest.length,1);assert.doesNotMatch(JSON.stringify(h.state.youthViewRequest),/검토|결정문|storageKey/);h.now=new Date(now.getTime()+300000);await assert.rejects(documents.downloadYouthDecisionDocument(ctx(),'document',body),{code:'VIEW_REQUEST_EXPIRED'});assert.equal(h.exposures,2);h.now=now;h.state.youthDecisionDocument[0].updatedAt=new Date(now.getTime()+1);await assert.rejects(documents.downloadYouthDecisionDocument(ctx(),'document',body),{code:'VIEW_SNAPSHOT_CHANGED'});assert.equal(h.exposures,2);});
test('download late permission,parent purge or sourcechange blocks body; audit failure rolls back disclosure',async()=>{for(const mutate of[()=>h.state.user[0].canDownloadYouthDocuments=false,()=>h.state.youth[0].purgeStartedAt=now,()=>h.state.youthDecisionDocument[0].updatedAt=new Date(now.getTime()+1)]){h.state.user[0]={...actor};h.state.youth=[];h.state.youthDecisionDocument=[];youth();document();h.beforeExpose=mutate;await assert.rejects(documents.downloadYouthDecisionDocument(ctx(),'document',{requestId:'fresh-download-key',reason:'CASE_SUPPORT'}));assert.equal(h.exposures,0);}h.beforeExpose=null;h.state.user[0]={...actor};h.state.youth=[];h.state.youthDecisionDocument=[];youth();document();h.auditFailure=true;await assert.rejects(documents.downloadYouthDecisionDocument(ctx(),'document',{requestId:'audit-failed-key',reason:'CASE_SUPPORT'}),{code:'AUDIT_UNAVAILABLE'});assert.equal(h.exposures,0);assert.equal(h.state.youthViewRequest.length,0);});
test('document delete durable cleanup rolls back with audit and later succeeds exactlyonce',async()=>{const parent=youth(),doc=document(),row=upload({state:'consumed',consumedYouthId:'youth',consumedDocumentId:'document',consumedMutationId:'old-receipt',stagingKey:null});const body={requestId:'delete-doc-key',youthId:'youth',expectedYouthUpdatedAt:parent.updatedAt.toISOString(),expectedDocumentUpdatedAt:doc.updatedAt.toISOString()};h.auditFailure=true;await assert.rejects(documents.deleteYouthDecisionDocument(ctx(),'document',body));assert.equal(h.state.youthDecisionDocument.length,1);assert.equal(h.state.youthDecisionFileCleanup.length,0);h.auditFailure=false;await documents.deleteYouthDecisionDocument(ctx(),'document',body);assert.equal(h.state.youthDecisionDocument.length,0);assert.equal(h.state.youthDecisionUpload[0].state,'deleted');assert.equal(h.state.youthDecisionFileCleanup[0].state,'done');assert.equal((await documents.deleteYouthDecisionDocument(ctx(),'document',body)).replayed,true);assert.equal(h.state.youthMutationReceipt.length,1);assert.equal(row.id,'upload');});
test('issued signed grant expiry+absent HEAD never proves quiescence; repeats late object delete and stays pending',async()=>{youth();upload({state:'deleting',lastGrantExpiresAt:new Date(now.getTime()-1000)});await db.$transaction((tx:Row)=>cleanup.enqueueYouthDecisionFileCleanup(tx,{ref:{storageProvider:'supabase-storage',storageKey:'youth-decision-documents/staging/upload'},objectKind:'staging',sourceUploadId:'upload',youthId:'youth'},now));const first=await cleanup.reconcileYouthDecisionFileQueue(ctx());assert.equal(first.completed,0);assert.deepEqual(h.deleted,['youth-decision-documents/staging/upload']);assert.equal(h.state.youthDecisionFileCleanup[0].lastErrorCode,'WRITE_PENDING');h.now=new Date(now.getTime()+120000);await cleanup.reconcileYouthDecisionFileQueue(ctx());assert.equal(h.deleted.length,2);assert.equal(h.state.youthDecisionFileCleanup[0].state,'pending');});
test('all other live owners protected and wrong purge version cannot ignore own youth reference',async()=>{youth({purgeStartedAt:now,retentionVersion:2});document();upload({state:'deleting',consumedYouthId:'youth',consumedDocumentId:'document'});await db.$transaction((tx:Row)=>cleanup.enqueueYouthDecisionFileCleanup(tx,{ref:{storageProvider:'supabase-storage',storageKey:'youth-decision-documents/final/upload'},objectKind:'final',sourceUploadId:'upload',sourceMutationId:'purge:youth:1',youthId:'youth'},now));await cleanup.reconcileYouthDecisionFileQueue(ctx());assert.deepEqual(h.deleted,[]);assert.equal(h.state.youthDecisionFileCleanup[0].lastErrorCode,'LIVE_REFERENCE');h.now=new Date(now.getTime()+120000);h.state.youthDecisionFileCleanup[0].sourceMutationId='purge:youth:2';h.state.attachment.push({id:'other',storageProvider:'supabase-storage',storageKey:'youth-decision-documents/final/upload'});await cleanup.reconcileYouthDecisionFileQueue(ctx());assert.deepEqual(h.deleted,[]);});
test('legacy unknown writer is repeatedly removed but cannot claim physical deletion complete',async()=>{youth({purgeStartedAt:now,retentionVersion:3});document({storageKey:'legacy/one.pdf'});await db.$transaction((tx:Row)=>cleanup.enqueueYouthDecisionFileCleanup(tx,{ref:{storageProvider:'supabase-storage',storageKey:'legacy/one.pdf'},objectKind:'legacy',sourceMutationId:'purge:youth:3',youthId:'youth'},now));const result=await cleanup.reconcileYouthDecisionFileQueue(ctx());assert.equal(result.completed,0);assert.equal(h.state.youthDecisionFileCleanup[0].lastErrorCode,'LEGACY_WRITER_UNTRACKED');assert.deepEqual(h.deleted,['legacy/one.pdf']);});
test('admin immutable reencrypt claims before write then swaps source with parent+file CAS and durable legacy cleanup',async()=>{h.state.user[0].role='ADMIN';const parent=youth();document({storageKey:'legacy/one.pdf'});const result=await reencrypt.reencryptYouthDecisionDocuments(ctx());assert.equal(result.summary.encrypted,1);assert.equal(result.replacementBatchComplete,true);assert.equal(result.physicalCleanupComplete,false);assert.notEqual(h.state.youthDecisionDocument[0].storageKey,'legacy/one.pdf');assert.equal(h.state.youthDecisionUpload[0].state,'consumed');assert.equal(h.state.youthDecisionUpload[0].sourceStorageKey,'legacy/one.pdf');assert.equal(h.state.youthDecisionFileCleanup[0].storageKey,'legacy/one.pdf');assert.equal(h.state.youthDecisionFileCleanup[0].state,'pending');assert.equal(h.state.youth[0].updatedAt.getTime(),now.getTime()+1);assert.equal(parent.id,'youth');assert.doesNotMatch(JSON.stringify(result),/storageKey|one.pdf|Sha256/);});
test('reencrypt actor revoke or purge between write and swap keeps new file tracked and exposes no replacement',async()=>{for(const mutate of[()=>h.state.user[0].status='INACTIVE',()=>h.state.youth[0].purgeStartedAt=now]){h.state.user[0]={...actor,role:'ADMIN'};h.state.youth=[];h.state.youthDecisionDocument=[];h.state.youthDecisionUpload=[];h.state.youthMutationReceipt=[];h.state.youthDecisionFileCleanup=[];youth();document({storageKey:'legacy/one.pdf'});h.beforeReencrypt=mutate;const result=await reencrypt.reencryptYouthDecisionDocuments(ctx());assert.equal(result.summary.pending,1);assert.equal(h.state.youthDecisionDocument[0].storageKey,'legacy/one.pdf');assert.equal(h.state.youthDecisionUpload[0].state,'deleting');assert.equal(h.state.youthDecisionFileCleanup.length,1);assert.equal(h.state.youthMutationReceipt.length,0);}});
test('reencrypt already encrypted actual readproof writes0 and nonadmin/inactive access rejected before provider',async()=>{youth();document();await assert.rejects(reencrypt.reencryptYouthDecisionDocuments(ctx()),{code:'FORBIDDEN'});assert.deepEqual(h.storageCalls,[]);h.state.user[0].role='ADMIN';h.storageEncrypted=true;const result=await reencrypt.reencryptYouthDecisionDocuments(ctx());assert.equal(result.summary.alreadyEncrypted,1);assert.equal(h.state.youthDecisionUpload.length,0);assert.deepEqual(h.storageCalls,['read']);h.state.user[0].status='INACTIVE';await assert.rejects(reencrypt.reencryptYouthDecisionDocuments(ctx()),{code:'UNAUTHORIZED'});assert.deepEqual(h.storageCalls,['read']);});

test('reencrypt proven no-write failure retries the same immutable attempt after fresh source checks',async()=>{
 h.state.user[0].role='ADMIN';youth();document({storageKey:'legacy/one.pdf'});
 h.beforeReencrypt=()=>{h.storageError=Object.assign(Error('synthetic unavailable before write'),{writeEvidence:'none'});};
 const first=await reencrypt.reencryptYouthDecisionDocuments(ctx());assert.equal(first.summary.failed,1);assert.equal(h.state.youthDecisionUpload[0].state,'uploading');assert.equal(h.state.youthDecisionUpload[0].finalizeWriteEvidence,'none');assert.equal(h.state.youthDecisionFileCleanup.length,0);assert.equal(h.state.youthDecisionDocument[0].storageKey,'legacy/one.pdf');
 const finalKey=h.state.youthDecisionUpload[0].finalKey;h.storageError=null;h.beforeReencrypt=null;
 const second=await reencrypt.reencryptYouthDecisionDocuments(ctx());assert.equal(second.summary.encrypted,1);assert.equal(h.state.youthDecisionUpload.length,1);assert.equal(h.state.youthDecisionDocument[0].storageKey,finalKey);assert.equal(h.state.youthMutationReceipt.length,1);
});
test('reencrypt unknown write keeps uncertainty and never resets the same source for another writer',async()=>{
 h.state.user[0].role='ADMIN';youth();document({storageKey:'legacy/one.pdf'});h.beforeReencrypt=()=>{h.storageError=Object.assign(Error('synthetic unknown write'),{writeEvidence:'unknown'});};
 const first=await reencrypt.reencryptYouthDecisionDocuments(ctx());assert.equal(first.summary.pending,1);assert.equal(h.state.youthDecisionUpload[0].state,'deleting');assert.equal(h.state.youthDecisionUpload[0].hadUnknownWrite,true);assert.equal(h.state.youthDecisionFileCleanup.length,1);
 h.storageError=null;h.beforeReencrypt=null;const second=await reencrypt.reencryptYouthDecisionDocuments(ctx());assert.equal(second.summary.failed,1);assert.equal(h.storageCalls.filter((v:string)=>v==='reencrypt').length,1);assert.equal(h.state.youthDecisionDocument[0].storageKey,'legacy/one.pdf');assert.equal(h.state.youthMutationReceipt.length,0);
});

test('reencrypt parent CAS loss preserves source and a fresh parent creates a separate tracked attempt',async()=>{
 h.state.user[0].role='ADMIN';youth();document({storageKey:'legacy/one.pdf'});h.beforeReencrypt=()=>{h.state.youth[0].updatedAt=new Date(now.getTime()+1);};
 const first=await reencrypt.reencryptYouthDecisionDocuments(ctx());assert.equal(first.summary.pending,1);assert.equal(h.state.youthDecisionDocument[0].storageKey,'legacy/one.pdf');assert.equal(h.state.youthDecisionUpload[0].state,'deleting');assert.equal(h.state.youthDecisionFileCleanup.length,1);
 const oldKey=h.state.youthDecisionUpload[0].finalKey;h.beforeReencrypt=null;const second=await reencrypt.reencryptYouthDecisionDocuments(ctx());assert.equal(second.summary.encrypted,1);assert.equal(h.state.youthDecisionUpload.length,2);assert.notEqual(h.state.youthDecisionDocument[0].storageKey,oldKey);assert.equal(h.state.youthMutationReceipt.length,1);assert.equal(h.state.youthDecisionUpload[0].state,'deleting');
});

});
