import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { beforeEach, after, describe, test } from "node:test";
import ts from "typescript";
// Actual roster TSX; hook and boundary components/server actions only are mocked.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row=Record<string,any>;
const filename=new URL('../src/components/youth-roster-board.tsx',import.meta.url), source=readFileSync(filename,'utf8'), sourceSha256=createHash('sha256').update(source).digest('hex');
const key='__actualYouthRosterFlow',h:Row={current:null,calls:[],api:{},confirm:true};(globalThis as Row)[key]=h;
const url=(value:string)=>`data:text/javascript;base64,${Buffer.from(value).toString('base64')}`;
const hooks = url(`const h=globalThis.${key};export function useState(initial){const r=h.current,i=r.index++;if(!(i in r.slots))r.slots[i]=typeof initial==='function'?initial():initial;return[r.slots[i],next=>{r.slots[i]=typeof next==='function'?next(r.slots[i]):next;}];}export function useRef(initial){const r=h.current,i=r.index++;if(!(i in r.slots))r.slots[i]={current:initial};return r.slots[i];}export function useEffect(fn,deps){const r=h.current,i=r.index++,old=r.effects[i];if(!old||deps.some((v,j)=>v!==old.deps[j]))r.scheduled.push(()=>{old?.cleanup?.();r.effects[i]={deps,cleanup:fn()};});}export function useId(){const r=h.current;return 'id-'+r.index++;}export function useMemo(fn){const r=h.current;r.index++;return fn();}export function useCallback(fn){const r=h.current;r.index++;return fn;}export function useTransition(){const r=h.current;r.index++;return[false,fn=>{const job=Promise.resolve(fn());r.jobs.push(job);job.catch(()=>{});}];}export function startTransition(fn){const r=h.current,job=Promise.resolve(fn());r.jobs.push(job);job.catch(()=>{});}`);
const jsx = url(`export const Fragment='Fragment';export function jsx(type,props){return{type,props:props??{}};}export const jsxs=jsx;`);
const ports=url(`export const AppModal='AppModal';export const PageTitle='PageTitle';export const SplitDateInput='SplitDateInput';export const UserIdentity='UserIdentity';`);
let transformed=`const window={confirm:()=>globalThis.${key}.confirm};\n${source}`;
transformed=transformed.replace("function YouthDischargeExtensionModal(","export function YouthDischargeExtensionModal(");
transformed=transformed.replaceAll('"react"',JSON.stringify(hooks));for(const alias of['@/components/app-modal','@/components/page-title','@/components/split-date-input','@/components/user-identity'])transformed=transformed.replaceAll(JSON.stringify(alias),JSON.stringify(ports));
const output=ts.transpileModule(transformed,{fileName:filename.pathname,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText.replaceAll('"react/jsx-runtime"',JSON.stringify(jsx));
const {YouthRosterFormModal,YouthDischargeExtensionModal}=await import(url(output));
const baseline='2026-10-04T03:00:00.000Z',fresh='2026-10-04T04:00:00.000Z';
const permissions={canViewYouthBasic:true,canManageYouth:true,canViewYouthDetails:true,canViewYouthContacts:true,canDownloadYouthDocuments:true,canDeleteYouth:false};
const youth={id:'youth',name:'가상 학생',admissionDate:'2026-01-01',birthDate:'2009-01-01',initialDischargeDate:'2026-11-01',dischargeDate:'2026-12-01',age:17,koreanAge:18,phone:null,familyContacts:[],hasContact:true,decisionDocuments:[],dischargeExtensions:[],updatedAt:baseline};
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>resolve=yes);return{promise,resolve};}
function walk(node:unknown):Row[]{if(Array.isArray(node))return node.flatMap(walk);if(!node||typeof node!=='object'||!('type'in node))return[];return[node as Row,...Object.values((node as Row).props).flatMap(walk)];}
function text(node:unknown):string{if(Array.isArray(node))return node.map(text).join('');if(node&&typeof node==='object'&&'type'in node)return text((node as Row).props.children);return typeof node==='string'?node:'';}
class Screen{slots:Row[]=[];index=0;effects:Row[]=[];scheduled:Array<()=>void>=[];jobs:Promise<unknown>[]=[];nodes:Row[]=[];tree:Row|null=null;mounted=true;props:Row;
 constructor(extra:Row={}){this.props={actorId:'actor',modal:{mode:'edit',youth:structuredClone(youth),canDelete:false},permissions:{...permissions},createYouth:async(...args:unknown[])=>{h.calls.push(['create',...args]);return h.api.create(...args);},updateYouth:async(...args:unknown[])=>{h.calls.push(['update',...args]);return h.api.update(...args);},deleteYouth:async()=>{},deleteDecisionDocument:async()=>{},onClose:()=>h.calls.push(['close']),onSaved:(value:unknown)=>h.calls.push(['saved',value]),onDeleted:()=>{},onDecisionDocumentDownload:()=>{},mutationStatus:async(...args:unknown[])=>{h.calls.push(['status',...args]);return h.api.status(...args);},loadEditor:async(...args:unknown[])=>{h.calls.push(['editor',...args]);return h.api.editor(...args);},recordYouthContactView:async()=>({ok:true,data:{phone:'010-1234-5678',familyContacts:[{id:'family',relationship:'보호자',phone:'010-2222-3333'}]}}),...extra};this.render();}
 render(){this.index=0;this.scheduled=[];h.current=this;this.tree=YouthRosterFormModal(this.props);this.nodes=walk(this.tree);for(const effect of this.scheduled)effect();return this;}
 submit(){this.nodes.find(n=>n.type==='form')!.props.onSubmit({preventDefault(){}});this.render();}
 changeName(value:string){this.nodes.find(n=>n.type==='input'&&n.props.autoFocus)!.props.onChange({target:{value}});this.render();}
 async flush(){for(let i=0;i<3;i++){await Promise.allSettled(this.jobs);await Promise.resolve();}if(this.mounted)this.render();}
 click(label:string){const node=this.nodes.find(n=>n.type==='button'&&text(n).includes(label));assert.ok(node,'missing '+label);node.props.onClick();this.render();}
 reveal(){this.nodes.find(n=>typeof n.props.onReveal==='function')!.props.onReveal();this.render();}
 file(file:File){this.nodes.find(n=>n.type==='input'&&n.props.type==='file')!.props.onChange({target:{files:[file],value:'chosen'}});this.render();}
 unmount(){this.mounted=false;for(const effect of this.effects)effect?.cleanup?.();}
}
class ExtensionScreen extends Screen {
  render(){this.index=0;this.scheduled=[];h.current=this;this.tree=YouthDischargeExtensionModal(this.props);this.nodes=walk(this.tree);for(const effect of this.scheduled)effect();return this;}
}
function extensionScreen(action:(id:string,body:Row)=>Promise<Row>){return new ExtensionScreen({actorId:'actor',youthId:'youth',youthName:'합성 학생',currentDischargeDate:'2026-12-01',initialDischargeDate:'2026-11-01',extensions:[],expectedUpdatedAt:baseline,extendYouthDischarge:async(id:string,body:Row)=>{h.calls.push(['extend',id,body]);return action(id,body);},mutationStatus:async(key:string)=>{h.calls.push(['extension-status',key]);return{ok:false,code:'NOT_FOUND',status:404,error:'미기록'};},onExtended:()=>h.calls.push(['extended']),onClose:()=>h.calls.push(['close'])});}
describe('actual youth roster immutable edit flow',()=>{
beforeEach(()=>Object.assign(h,{calls:[],confirm:true,api:{create:async()=>({ok:true,data:{youth:null}}),update:async()=>({ok:true,data:{youth:null}}),status:async()=>({ok:false,code:'NOT_FOUND',status:404,error:'미확인'}),editor:async()=>({ok:true,data:{youth:{...youth,phone:null,familyContacts:[],notes:[],updatedAt:fresh}}})}}));
after(()=>delete(globalThis as Row)[key]);
test('actual source fingerprint and synchronous duplicate gate',async t=>{t.diagnostic('YouthRosterFormModal source SHA256: '+sourceSha256);const gate=deferred<Row>();h.api.update=()=>gate.promise;const screen=new Screen();screen.submit();screen.submit();assert.equal(h.calls.filter((c:Row)=>c[0]==='update').length,1);gate.resolve({ok:true,data:{youth:null}});await screen.flush();screen.unmount();});
test('name edit preserves hidden/unrevealed/unchanged DOB contact initial fields by omission',async()=>{for(const flags of[{canViewYouthDetails:false,canViewYouthContacts:false},{canViewYouthDetails:true,canViewYouthContacts:true}]){h.calls=[];const screen=new Screen({permissions:{...permissions,...flags}});screen.changeName('수정 이름');screen.submit();await screen.flush();const value=h.calls.find((c:Row)=>c[0]==='update')[2];for(const field of['birthDate','phone','familyContacts','dischargeDate'])assert.equal(Object.hasOwn(value,field),false,field);assert.equal(value.name,'수정 이름');assert.equal(value.expectedUpdatedAt,baseline);assert.equal(value.expectedActorId,'actor');screen.unmount();}});
test('explicitly revealed but unchanged contacts are omitted; only intentional change sent',async()=>{const screen=new Screen();screen.reveal();await screen.flush();screen.changeName('수정 이름');screen.submit();await screen.flush();const value=h.calls.find((c:Row)=>c[0]==='update')[2];assert.equal(Object.hasOwn(value,'phone'),false);assert.equal(Object.hasOwn(value,'familyContacts'),false);screen.unmount();});
test('unknown transport keeps exact key/body/files and resolves own receipt before redispatch',async()=>{h.api.update=async()=>{throw Error('PRIVATE_NETWORK');};const screen=new Screen();screen.file(new File(['safe'],'가상.pdf',{type:'application/pdf'}));screen.changeName('입력 보존');screen.submit();await screen.flush();const first=h.calls.find((c:Row)=>c[0]==='update');screen.changeName('불명확 중 변경');screen.props.modal.youth.updatedAt=fresh;screen.render();screen.submit();await screen.flush();const updates=h.calls.filter((c:Row)=>c[0]==='update');assert.equal(updates.length,2);assert.equal(updates[1][2],first[2]);assert.equal(updates[1][3],first[3]);assert.equal(updates[1][2].name,'입력 보존');assert.equal(updates[1][2].expectedUpdatedAt,baseline);assert.deepEqual(h.calls.filter((c:Row)=>['update','status'].includes(c[0])).map((c:Row)=>c[0]),['update','status','update']);assert.doesNotMatch(text(screen.tree),/PRIVATE_NETWORK/);screen.unmount();});
test('committed unavailable creation receipt stops upload and parent re-execution',async()=>{h.api.create=async()=>{throw Error('lost');};const screen=new Screen({modal:{mode:'create'}});screen.changeName('새 입력');screen.submit();await screen.flush();h.api.status=async()=>({ok:true,data:{operation:'profile.create',targetId:'new-youth',outcome:'unavailable',youth:null}});screen.submit();await screen.flush();assert.equal(h.calls.filter((c:Row)=>c[0]==='create').length,1);assert.equal(h.calls.filter((c:Row)=>c[0]==='saved').length,0);assert.ok(h.calls.some((c:Row)=>c[0]==='close'));screen.unmount();});
test('CAS409 keeps input and token until explicit fresh baseline adoption',async()=>{h.api.update=async()=>({ok:false,code:'YOUTH_CONFLICT',status:409,error:'최신 정보 확인'});const screen=new Screen();screen.changeName('입력 보존');screen.submit();await screen.flush();screen.submit();assert.equal(h.calls.filter((c:Row)=>c[0]==='update').length,1);screen.click('최신 수정 기준 확인');await screen.flush();screen.submit();await screen.flush();const values=h.calls.filter((c:Row)=>c[0]==='update').map((c:Row)=>c[2]);assert.equal(values[1].name,'입력 보존');assert.equal(values[1].expectedUpdatedAt,fresh);assert.notEqual(values[1].requestId,values[0].requestId);screen.unmount();});
test('403 clears retained body and files and blocks another submission',async()=>{h.api.update=async()=>({ok:false,code:'FORBIDDEN',status:403,error:'계정 변경'});const screen=new Screen();screen.file(new File(['safe'],'가상.pdf'));screen.submit();await screen.flush();const call=h.calls.find((c:Row)=>c[0]==='update');assert.deepEqual(Object.keys(call[2]),[]);assert.equal(Array.from(call[3].keys()).length,0);screen.submit();await screen.flush();assert.equal(h.calls.filter((c:Row)=>c[0]==='update').length,1);screen.unmount();});
test('actor changes during held save invalidate private body and late onSaved',async()=>{const gate=deferred<Row>();h.api.update=()=>gate.promise;const screen=new Screen();screen.submit();const call=h.calls.find((c:Row)=>c[0]==='update');screen.props.actorId='other';screen.render();gate.resolve({ok:true,data:{youth:{...youth,notes:[]}}});await screen.flush();assert.deepEqual(Object.keys(call[2]),[]);assert.equal(h.calls.some((c:Row)=>c[0]==='saved'),false);screen.unmount();});
test('unmount during held unknown lookup prevents any late parent dispatch',async()=>{h.api.update=async()=>{throw Error('lost');};const screen=new Screen();screen.submit();await screen.flush();const gate=deferred<Row>();h.api.status=()=>gate.promise;screen.submit();screen.unmount();gate.resolve({ok:false,code:'NOT_FOUND',status:404,error:'missing'});await screen.flush();assert.equal(h.calls.filter((c:Row)=>c[0]==='update').length,1);});
test('extension definite validation permits corrected input with a new frozen request',async()=>{const screen=extensionScreen(async()=>({ok:false,code:'INVALID_REQUEST',status:400,error:'사유 확인'}));screen.nodes.find(n=>n.type==='textarea')!.props.onChange({target:{value:'원래 입력'}});screen.render();screen.submit();await screen.flush();screen.nodes.find(n=>n.type==='textarea')!.props.onChange({target:{value:'수정 입력'}});screen.render();screen.submit();await screen.flush();const calls=h.calls.filter((c:Row)=>c[0]==='extend');assert.equal(calls.length,2);assert.equal(calls[1][2].reason,'수정 입력');assert.notEqual(calls[0][2].requestId,calls[1][2].requestId);screen.unmount();});
test('extension unknown retry checks own receipt first and keeps exact original body',async()=>{const screen=extensionScreen(async()=>{throw Error('unknown');});screen.submit();await screen.flush();const first=h.calls.find((c:Row)=>c[0]==='extend')[2];screen.submit();await screen.flush();assert.deepEqual(h.calls.filter((c:Row)=>['extend','extension-status'].includes(c[0])).map((c:Row)=>c[0]),['extend','extension-status','extend']);assert.equal(h.calls.filter((c:Row)=>c[0]==='extend')[1][2],first);screen.unmount();});
test('extension synchronous gate and unmount prevent late parent callback',async()=>{const held=deferred<Row>(),screen=extensionScreen(()=>held.promise);screen.submit();screen.submit();assert.equal(h.calls.filter((c:Row)=>c[0]==='extend').length,1);screen.unmount();held.resolve({ok:true,data:{}});await screen.flush();assert.equal(h.calls.some((c:Row)=>c[0]==='extended'),false);});

test('extension private failure erases captured reason and prevents a new request',async()=>{const screen=extensionScreen(async()=>({ok:false,code:'FORBIDDEN',status:403,error:'계정 확인'}));screen.nodes.find(n=>n.type==='textarea')!.props.onChange({target:{value:'민감한 입력'}});screen.render();screen.submit();await screen.flush();const body=h.calls.find((c:Row)=>c[0]==='extend')[2];assert.equal(body.reason,'');assert.equal(body.extendedDischargeDate,'');screen.submit();await screen.flush();assert.equal(h.calls.filter((c:Row)=>c[0]==='extend').length,1);screen.unmount();});

});
