import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View, type KeyboardTypeOptions } from "react-native";
import { formatScheduleDate, formatScheduleMinute, formatScheduleTimestamp, scheduleSourceLabel } from "@/lib/schedules";
import { useTheme } from "@/lib/theme";
import type { MobileScheduleCounts, MobileScheduleItem, MobileScheduleSnapshot } from "@/lib/types";

export function WorkScheduleRowLink({ title, accessibilityLabel, numberOfLines, disabled = false, onPress }: { title: string; accessibilityLabel?: string; numberOfLines?: number; disabled?: boolean; onPress: () => void }) {
  const theme = useTheme(); const [focused, setFocused] = useState(false);
  return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel ?? title} accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} onFocus={() => setFocused(true)} onBlur={() => setFocused(false)} style={({ pressed }) => [{ minHeight: 44, minWidth: 44, width: "100%", justifyContent: "center", alignItems: "flex-start", paddingHorizontal: 4, paddingVertical: 6, borderWidth: 2, borderRadius: 8 }, { borderColor: focused ? theme.accent : "transparent", backgroundColor: pressed || focused ? theme.accentSoft : "transparent", opacity: disabled ? 0.5 : 1 }]}><Text numberOfLines={numberOfLines} style={{ color: theme.accent, fontSize: 14, fontWeight: "700", lineHeight: 21, width: "100%", flexShrink: 1 }}>{title}</Text></Pressable>;
}
export function WorkScheduleSummary({ counts, label = "선택일 일정" }: { counts: MobileScheduleCounts; label?: string }) {
  const theme = useTheme();
  return <View accessibilityLabel={`${label} ${counts.total}건, 직접 등록 ${counts.manual}건, 승인 휴가 ${counts.vacation}건, 병원 예약 ${counts.hospital}건`} style={[styles.summary, { backgroundColor: theme.surfaceMuted, borderColor: theme.border }]}><Text style={[styles.label, { color: theme.text }]}>{label} {counts.total.toLocaleString()}건</Text><Text style={[styles.small, { color: theme.secondary }]}>직접 등록 {counts.manual.toLocaleString()} · 승인 휴가 {counts.vacation.toLocaleString()} · 병원 예약 {counts.hospital.toLocaleString()}</Text></View>;
}
export function WorkScheduleContent({ item }: { item: MobileScheduleItem }) {
  const theme = useTheme();
  return <View style={styles.group}><Text style={[styles.small, { color: theme.secondary }]}>{formatScheduleDate(item.scheduleDate)} · {item.allDay ? "종일" : `${formatScheduleMinute(item.startMinute)}–${formatScheduleMinute(item.endMinute)}`}</Text><Text style={[styles.small, { color: theme.secondary }]}>{scheduleSourceLabel(item)}</Text><Text selectable style={[styles.body, { color: theme.text }]}>{item.content}</Text>{item.sourceType === "manual" ? <Text style={[styles.small, { color: theme.secondary }]}>최근 변경 {formatScheduleTimestamp(item.updatedAt)} · 시설 공용 일정</Text> : item.sourceType === "approvedVacation" ? <><Text style={[styles.small, { color: theme.secondary }]}>{item.staffName} · {item.vacationLabel}</Text><Text style={[styles.small, { color: theme.secondary }]}>{[item.departmentName, item.positionName].filter(Boolean).join(" · ")}</Text><Text style={[styles.small, { color: theme.secondary }]}>승인 휴가에서 표시한 일정입니다. 이 화면에서는 수정하지 않습니다.</Text></> : <><Text style={[styles.small, { color: theme.secondary }]}>{item.youthName} · {item.hospitalName}</Text><Text style={[styles.small, { color: theme.secondary }]}>동행 {item.escortName || "미지정"}</Text><Text style={[styles.small, { color: theme.secondary }]}>청소년 병원 예약에서 표시한 일정입니다. 이 화면에서는 수정하지 않습니다.</Text></>}</View>;
}
export function WorkScheduleSnapshot({ snapshot, label }: { snapshot: MobileScheduleSnapshot | null; label: string }) {
  const theme = useTheme(); return <View style={styles.group}><Text style={[styles.label, { color: theme.text }]}>{label}</Text>{snapshot ? <><Text style={[styles.small, { color: theme.secondary }]}>{formatScheduleDate(snapshot.scheduleDate)} · {formatScheduleMinute(snapshot.startMinute)}–{formatScheduleMinute(snapshot.endMinute)}</Text><Text selectable style={[styles.body, { color: theme.text }]}>{snapshot.content}</Text></> : <Text style={[styles.small, { color: theme.secondary }]}>없음</Text>}</View>;
}
export function ScheduleField({ name, label, value, onChange, error, disabled = false, multiline = false, placeholder, hint, keyboardType }: { name: string; label: string; value: string; onChange: (name: string, value: string) => void; error?: string; disabled?: boolean; multiline?: boolean; placeholder?: string; hint?: string; keyboardType?: KeyboardTypeOptions }) {
  const theme = useTheme(); const [focused, setFocused] = useState(false);
  return <View style={styles.field}><Text style={[styles.label, { color: theme.text }]}>{label}</Text>{hint ? <Text style={[styles.small, { color: theme.secondary }]}>{hint}</Text> : null}<TextInput accessibilityLabel={label} accessibilityHint={hint} aria-invalid={!!error} editable={!disabled} value={value} placeholder={placeholder} placeholderTextColor={theme.muted} keyboardType={keyboardType} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} onFocus={() => setFocused(true)} onBlur={() => setFocused(false)} onChangeText={next => onChange(name, next)} style={[styles.input, multiline && styles.multiline, { color: theme.text, backgroundColor: theme.surface, borderColor: error ? theme.danger : focused ? theme.accent : theme.muted, opacity: disabled ? 0.65 : 1 }]} />{error ? <Text style={[styles.small, { color: theme.danger }]}>{error}</Text> : null}</View>;
}
const styles = StyleSheet.create({ group: { gap: 6 }, summary: { padding: 8, gap: 4, borderWidth: 1, borderRadius: 8 }, label: { fontSize: 15, fontWeight: "700" }, small: { fontSize: 13, lineHeight: 20, fontVariant: ["tabular-nums"] }, body: { fontSize: 15, lineHeight: 23 }, field: { gap: 4 }, input: { minHeight: 44, borderWidth: 1.5, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 10, fontSize: 16 }, multiline: { minHeight: 160 } });
