import { KeyboardScrollView } from "@/components/keyboard-scroll-view";
import { KeyboardScreen } from "@/components/keyboard-screen";
/* Privacy guards and immutable mutation baselines deliberately use synchronous refs; permission changes must clear local state before user actions can resume. */
/* eslint-disable react-hooks/refs, react-hooks/set-state-in-effect */
import { useEffect, useRef, useState } from 'react';
import { Redirect, router } from 'expo-router';
import { ActivityIndicator, Text, View } from 'react-native';
import { useSession } from '@/lib/session';
import { useTheme } from '@/lib/theme';
import { isYouthList, youthId, youthPage } from '@/lib/youth';
import { isYouthActivityResult, isYouthRules, youthRuleCategories } from '@/lib/youth-activities';
import type { YouthRule } from '@/types/youth';
import { AccountFeedback } from './account-feedback';
import { PrimaryButton, TextAction } from './ui';
import { YouthField, useYouthSnapshot, youthStyles as s } from './youth-ui';
import { useYouthMutation } from './youth-mutation';
import { YouthMutationActions, useYouthLeave } from './youth-write-ui';
export function YouthRulesScreen({target,category,page}:{target?:string;category?:string;page?:string}){const {token,user}=useSession();return token&&user?<Rules key={`${token}:${target}:${category}:${page}`} target={target} category={category} page={page}/>:<Redirect href="/login"/>;}
function Rules({target,category,page}:{target?:string;category?:string;page?:string}) {
 const scope=target??'all',filter=category??'all',number=youthPage(page),theme=useTheme(),valid=number!==null&&(scope==='all'||scope==='common'||youthId(scope))&&(filter==='all'||youthRuleCategories.includes(filter as typeof youthRuleCategories[number]));
 const snapshot=useYouthSnapshot(valid?`/youth/rules?target=${encodeURIComponent(scope)}&category=${encodeURIComponent(filter)}&page=${number}`:null,isYouthRules);
 const [detail,setDetail]=useState(''),[newCategory,setNewCategory]=useState<typeof youthRuleCategories[number]>(filter==='all'?'생활':filter as typeof youthRuleCategories[number]),[newTarget,setNewTarget]=useState<string|null>(scope==='all'||scope==='common'?null:scope),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[choose,setChoose]=useState(false),[search,setSearch]=useState(''),[rosterPage,setRosterPage]=useState(1);const original=useRef(''),latest=useRef<unknown>(null);
 const roster=useYouthSnapshot(choose?`/youth?q=${encodeURIComponent(search)}&page=${rosterPage}`:null,isYouthList);
 const current=()=>snapshot.current()&&snapshot.verifiedRef.current,canWrite=()=>current()&&!!snapshot.cached.current?.permissions.canManageYouth;
 const clear=()=>{setDetail('');setSearch('');setChoose(false);setNewTarget(null);latest.current=null;};
 const mutation=useYouthMutation({current:canWrite,resultGuard:isYouthActivityResult,onLoss:()=>{clear();snapshot.purge();},onSuccess:()=>{setNotice('규칙 변경이 확정되었습니다.');setDetail('');original.current='';void snapshot.load();}});
 useEffect(()=>{if(snapshot.data&&!snapshot.data.permissions.canManageYouth)clear();},[snapshot.data]);useEffect(()=>{if(snapshot.revoked)clear();},[snapshot.revoked]);
 const confirm=useYouthLeave(detail!==original.current||mutation.state!=='idle'||mutation.busy,snapshot.current,()=>mutation.busyRef.current);
 const add=async()=>{if(!canWrite()||mutation.locked)return;if(!detail.trim()||detail.trim().length>2000){setError('세부사항을 1~2000자로 입력하세요.');return;}await mutation.submit({operation:'rule.create',path:'/youth/rules',method:'POST',body:{targetYouthId:newTarget,category:newCategory,detail:detail.trim()}});};
 const remove=async(row:YouthRule)=>{if(!canWrite()||mutation.locked)return;const yes=await confirm.ask({title:'청소년 규칙 삭제',message:'선택한 규칙이 삭제됩니다.',confirm:'규칙 삭제',danger:true});if(yes&&canWrite()&&!mutation.locked)await mutation.submit({operation:'rule.delete',targetId:row.id,path:`/youth/rules/${row.id}`,method:'DELETE',body:{targetYouthId:row.targetYouthId,expectedUpdatedAt:row.updatedAt}});};
 const refresh=async()=>{await snapshot.load();if(current())latest.current=snapshot.cached.current;};
 const adopt=async()=>{const value=latest.current;if(!value||!canWrite()||snapshot.cached.current!==value)return;const yes=await confirm.ask({title:'최신 규칙 확인',message:'이전 변경 요청을 종료합니다. 내 등록 입력은 유지하며 삭제할 규칙은 최신 목록에서 다시 선택하세요.',confirm:'최신 목록 기준 선택'});if(yes&&canWrite()&&snapshot.cached.current===value&&mutation.useLatest())setError(null);};
 const params=async(p:Record<string,string>)=>{if(!current()||mutation.locked)return;const yes=detail===original.current||await confirm.ask({title:'조회 조건 변경',message:'저장하지 않은 규칙 입력이 사라집니다.',confirm:'입력 버리고 조회',danger:true});if(yes&&current()&&!mutation.busyRef.current)router.setParams(p);};
 const selectTarget=(id:string|null)=>{if(!canWrite()||mutation.locked)return;if(id&&(!roster.current()||!roster.verifiedRef.current||!roster.cached.current?.items.some(x=>x.id===id)))return;setNewTarget(id);setChoose(false);};
 return <KeyboardScreen style={[s.screen,{backgroundColor:theme.background}]}><KeyboardScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><AccountFeedback error={!valid?'규칙 조회 조건을 확인하세요.':snapshot.error||mutation.error||error} message={notice}/>{snapshot.loading?<ActivityIndicator color={theme.accent}/>:null}{snapshot.data?<><Text style={[s.small,{color:theme.secondary}]}>규칙 {snapshot.data.total.toLocaleString('ko-KR')}건 · {snapshot.data.page}/{snapshot.data.totalPages}쪽</Text><View style={s.actions}><TextAction label="전체 대상 조회" onPress={()=>void params({target:'all',page:'1'})}/><TextAction label="공통 규칙 조회" onPress={()=>void params({target:'common',page:'1'})}/><TextAction label="청소년 대상 선택" disabled={mutation.locked} onPress={()=>{if(current()&&!mutation.locked)setChoose(v=>!v);}}/></View>
 {choose?<View style={s.section}><YouthField label="대상 청소년 이름 검색" value={search} onChange={v=>{if(current()){setSearch(v);setRosterPage(1);}}}/><AccountFeedback error={roster.error}/>{roster.loading?<ActivityIndicator color={theme.accent}/>:null}{roster.data?.items.map(x=><View key={x.id} style={s.actions}><TextAction label={`${x.name} 규칙 조회`} onPress={()=>void params({target:x.id,page:'1'})}/>{canWrite()?<TextAction label={`${x.name} 등록 대상 선택`} onPress={()=>selectTarget(x.id)}/>:null}</View>)}{roster.data?<View style={s.actions}><TextAction label="이전 청소년" disabled={roster.data.page<=1} onPress={()=>{if(roster.current())setRosterPage(v=>v-1);}}/><TextAction label="다음 청소년" disabled={roster.data.page>=roster.data.totalPages} onPress={()=>{if(roster.current())setRosterPage(v=>v+1);}}/></View>:null}</View>:null}
 <View style={s.actions}>{['all',...youthRuleCategories].map(c=><TextAction key={c} label={(c===filter?'선택 · ':'')+(c==='all'?'전체 분류':c)} onPress={()=>void params({category:c,page:'1'})}/>)}</View><View accessibilityRole="list" accessibilityLabel="청소년 규칙">{snapshot.data.rules.map(row=><View key={row.id} role="listitem" style={s.section}><Text style={[s.small,{color:theme.secondary}]}>{row.targetYouthName||'공통'} · {row.category}</Text><Text selectable style={[s.body,{color:theme.text}]}>{row.detail}</Text>{canWrite()?<TextAction label={`${row.detail.slice(0,40)} 규칙 삭제`} disabled={mutation.locked} onPress={()=>void remove(row)}/>:null}</View>)}</View>{snapshot.data.total===0?<Text style={[s.body,{color:theme.secondary}]}>해당 규칙이 없습니다.</Text>:null}<View style={s.actions}><TextAction label="이전 규칙" disabled={snapshot.data.page<=1} onPress={()=>void params({page:String(snapshot.data!.page-1)})}/><TextAction label="다음 규칙" disabled={snapshot.data.page>=snapshot.data.totalPages} onPress={()=>void params({page:String(snapshot.data!.page+1)})}/></View>
 {canWrite()?<View style={s.section}><Text accessibilityRole="header" aria-level={2} style={[s.heading,{color:theme.text}]}>규칙 등록</Text><Text style={[s.small,{color:theme.secondary}]}>등록 대상: {newTarget===null?'공통':roster.cached.current?.items.find(x=>x.id===newTarget)?.name??(scope===newTarget?'선택한 청소년':'선택한 청소년')}</Text><View style={s.actions}><TextAction label="공통 규칙으로 등록" disabled={mutation.locked} onPress={()=>selectTarget(null)}/><TextAction label="등록 청소년 선택" disabled={mutation.locked} onPress={()=>{if(canWrite())setChoose(true);}}/></View><View style={s.actions}>{youthRuleCategories.map(c=><TextAction key={c} label={`${newCategory===c?'선택 · ':''}${c} 분류`} disabled={mutation.locked} onPress={()=>{if(canWrite()&&!mutation.locked)setNewCategory(c);}}/>)}</View><YouthField label="규칙 세부사항" value={detail} multiline hint="2000자 이내" disabled={mutation.locked} onChange={v=>{if(canWrite()&&!mutation.locked){setDetail(v);setError(null);mutation.clearValidation();}}}/><PrimaryButton title="규칙 등록" disabled={mutation.locked} onPress={()=>void add()}/></View>:null}<TextAction label="규칙 처리 이력" disabled={mutation.locked} onPress={()=>{if(current()&&!mutation.locked)router.push(`/youth/activity-history?activity=rules&target=${encodeURIComponent(scope)}&category=${encodeURIComponent(filter)}` as never);}}/></>:!snapshot.loading?<Text style={[s.body,{color:theme.secondary}]}>규칙을 확인할 수 없습니다.</Text>:null}<YouthMutationActions mutation={mutation} onRefresh={refresh} onAdopt={()=>void adopt()}/><TextAction label="규칙 다시 확인" onPress={()=>void snapshot.load()}/>{confirm.dialog}</KeyboardScrollView></KeyboardScreen>;
}
