/* Privacy guards and immutable mutation baselines deliberately use synchronous refs; permission changes must clear local state before user actions can resume. */
/* eslint-disable react-hooks/refs, react-hooks/set-state-in-effect */
import { useEffect, useRef, useState } from 'react';
import { Redirect, router } from 'expo-router';
import { ActivityIndicator, ScrollView, Text, View } from 'react-native';
import { useSession } from '@/lib/session';
import { useTheme } from '@/lib/theme';
import { youthId } from '@/lib/youth';
import { isYouthActivityResult, isYouthConceptList, isYouthLearning } from '@/lib/youth-activities';
import type { YouthConceptList, YouthLearning } from '@/types/youth';
import { AccountFeedback } from './account-feedback';
import { PrimaryButton, TextAction } from './ui';
import { YouthField, YouthRow, useYouthSnapshot, youthStyles as s } from './youth-ui';
import { useYouthMutation } from './youth-mutation';
import { YouthMutationActions, useYouthLeave } from './youth-write-ui';
export function YouthLearningScreen({id,subunitId}:{id?:string;subunitId?:string}){const {token,user}=useSession();return token&&user?<Learning key={`${token}:${id}:${subunitId}`} id={id} subunitId={subunitId}/>:<Redirect href="/login"/>;}
function Learning({id,subunitId}:{id?:string;subunitId?:string}) {
 const theme=useTheme(),valid=(id===undefined||youthId(id))&&(subunitId===undefined||youthId(subunitId)),path=id?`/youth/${id}/learning`:'/youth/study-concepts';
 const snapshot=useYouthSnapshot<YouthLearning|YouthConceptList>(valid?`${path}?subject=math${subunitId?'&subunitId='+encodeURIComponent(subunitId):''}`:null,(v):v is YouthLearning|YouthConceptList=>id?isYouthLearning(v,id):isYouthConceptList(v));
 const [content,setContent]=useState(''),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[choose,setChoose]=useState(false),[baselineConfirmed,setBaselineConfirmed]=useState(false);const original=useRef(''),latest=useRef<YouthLearning|YouthConceptList|null>(null);
 const current=()=>snapshot.current()&&snapshot.verifiedRef.current,canWrite=()=>current()&&!!snapshot.cached.current?.permissions.canManageYouth;
 const clear=()=>{setContent('');latest.current=null;setChoose(false);};
 const mutation=useYouthMutation({current:canWrite,resultGuard:isYouthActivityResult,onLoss:()=>{clear();snapshot.purge();},onSuccess:()=>{original.current=content;setNotice('수학 개념 변경이 확정되었습니다.');setContent('');original.current='';setBaselineConfirmed(false);void snapshot.load();}});
 useEffect(()=>{if(snapshot.data&&!snapshot.data.permissions.canManageYouth)clear();},[snapshot.data]);useEffect(()=>{if(snapshot.revoked)clear();},[snapshot.revoked]);
 const confirm=useYouthLeave(content!==original.current||mutation.busy||mutation.state!=='idle',snapshot.current,()=>mutation.busyRef.current);
 const change=(value:string)=>{if(canWrite()&&!mutation.locked){setContent(value);setError(null);mutation.clearValidation();}};
 const add=async()=>{if(!canWrite()||mutation.locked||!snapshot.data)return;if(!content.trim()||content.trim().length>200){setError('개념 내용을 1~200자로 입력하세요.');return;}await mutation.submit({operation:'concept.create',path:'/youth/study-concepts',method:'POST',body:{subject:'math',subunitId:snapshot.data.subunitId,content:content.trim()}});};
 const check=async(concept:YouthLearning['concepts'][number])=>{const data=snapshot.cached.current;if(!canWrite()||mutation.locked||!id||!data||!('youthUpdatedAt'in data))return;await mutation.submit({operation:'concept.check',targetId:concept.id,path:`/youth/${id}/learning/checks/${concept.id}`,method:'PUT',body:{checked:!concept.checked,expectedYouthUpdatedAt:data.youthUpdatedAt,expectedConceptUpdatedAt:concept.updatedAt}});};
 const remove=async(concept:{id:string;content:string;updatedAt:string})=>{if(!canWrite()||mutation.locked)return;const yes=await confirm.ask({title:'공용 개념 삭제',message:'이 개념과 모든 청소년의 해당 숙지 체크가 삭제됩니다.',confirm:'공용 개념 삭제',danger:true});if(yes&&canWrite()&&!mutation.locked)await mutation.submit({operation:'concept.delete',targetId:concept.id,path:`/youth/study-concepts/${concept.id}`,method:'DELETE',body:{expectedUpdatedAt:concept.updatedAt}});};
 const refresh=async()=>{await snapshot.load();if(current())latest.current=snapshot.cached.current;};
 const adopt=async()=>{const data=latest.current;if(!data||!canWrite()||snapshot.cached.current!==data)return;const yes=await confirm.ask({title:'최신 학습 기준',message:'변경된 개념과 숙지 상태를 확인했습니다. 이전 요청을 종료하고 다음 명시 변경부터 최신 기준을 사용합니다.',confirm:'최신 기준 선택'});if(yes&&canWrite()&&snapshot.cached.current===data&&mutation.useLatest()){setBaselineConfirmed(true);setError(null);}};
 const navigate=async(unit:string)=>{if(!current()||mutation.locked)return;const yes=content===original.current||await confirm.ask({title:'다른 단원 조회',message:'저장하지 않은 개념 입력이 사라집니다.',confirm:'입력 버리고 이동',danger:true});if(yes&&current()&&!mutation.busyRef.current)router.setParams({subunitId:unit});};
 return <ScrollView style={[s.screen,{backgroundColor:theme.background}]} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><AccountFeedback error={!valid?'청소년과 단원을 확인하세요.':snapshot.error||mutation.error||error} message={notice}/>{snapshot.loading?<ActivityIndicator color={theme.accent}/>:null}{snapshot.data?<><Text accessibilityRole="header" aria-level={2} style={[s.heading,{color:theme.text}]}>{'youth'in snapshot.data?snapshot.data.youth.name+' 수학 숙지':'공용 수학 개념'}</Text><Text style={[s.small,{color:theme.secondary}]}>{snapshot.data.curriculum.flatMap(x=>x.units.flatMap(u=>u.subunits)).find(x=>x.id===snapshot.data!.subunitId)?.label??snapshot.data.subunitId} · 개념 {snapshot.data.concepts.length}개{'youth'in snapshot.data?' · 숙지 '+snapshot.data.concepts.filter(x=>'checked'in x&&x.checked).length+'개':''}</Text><TextAction label="수학 단원 선택" disabled={mutation.locked} onPress={()=>{if(current()&&!mutation.locked)setChoose(v=>!v);}}/>{choose?<View style={s.section}>{snapshot.data.curriculum.map(semester=><View key={semester.id}><Text style={[s.body,{color:theme.text}]}>{semester.label}</Text>{semester.units.map(unit=><View key={unit.id}><Text style={[s.small,{color:theme.secondary}]}>{unit.label}</Text>{unit.subunits.map(x=><TextAction key={x.id} label={x.label} disabled={mutation.locked} onPress={()=>void navigate(x.id)}/>)}</View>)}</View>)}</View>:null}
 <View accessibilityRole="list" accessibilityLabel="수학 개념">{snapshot.data.concepts.map(concept=><View key={concept.id} role="listitem"><YouthRow title={concept.content} detail={'checked'in concept?(concept.checked?'숙지 완료':'미숙지'):'공용 개념'} disabled={!snapshot.data?.permissions.canManageYouth||mutation.locked||!id} onPress={()=>{if('checked'in concept)void check(concept);}}/>{snapshot.data?.permissions.canManageYouth?<TextAction label={`${concept.content.slice(0,50)} 개념 삭제`} disabled={mutation.locked} onPress={()=>void remove(concept)}/>:null}</View>)}</View>
 {snapshot.data.permissions.canManageYouth?<><YouthField label="새 공용 수학 개념" hint="200자 이내 · 모든 청소년이 사용하는 개념" value={content} disabled={mutation.locked} onChange={change}/><PrimaryButton title="공용 개념 등록" disabled={mutation.locked} onPress={()=>void add()}/></>:null}{baselineConfirmed?<Text style={[s.small,{color:theme.secondary}]}>최신 기준을 선택했습니다. 변경할 개념을 다시 선택하세요.</Text>:null}{id?<TextAction label="수학 처리 이력" disabled={mutation.locked} onPress={()=>{if(current()&&!mutation.locked)router.push(`/youth/activity-history?activity=learning&id=${id}&subunitId=${snapshot.data!.subunitId}` as never);}}/>:null}</>:!snapshot.loading?<Text style={[s.body,{color:theme.secondary}]}>수학 개념을 확인할 수 없습니다.</Text>:null}<YouthMutationActions mutation={mutation} onRefresh={refresh} onAdopt={()=>void adopt()}/><TextAction label="수학 개념 다시 확인" onPress={()=>void snapshot.load()}/>{confirm.dialog}</ScrollView>;
}
