/* Scope cleanup effects intentionally depend on the permission snapshot or token; render-created action callbacks would retrigger them and discard dirty input. */
/* eslint-disable react-hooks/exhaustive-deps */
/* Privacy guards and immutable mutation baselines deliberately use synchronous refs; permission changes must clear local state before user actions can resume. */
/* eslint-disable react-hooks/refs */
import { useEffect, useRef, useState } from 'react';
import { Text, View } from 'react-native';
import { useSession } from '@/lib/session';
import { useTheme } from '@/lib/theme';
import { newYouthRequestId } from '@/lib/youth';
import { isYouthDecisionPolicy } from '@/lib/youth-file-core';
import { createYouthDecisionUpload, discardYouthDecisionFile, purgeYouthDecisionFile, isYouthFileCancellation, pickYouthDecisionFile, youthFileSize, type SelectedYouthFile, type YouthUploadOperation } from '@/lib/youth-file-transfer';
import { registerYouthResource } from '@/lib/youth-privacy';
import { useYouth } from './youth-provider';
import { TextAction } from './ui';
import { useConfirmAction } from './use-confirm-action';
import { AccountFeedback } from './account-feedback';
import { youthStyles as s } from './youth-ui';
type Entry={key:string;file:SelectedYouthFile;operation:YouthUploadOperation;progress:number|null};
export function useYouthUploads({targetYouthId,current,scopeCurrent}:{targetYouthId:string|null;current:()=>boolean;scopeCurrent:()=>boolean}){
 const {token,expireSession}=useSession(),{request}=useYouth(),[files,setFiles]=useState<Entry[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);const entries=useRef<Entry[]>([]),lock=useRef(false),alive=useRef(false),epoch=useRef(0),callbacks=useRef({current,scopeCurrent});callbacks.current={current,scopeCurrent};
 const handoff=useRef(false),confirmation=useConfirmAction();const fileCurrent=()=>alive.current&&callbacks.current.scopeCurrent()&&(callbacks.current.current()||handoff.current);
 const clear=()=>{epoch.current++;lock.current=false;setBusy(false);for(const entry of entries.current){entry.operation.cancel();try{purgeYouthDecisionFile(entry.file,{token:token??'',isCurrent:()=>alive.current&&callbacks.current.scopeCurrent()});}catch{entry.operation.release();}}entries.current=[];setFiles([]);};
 useEffect(()=>{alive.current=true;epoch.current++;const off=token?registerYouthResource(token,clear):()=>{};return()=>{alive.current=false;epoch.current++;off();for(const entry of entries.current)entry.operation.release();};},[token]);
 const fail=(cause:unknown)=>{if(cause instanceof Error&&!isYouthFileCancellation(cause))setError(cause.message);if(cause instanceof Error&&'status'in cause&&cause.status===401&&token)void expireSession(token);};
 const pick=async()=>{if(!token||lock.current||!callbacks.current.current()||entries.current.length>=5)return;lock.current=true;setBusy(true);setError(null);const generation=epoch.current;let selected:SelectedYouthFile|null=null;try{const value=await request<unknown>('/youth/document-upload-policy');if(!isYouthDecisionPolicy(value))throw new Error('결정문 첨부 정책을 확인하지 못했습니다.');if(generation!==epoch.current||!callbacks.current.current())return;handoff.current=true;selected=await pickYouthDecisionFile({token,policy:value,isCurrent:fileCurrent});if(!selected)return;if(generation!==epoch.current||!fileCurrent()){selected.release();return;}const key=newYouthRequestId(),entry:Entry={key,file:selected,operation:createYouthDecisionUpload({file:selected,token,targetYouthId,requestId:key,isCurrent:fileCurrent,onProgress:fraction=>{if(generation===epoch.current&&fileCurrent()){entry.progress=fraction;setFiles([...entries.current]);}}}),progress:null};entries.current=[...entries.current,entry];setFiles(entries.current);selected=null;}catch(cause){if(generation===epoch.current&&fileCurrent())fail(cause);}finally{selected?.release();handoff.current=false;if(generation===epoch.current){lock.current=false;setBusy(false);}}};
 const run=async(entry:Entry,action:'prepare'|'refresh')=>{if(lock.current||!callbacks.current.current()||!entries.current.includes(entry))return;lock.current=true;setBusy(true);setError(null);const generation=epoch.current;try{await entry.operation[action]();}catch(cause){if(generation===epoch.current&&callbacks.current.scopeCurrent())fail(cause);}finally{if(generation===epoch.current){setFiles([...entries.current]);lock.current=false;setBusy(false);}}};
 const remove=async(entry:Entry)=>{if(lock.current||!callbacks.current.current()||!entries.current.includes(entry))return;const yes=await confirmation.ask({title:'선택한 결정문 제거',message:'선택한 앱 사본과 미등록 업로드를 제거합니다. 기기의 원본은 보존합니다. 불명확한 청소년 저장이 있다면 먼저 그 결과를 확인하세요.',confirm:'선택 파일 제거',danger:true});if(!yes||lock.current||!callbacks.current.current()||!entries.current.includes(entry))return;lock.current=true;setBusy(true);const generation=epoch.current;try{if(entry.operation.getState().phase==='selected')discardYouthDecisionFile(entry.file,{token:token!,isCurrent:fileCurrent});else await entry.operation.discard();if(generation===epoch.current&&fileCurrent()){entries.current=entries.current.filter(x=>x!==entry);setFiles(entries.current);}}catch(cause){if(generation===epoch.current&&callbacks.current.scopeCurrent())fail(cause);}finally{if(generation===epoch.current){lock.current=false;setBusy(false);}}};
 return{files,busy,error,pick,run,remove,clear,dialog:confirmation.dialog,busyRef:lock,readyIds:()=>entries.current.map(x=>x.operation.readyUploadId()),count:()=>entries.current.length};
}
export function YouthFilesEditor({uploads,disabled=false}:{uploads:ReturnType<typeof useYouthUploads>;disabled?:boolean}){const theme=useTheme();return <View style={s.section}><Text accessibilityRole="header" aria-level={2} style={[s.heading,{color:theme.text}]}>새 결정문 첨부</Text><Text style={[s.small,{color:theme.secondary}]}>새 파일 최대 5개 · 파일당 30MB. 업로드 결과가 준비 완료인 파일만 등록합니다.</Text><AccountFeedback error={uploads.error}/>{uploads.files.map(entry=><View key={entry.key}><Text style={[s.body,{color:theme.text}]}>{entry.file.name} · {youthFileSize(entry.file.size)}</Text><Text style={[s.small,{color:theme.secondary}]}>{phaseLabel(entry.operation.getState().phase)}{entry.progress===null?'':` · ${Math.round(entry.progress*100)}%`}</Text><View style={s.actions}><TextAction label={`${entry.file.name} 업로드 준비`} disabled={disabled||uploads.busy} onPress={()=>void uploads.run(entry,'prepare')}/><TextAction label={`${entry.file.name} 같은 업로드 결과 확인`} disabled={disabled||uploads.busy} onPress={()=>void uploads.run(entry,'refresh')}/><TextAction label={`${entry.file.name} 선택 제거`} disabled={disabled||uploads.busy} onPress={()=>void uploads.remove(entry)}/></View></View>)}<TextAction label="결정문 파일 선택" disabled={disabled||uploads.busy||uploads.files.length>=5} onPress={()=>void uploads.pick()}/>{uploads.dialog}</View>;}
function phaseLabel(phase:string){return ({selected:'선택됨',hashing:'파일 검증 중',uploading:'전송 결과 확인 필요',finalizing:'서버 확인 중',ready:'준비 완료',consumed:'등록됨',deleting:'제거 처리 중',expired:'만료됨',deleted:'제거됨',purged:'사용할 수 없음'} as Record<string,string>)[phase]??'결과 확인 필요';}
