import { KeyboardScrollView } from "@/components/keyboard-scroll-view";
import { KeyboardScreen } from "@/components/keyboard-screen";
/* Privacy guards and immutable mutation baselines deliberately use synchronous refs; permission changes must clear local state before user actions can resume. */
/* eslint-disable react-hooks/refs */
import { useEffect, useRef, useState } from 'react';
import { Redirect } from 'expo-router';
import { ActivityIndicator, Platform, Text, View } from 'react-native';
import { useSession } from '@/lib/session';
import { useTheme } from '@/lib/theme';
import { isYouthDocuments, newYouthRequestId, youthId } from '@/lib/youth';
import { createYouthDecisionTransfer, isYouthFileCancellation, youthFileSize, type YouthDecisionTransfer } from '@/lib/youth-file-transfer';
import { AccountFeedback } from './account-feedback';
import { TextAction } from './ui';
import { YouthField, useYouthSnapshot, youthStyles as s } from './youth-ui';
const reasons=[['CASE_SUPPORT','사건 지원 업무'],['EXTERNAL_SUBMISSION','외부기관 제출'],['INTERNAL_REVIEW','기관 내부 검토'],['OTHER','기타']] as const;
export function YouthDecisionScreen({id,youthId:parent}:{id:string;youthId:string}){const {token,user}=useSession();return token&&user?<Decision key={`${token}:${parent}:${id}`} id={id} parent={parent}/>:<Redirect href="/login"/>;}
function Decision({id,parent}:{id:string;parent:string}) {
 const {token,expireSession}=useSession(),theme=useTheme(),valid=youthId(id)&&youthId(parent),snapshot=useYouthSnapshot(valid?`/youth/${parent}/documents`:null,(v):v is import('@/types/youth').YouthDocuments=>isYouthDocuments(v,parent));
 const [reason,setReason]=useState<typeof reasons[number][0]|null>(null),[detail,setDetail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[ready,setReady]=useState(false),[progress,setProgress]=useState<number|null>(null);const operation=useRef<YouthDecisionTransfer|null>(null),lock=useRef(false),handoff=useRef(false),epoch=useRef(0);const document=snapshot.data?.documents.find(x=>x.id===id),baseline=useRef<string|null>(null),attempt=useRef<{requestId:string;reason:typeof reasons[number][0];reasonDetail?:string}|null>(null);
 const current=()=>snapshot.current()&&snapshot.verifiedRef.current&&!!snapshot.cached.current?.permissions.canDownloadYouthDocuments;
 const fileCurrent=()=>snapshot.accountCurrent()&&(current()||handoff.current);
 const release=()=>{epoch.current++;operation.current?.cancel();operation.current?.release();operation.current=null;baseline.current=null;lock.current=false;setBusy(false);setReady(false);setProgress(null);};
 useEffect(()=>{if(!snapshot.data&&!handoff.current)release();if(snapshot.data){const item=snapshot.data.documents.find(x=>x.id===id);if(!item||baseline.current&&baseline.current!==item.updatedAt)release();}},[snapshot.data,id]);useEffect(()=>()=>{operation.current?.cancel();operation.current?.release();epoch.current++;},[]);
 const run=async(action:'download'|'save'|'share')=>{if(!token||!document||!current()||lock.current)return;if(action==='download'&&!reason){setError('다운로드 사유를 선택하세요.');return;}if(reason==='OTHER'&&(!detail.trim()||detail.trim().length>200)){setError('기타 사유를 1~200자로 입력하세요.');return;}lock.current=true;setBusy(true);setError(null);const generation=epoch.current;try{if(!operation.current){if(!attempt.current)attempt.current={requestId:newYouthRequestId(),reason:reason!,...(reason==='OTHER'?{reasonDetail:detail.trim()}:{} )};operation.current=createYouthDecisionTransfer({document,...attempt.current,token,isCurrent:fileCurrent,onProgress:f=>{if(generation===epoch.current&&fileCurrent())setProgress(f);}});baseline.current=document.updatedAt;}if(action==='download'){const done=await operation.current.download();if(generation===epoch.current&&current())setReady(done);}else{handoff.current=true;const message=await operation.current[action]();if(generation===epoch.current&&fileCurrent())setNotice(message);}}catch(cause){if(generation===epoch.current&&snapshot.accountCurrent()&&!isYouthFileCancellation(cause)){setError(cause instanceof Error?cause.message:'같은 다운로드 요청으로 다시 확인하세요.');if(cause instanceof Error&&'status'in cause){if(cause.status===401)void expireSession(token);if([403,404,409,410].includes(Number(cause.status))){release();attempt.current=null;setReason(null);setDetail('');}}}}finally{handoff.current=false;if(generation===epoch.current){lock.current=false;setBusy(false);}}};
 return <KeyboardScreen style={[s.screen,{backgroundColor:theme.background}]}><KeyboardScrollView contentContainerStyle={s.content}><AccountFeedback error={!valid?'청소년과 결정문 식별자를 확인하세요.':snapshot.error||error} message={notice}/>{snapshot.loading?<ActivityIndicator color={theme.accent}/>:null}{document?<><Text accessibilityRole="header" aria-level={2} style={[s.heading,{color:theme.text}]}>{document.name}</Text><Text style={[s.small,{color:theme.secondary}]}>{youthFileSize(document.size)} · 다운로드 사유가 감사 기록에 남습니다.</Text><View style={s.actions}>{reasons.map(([value,label])=><TextAction key={value} label={`${reason===value?'선택 · ':''}${label}`} disabled={busy||attempt.current!==null} onPress={()=>{if(current()&&!lock.current&&!attempt.current)setReason(value);}}/>)}</View>{reason==='OTHER'?<YouthField label="기타 다운로드 사유" value={detail} hint="200자 이내" disabled={busy||attempt.current!==null} onChange={v=>{if(current()&&!lock.current&&!attempt.current)setDetail(v);}}/>:null}<TextAction label={operation.current?'같은 사유·요청으로 다시 내려받기':'사유 기록하고 결정문 내려받기'} disabled={busy} onPress={()=>void run('download')}/>{progress===null?null:<Text style={[s.small,{color:theme.secondary}]}>{Math.round(progress*100)}%</Text>}{ready?<View style={s.actions}><TextAction label="결정문 파일 저장" disabled={busy} onPress={()=>void run('save')}/>{Platform.OS!=='web'?<TextAction label="결정문 공유" disabled={busy} onPress={()=>void run('share')}/>:null}</View>:null}</>:!snapshot.loading?<Text style={[s.body,{color:theme.secondary}]}>현재 결정문을 확인할 수 없습니다.</Text>:null}<TextAction label="결정문 권한 다시 확인" disabled={busy} onPress={()=>void snapshot.load()}/></KeyboardScrollView></KeyboardScreen>;
}
