ALTER TYPE "AuditAction" ADD VALUE 'CREATE_QUESTION_BANK_UNIT';
ALTER TYPE "AuditAction" ADD VALUE 'CREATE_QUESTION_BANK_PROBLEM';
ALTER TYPE "AuditAction" ADD VALUE 'UPLOAD_QUESTION_BANK_PDF';
ALTER TYPE "AuditAction" ADD VALUE 'DELETE_QUESTION_BANK_PDF';
ALTER TYPE "AuditAction" ADD VALUE 'CREATE_WORK_FEATURE_UPDATE';
