-- Harden Supabase-exposed public tables.
--
-- The app accesses these tables through the server-side Prisma connection.
-- Do not FORCE RLS here: the database owner used by Prisma must keep working,
-- while Supabase anon/authenticated API roles should not get direct table access.

ALTER TABLE IF EXISTS public."_prisma_migrations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Department" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Position" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."DocumentTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."AttachmentPolicy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."CompanyBusinessInfo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ApprovalDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ApprovalStep" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ApprovalComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Attachment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ResourcePost" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ResourceAttachment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."ResourcePostView" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Youth" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."YouthRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."YouthFamilyContact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."YouthSpecialNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."YouthLearningSchedule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."YouthCommonSchedule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."WorkSchedule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."WorkFeatureUpdate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."CafeItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."LoginHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."StaffLeaveLedger" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."Notification" ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  api_role text;
BEGIN
  FOREACH api_role IN ARRAY ARRAY['anon', 'authenticated']
  LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = api_role) THEN
      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I', api_role);
      EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I', api_role);
      EXECUTE format('REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM %I', api_role);

      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM %I', api_role);
      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I', api_role);
      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM %I', api_role);
    END IF;
  END LOOP;
END $$;
