import { isYouthBasic, isYouthDate, isYouthPermissions, isYouthTimestamp, youthDateOrNull, youthExact, youthId, youthInteger, youthNullableText, youthRecord, youthText } from './youth';
import type { YouthActivityHistory, YouthCommonList, YouthCommonSchedule, YouthConcept, YouthConceptList, YouthCurriculum, YouthLearning, YouthPersonalDetail, YouthPersonalList, YouthPersonalSchedule, YouthRule, YouthRules } from '../types/youth';
export const youthRuleCategories=['생활','학습','외출/외박','안전','상담','기타'] as const;
export const youthWeekdays=['일','월','화','수','목','금','토'];
export function youthTime(value:number){return `${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`;}
export function youthMinute(value:string,end=false){if(!/^\d{2}:\d{2}$/.test(value))return null;const [h,m]=value.split(':').map(Number),v=h*60+m;return m<60&&m%10===0&&v>=0&&v<=(end?1440:1430)?v:null;}
function dates(v:unknown){return Array.isArray(v)&&v.every(isYouthDate)&&new Set(v).size===v.length;}
function minute(v:unknown,end=false):v is number{return youthInteger(v)&&v<=(end?1440:1430)&&v%10===0;}
function base(v:Record<string,unknown>){return isYouthDate(v.today)&&isYouthPermissions(v.permissions);}
function staff(v:unknown){return Array.isArray(v)&&v.every(x=>youthRecord(x)&&youthExact(x,['id','name'])&&youthId(x.id)&&youthText(x.name));}
export function isYouthPersonal(v:unknown):v is YouthPersonalSchedule{return youthRecord(v)&&youthExact(v,['id','youthId','content','scheduleType','hospitalName','escortType','escortUserId','escortName','nextAppointmentDate','startMinute','endMinute','selectionMode','occurrenceDates','recurrenceWeekdays','recurrenceStartDate','recurrenceEndDate','updatedAt'])&&youthId(v.id)&&youthId(v.youthId)&&youthText(v.content)&&['GENERAL','HOSPITAL'].includes(String(v.scheduleType))&&youthNullableText(v.hospitalName)&&[null,'STAFF','OTHER'].includes(v.escortType as null|string)&&(v.escortUserId===null||youthId(v.escortUserId))&&youthNullableText(v.escortName)&&youthDateOrNull(v.nextAppointmentDate)&&minute(v.startMinute)&&minute(v.endMinute,true)&&Number(v.endMinute)>Number(v.startMinute)&&['DATES','WEEKDAYS'].includes(String(v.selectionMode))&&dates(v.occurrenceDates)&&Array.isArray(v.recurrenceWeekdays)&&v.recurrenceWeekdays.every(d=>youthInteger(d)&&d<=6)&&youthDateOrNull(v.recurrenceStartDate)&&youthDateOrNull(v.recurrenceEndDate)&&isYouthTimestamp(v.updatedAt);}
export function isYouthPersonalList(v:unknown,id:string):v is YouthPersonalList{return youthRecord(v)&&youthExact(v,['today','permissions','youth','month','date','schedules','staffOptions'])&&base(v)&&isYouthBasic(v.youth)&&v.youth.id===id&&isYouthDate(v.date)&&v.month===v.date.slice(0,7)&&Array.isArray(v.schedules)&&v.schedules.every(s=>isYouthPersonal(s)&&s.youthId===id)&&staff(v.staffOptions)&&(!isYouthPermissions(v.permissions)||v.permissions.canManageYouth||(v.staffOptions as unknown[]).length===0);}
export function isYouthPersonalDetail(v:unknown,id:string,parent:string):v is YouthPersonalDetail{return youthRecord(v)&&youthExact(v,['today','permissions','youth','schedule','staffOptions'])&&base(v)&&isYouthBasic(v.youth)&&v.youth.id===parent&&isYouthPersonal(v.schedule)&&v.schedule.id===id&&v.schedule.youthId===parent&&staff(v.staffOptions);}
export function isYouthCommon(v:unknown):v is YouthCommonSchedule{return youthRecord(v)&&youthExact(v,['id','weekday','startHour','startMinute','endHour','endMinute','content','updatedAt'])&&youthId(v.id)&&youthInteger(v.weekday)&&v.weekday>=1&&v.weekday<=5&&youthInteger(v.startHour)&&v.startHour<=24&&youthInteger(v.endHour)&&v.endHour<=24&&minute(v.startMinute)&&v.startMinute>=540&&minute(v.endMinute,true)&&v.endMinute<=1320&&v.endMinute>v.startMinute&&youthText(v.content)&&isYouthTimestamp(v.updatedAt);}

export function isYouthCommonList(v:unknown):v is YouthCommonList{return youthRecord(v)&&youthExact(v,['today','permissions','weekday','items'])&&base(v)&&youthInteger(v.weekday)&&v.weekday>=1&&v.weekday<=5&&Array.isArray(v.items)&&v.items.every(x=>isYouthCommon(x)&&x.weekday===v.weekday);}
export function isYouthCurriculum(v:unknown):v is YouthCurriculum{return Array.isArray(v)&&v.every(s=>youthRecord(s)&&youthExact(s,['id','label','units'])&&youthId(s.id)&&youthText(s.label)&&Array.isArray(s.units)&&s.units.every(u=>youthRecord(u)&&youthExact(u,['id','label','subunits'])&&youthId(u.id)&&youthText(u.label)&&Array.isArray(u.subunits)&&u.subunits.every(x=>youthRecord(x)&&youthExact(x,['id','label'])&&youthId(x.id)&&youthText(x.label))));}
export function isYouthConcept(v:unknown):v is YouthConcept{return youthRecord(v)&&youthExact(v,['id','subject','subunitId','content','updatedAt'])&&youthId(v.id)&&v.subject==='math'&&youthId(v.subunitId)&&youthText(v.content)&&isYouthTimestamp(v.updatedAt);}
export function isYouthConceptList(v:unknown):v is YouthConceptList{return youthRecord(v)&&youthExact(v,['today','permissions','subject','subunitId','curriculum','concepts'])&&base(v)&&v.subject==='math'&&youthId(v.subunitId)&&isYouthCurriculum(v.curriculum)&&Array.isArray(v.concepts)&&v.concepts.every(x=>isYouthConcept(x)&&x.subunitId===v.subunitId);}
export function isYouthLearning(v:unknown,id:string):v is YouthLearning{return youthRecord(v)&&youthExact(v,['today','permissions','youth','subject','subunitId','curriculum','concepts','youthUpdatedAt'])&&base(v)&&isYouthBasic(v.youth)&&v.youth.id===id&&v.subject==='math'&&youthId(v.subunitId)&&isYouthCurriculum(v.curriculum)&&isYouthTimestamp(v.youthUpdatedAt)&&v.youth.updatedAt===v.youthUpdatedAt&&Array.isArray(v.concepts)&&v.concepts.every(x=>youthRecord(x)&&youthExact(x,['id','content','updatedAt','checked','checkedAt'])&&youthId(x.id)&&youthText(x.content)&&isYouthTimestamp(x.updatedAt)&&typeof x.checked==='boolean'&&(x.checkedAt===null||isYouthTimestamp(x.checkedAt))&&x.checked===(x.checkedAt!==null));}
export function isYouthRule(v:unknown):v is YouthRule{return youthRecord(v)&&youthExact(v,['id','category','detail','targetYouthId','targetYouthName','createdAt','updatedAt'])&&youthId(v.id)&&youthRuleCategories.includes(v.category as typeof youthRuleCategories[number])&&youthText(v.detail)&&(v.targetYouthId===null||youthId(v.targetYouthId))&&youthNullableText(v.targetYouthName)&&isYouthTimestamp(v.createdAt)&&isYouthTimestamp(v.updatedAt);}
function pages(v:Record<string,unknown>,rows:unknown[]){return youthInteger(v.total)&&youthInteger(v.totalPages)&&v.totalPages===Math.max(1,Math.ceil(v.total/10))&&youthInteger(v.page)&&v.page>=1&&v.page<=v.totalPages&&v.pageSize===10&&rows.length===Math.min(10,v.total-(v.page-1)*10);}
export function isYouthRules(v:unknown):v is YouthRules{return youthRecord(v)&&youthExact(v,['today','permissions','target','category','rules','page','pageSize','total','totalPages'])&&base(v)&&youthText(v.target)&&(['all','common'].includes(v.target)||youthId(v.target))&&youthText(v.category)&&(v.category==='all'||youthRuleCategories.includes(v.category as typeof youthRuleCategories[number]))&&Array.isArray(v.rules)&&v.rules.every(isYouthRule)&&pages(v,v.rules);}
export function isYouthActivityHistory(v:unknown):v is YouthActivityHistory{return youthRecord(v)&&youthExact(v,['today','permissions','page','pageSize','total','totalPages','logs'])&&base(v)&&Array.isArray(v.logs)&&pages(v,v.logs)&&v.logs.every(x=>youthRecord(x)&&youthExact(x,['id','createdAt','actorName','changeType','message','changes'])&&youthId(x.id)&&isYouthTimestamp(x.createdAt)&&youthText(x.actorName)&&youthNullableText(x.changeType)&&youthNullableText(x.message)&&Array.isArray(x.changes)&&x.changes.every(c=>youthRecord(c)&&youthExact(c,['field','label','before','after'])&&youthText(c.field)&&youthText(c.label)&&youthNullableText(c.before)&&youthNullableText(c.after)));}
/** Allow only one of the domain's public result shapes, never a raw audit record. */
export function isYouthActivityResult(v:unknown):v is Record<string,unknown>{if(!youthRecord(v))return false;
 if(youthExact(v,['youth','schedule']))return isYouthBasic(v.youth)&&isYouthPersonal(v.schedule)&&v.schedule.youthId===v.youth.id;
 if(youthExact(v,['youth','scheduleId']))return isYouthBasic(v.youth)&&youthId(v.scheduleId);
 if(youthExact(v,['items','targetWeekdays']))return Array.isArray(v.items)&&v.items.every(isYouthCommon)&&Array.isArray(v.targetWeekdays)&&v.targetWeekdays.every(d=>youthInteger(d)&&d>=1&&d<=5);
 if(youthExact(v,['concept']))return isYouthConcept(v.concept);
 if(youthExact(v,['rule']))return isYouthRule(v.rule);
 if(youthExact(v,['conceptId','youthId','checked','checkedAt','youthUpdatedAt','conceptUpdatedAt']))return youthId(v.conceptId)&&youthId(v.youthId)&&typeof v.checked==='boolean'&&(v.checkedAt===null||isYouthTimestamp(v.checkedAt))&&v.checked===(v.checkedAt!==null)&&isYouthTimestamp(v.youthUpdatedAt)&&isYouthTimestamp(v.conceptUpdatedAt);
 return ['scheduleId','conceptId','ruleId'].some(k=>youthExact(v,[k])&&youthId(v[k]));
}
