import { ApiError } from './api';
import { attachmentFileSize, isAttachmentTransferCancellation } from './attachment-file';
import { resourceBinaryError, resourceDownloadInfo, type ResourceFileAdapter, type ResourceFileCall, type ResourceFilePickOptions, type ResourceFileInfo } from './resource-file-core';
import { registerYouthResource, youthPrivacyGeneration } from './youth-privacy';
import { youthRequest } from './youth-request';
import { isYouthTimestamp, youthExact, youthId, youthInteger, youthRecord, youthText } from './youth';
import type { YouthDocument } from '../types/youth';
export { resourceBinaryError as youthBinaryError, resourceDownloadInfo as youthDownloadInfo };
export const youthFileSize=attachmentFileSize;
export const isYouthFileCancellation=isAttachmentTransferCancellation;
export type YouthDecisionPolicy={maxNewFileCount:5;maxFileSize:31457280;allowedExtensions:string[]};
export type YouthUploadDto={id:string;requestId:string;targetYouthId:string|null;state:'uploading'|'finalizing'|'ready'|'consumed'|'deleting'|'expired'|'deleted'|'purged';expiresAt:string;file:{originalName:string;mimeType:string;size:number}|null;consumed:{youthId:string;documentId:string;requestId:string}|null};
export type YouthFileCall=ResourceFileCall&{downloadBody?:Record<string,unknown>};
export type YouthFileAdapter<F>=Omit<ResourceFileAdapter<F>,'download'>&{download(endpoint:string,expected:Parameters<ResourceFileAdapter<F>['download']>[1],call:YouthFileCall):ReturnType<ResourceFileAdapter<F>['download']>};
export type YouthFilePickOptions=ResourceFilePickOptions;
export type SelectedYouthFile=Readonly<{name:string;size:number;release():void}>;
export type YouthFileScope={token:string;isCurrent?:()=>boolean;signal?:AbortSignal;onProgress?:(fraction:number|null)=>void};
export type YouthUploadOperation={prepare():Promise<void>;refresh():Promise<void>;readyUploadId():string|null;getState():{phase:string;busy:boolean;uncertain:boolean};cancel():void;discard():Promise<void>;release():void};
export type YouthDecisionTransfer={download():Promise<boolean>;save():Promise<string|null>;share():Promise<string|null>;isReady():boolean;cancel():void;release():void};
export function isYouthDecisionPolicy(v:unknown):v is YouthDecisionPolicy{return youthRecord(v)&&youthExact(v,['maxNewFileCount','maxFileSize','allowedExtensions'])&&v.maxNewFileCount===5&&v.maxFileSize===31457280&&Array.isArray(v.allowedExtensions)&&v.allowedExtensions.length>0&&v.allowedExtensions.every(x=>typeof x==='string'&&/^\.[a-z0-9]+$/.test(x))&&new Set(v.allowedExtensions).size===v.allowedExtensions.length;}
export function validateYouthDecisionFile(name:string,size:number,policy:{allowedExtensions:string[];maxFileSizeMb:number}){if(!name.trim()||name!==name.trim()||/[\x00-\x1f\x7f/\\]/.test(name)||name==='.'||name==='..'||new TextEncoder().encode(name).byteLength>1024)throw new ApiError('파일 이름을 확인하세요.',400);const extension=name.slice(name.lastIndexOf('.')).toLowerCase();if(!policy.allowedExtensions.includes(extension))throw new ApiError('허용된 확장자의 결정문을 선택하세요.',415);if(!Number.isSafeInteger(size)||size<1||size>policy.maxFileSizeMb*1024*1024)throw new ApiError('결정문 파일은 0바이트보다 크고 30MB 이하여야 합니다.',413);return name;}
export function isYouthUpload(v:unknown):v is YouthUploadDto{return youthRecord(v)&&youthExact(v,['id','requestId','targetYouthId','state','expiresAt','file','consumed'])&&youthId(v.id)&&youthId(v.requestId)&&(v.targetYouthId===null||youthId(v.targetYouthId))&&['uploading','finalizing','ready','consumed','deleting','expired','deleted','purged'].includes(String(v.state))&&isYouthTimestamp(v.expiresAt)&&(v.file===null?['consumed','deleting','expired','deleted','purged'].includes(String(v.state)):youthRecord(v.file)&&youthExact(v.file,['originalName','mimeType','size'])&&youthText(v.file.originalName)&&youthText(v.file.mimeType)&&youthInteger(v.file.size)&&v.file.size>0&&v.file.size<=31457280)&&(v.consumed===null||youthRecord(v.consumed)&&youthExact(v.consumed,['youthId','documentId','requestId'])&&youthId(v.consumed.youthId)&&youthId(v.consumed.documentId)&&youthId(v.consumed.requestId))&&(v.state==='consumed'?v.file===null&&v.consumed!==null:v.consumed===null);}
export function isYouthDocument(v:unknown):v is YouthDocument{return youthRecord(v)&&youthExact(v,['id','name','size','createdAt','updatedAt'])&&youthId(v.id)&&youthText(v.name)&&youthInteger(v.size)&&v.size>0&&isYouthTimestamp(v.createdAt)&&isYouthTimestamp(v.updatedAt);}
function abort(){return Object.assign(new Error('파일 요청을 취소했습니다.'),{name:'AbortError'});}
export function createYouthFileApi<F>(adapter:YouthFileAdapter<F>,request=youthRequest){
 let generation=0;const versions=new Map<string,number>(),owned=new Map<F,string>(),active=new Map<()=>void,string>(),registered=new Map<string,()=>void>(),timers=new Set<ReturnType<typeof setTimeout>>();
 type Entry={file:F;name:string;size:number;mimeType:string;token:string;epoch:string;busy:boolean;released:boolean;operation?:YouthUploadOperation;binding?:string};
 const selections=new WeakMap<SelectedYouthFile,Entry>(),entries=new Set<Entry>();
 const epoch=(token:string)=>`${generation}:${versions.get(token)??0}:${youthPrivacyGeneration(token)}`;
 const remove=(file:F)=>{owned.delete(file);adapter.release(file);};
 const register=(token:string)=>{if(!registered.has(token))registered.set(token,registerYouthResource(token,()=>clearYouthFileResources({expectedToken:token})));};
 function context(options:YouthFileScope,downloadBody?:Record<string,unknown>){register(options.token);const captured=epoch(options.token),controller=new AbortController(),callbacks=new Set<()=>void>();
  const cancel=()=>{controller.abort();for(const callback of [...callbacks])try{callback();}catch{}};active.set(cancel,options.token);options.signal?.addEventListener('abort',cancel,{once:true});if(options.signal?.aborted)cancel();
  const call:YouthFileCall={token:options.token,signal:controller.signal,downloadBody,check(){if(captured!==epoch(options.token)||controller.signal.aborted||options.isCurrent&&!options.isCurrent())throw abort();if(!options.token)throw new ApiError('로그인이 필요합니다.',401);},onProgress(value){call.check();options.onProgress?.(value);},onCancel(callback){callbacks.add(callback);if(controller.signal.aborted)callback();return()=>{callbacks.delete(callback);};}};
  return{call,cancel,finish(){active.delete(cancel);callbacks.clear();options.signal?.removeEventListener('abort',cancel);call.token='';}};
 }
 function selection(file:SelectedYouthFile,options:YouthFileScope){const entry=selections.get(file);if(!entry||entry.token!==options.token||entry.epoch!==epoch(options.token)||options.isCurrent&&!options.isCurrent())throw abort();return entry;}
 async function pickYouthDecisionFile(options:YouthFileScope&{policy:YouthDecisionPolicy}):Promise<SelectedYouthFile|null>{if(!isYouthDecisionPolicy(options.policy))throw new ApiError('결정문 정책을 확인하세요.',0);const op=context(options);let pending:F|undefined;try{const result=await adapter.pick({...options,policy:{maxFileCount:5,maxFileSizeMb:30,allowedExtensions:options.policy.allowedExtensions}},op.call);if(result){pending=result.file;owned.set(result.file,options.token);}op.call.check();if(!result)return null;const name=validateYouthDecisionFile(result.name,result.size,{maxFileSizeMb:30,allowedExtensions:options.policy.allowedExtensions});if(adapter.size(result.file)!==result.size)throw new ApiError('선택한 파일이 변경되었습니다.',0);const entry:Entry={...result,name,token:options.token,epoch:epoch(options.token),busy:false,released:false};
 const handle=Object.freeze({name,size:result.size,release(){entry.released=true;if(entry.operation||entry.busy)return;entries.delete(entry);selections.delete(handle);entry.token='';remove(entry.file);}});selections.set(handle,entry);entries.add(entry);pending=undefined;return handle;}
 catch(cause){if(isYouthFileCancellation(cause))return null;throw cause;}finally{if(pending!==undefined)remove(pending);op.finish();}}
 function discardYouthDecisionFile(file:SelectedYouthFile,options:YouthFileScope){const entry=selection(file,options);if(entry.busy)throw new ApiError('파일 처리 중에는 제거할 수 없습니다.',409);entry.operation?.cancel();entry.operation=undefined;entries.delete(entry);selections.delete(file);entry.token='';remove(entry.file);}
 function purgeYouthDecisionFile(file:SelectedYouthFile,options:YouthFileScope){const entry=selection(file,options);entry.operation?.cancel();entry.operation=undefined;entries.delete(entry);selections.delete(file);entry.token='';remove(entry.file);}
 function createYouthDecisionUpload(options:YouthFileScope&{file:SelectedYouthFile;targetYouthId:string|null;requestId:string}):YouthUploadOperation {
 const entry=selection(options.file,options),binding=JSON.stringify([options.targetYouthId,options.requestId]);if(!youthId(options.requestId)||options.targetYouthId!==null&&!youthId(options.targetYouthId))throw new ApiError('업로드 요청을 확인하세요.',400);if(entry.operation){if(entry.binding!==binding)throw new ApiError('원래 업로드 요청으로 확인하세요.',409);return entry.operation;}if(entry.released)throw new ApiError('파일을 다시 선택하세요.',0);
 let phase='selected',digest:string|undefined,upload:YouthUploadDto|undefined,putSent=false,uncertain=false,current:ReturnType<typeof context>|undefined;
 const check=()=>{selection(options.file,options);if(adapter.size(entry.file)!==entry.size)throw new ApiError('원래 파일의 사본이 변경되었습니다.',0);};
 const accept=(v:unknown)=>{if(!isYouthUpload(v)||v.requestId!==options.requestId||v.targetYouthId!==options.targetYouthId||upload&&v.id!==upload.id||v.file&&(v.file.originalName!==entry.name||v.file.mimeType!==entry.mimeType||v.file.size!==entry.size))throw new ApiError('원래 업로드와 응답이 일치하지 않습니다.',200);upload=v;phase=v.state;uncertain=false;};
 const json=async(path:string,method:'GET'|'POST'|'DELETE',body:unknown,call:YouthFileCall)=>{call.check();const value=await request<unknown>(path,call.token,{method,body,signal:call.signal,timeoutMs:120000});call.check();return value;};
 const read=async(call:YouthFileCall)=>{const value=await json(upload?`/youth/document-uploads/${upload.id}`:`/youth/document-uploads/requests/${options.requestId}`,'GET',undefined,call);if(!youthRecord(value)||!youthExact(value,['upload']))throw new ApiError('업로드 상태를 확인하지 못했습니다.',200);accept(value.upload);};
 async function work(action:'prepare'|'refresh'){check();if(entry.busy)throw new ApiError('파일 처리 중입니다.',409);entry.busy=true;const op=context(options);current=op;try{op.call.check();if(!digest){if(action==='refresh')throw new ApiError('업로드를 먼저 시작하세요.',0);phase='hashing';digest=(await adapter.hash(entry.file,op.call)).toLowerCase();check();op.call.check();if(!/^[a-f0-9]{64}$/.test(digest))throw new ApiError('전체 파일 검증을 완료하지 못했습니다.',0);}
 if(action==='refresh'){await read(op.call);return;}
 // Every resumed uncertain attempt inspects its original receipt first.
 if(uncertain){try{await read(op.call);}catch(cause){if(!(cause instanceof ApiError&&cause.status===404&&!upload))throw cause;}}
 if(!upload){uncertain=true;const value=await json('/youth/document-uploads','POST',{requestId:options.requestId,targetYouthId:options.targetYouthId,originalName:entry.name,mimeType:entry.mimeType,size:entry.size,wholeSha256:digest},op.call);if(!youthRecord(value)||!youthExact(value,['upload','replayed'])||typeof value.replayed!=='boolean')throw new ApiError('업로드 시작 결과를 확인하세요.',200);accept(value.upload);}
 if(!upload)throw new ApiError('업로드 요청을 확인하지 못했습니다.',200);
 if(upload.state==='ready'||upload.state==='consumed')return;
 if(['deleted','expired','deleting','purged'].includes(upload.state))throw new ApiError('이 업로드는 사용할 수 없습니다. 원래 결과를 확인하세요.',410);
 if(upload.state==='uploading'&&!putSent){uncertain=true;const value=await json(`/youth/document-uploads/${upload.id}/grant`,'POST',{},op.call);if(!youthRecord(value)||!youthExact(value,['upload','grant'])||!youthRecord(value.grant)||!youthExact(value.grant,['method','url','headers','signedExpiresAt'])||value.grant.method!=='PUT'||typeof value.grant.url!=='string'||!isYouthTimestamp(value.grant.signedExpiresAt)||!youthRecord(value.grant.headers)||!youthExact(value.grant.headers,['Content-Type'])||typeof value.grant.headers['Content-Type']!=='string')throw new ApiError('파일 전송 정보를 확인하지 못했습니다.',200);
 const url=new URL(value.grant.url);if(url.protocol!=='https:'||url.username||url.password||url.hash||Date.parse(value.grant.signedExpiresAt)<=Date.now())throw new ApiError('파일 전송 정보가 만료되었거나 올바르지 않습니다.',200);accept(value.upload);check();putSent=true;await adapter.put(entry.file,{method:'PUT',url:value.grant.url,headers:{'Content-Type':value.grant.headers['Content-Type']},expiresAt:value.grant.signedExpiresAt},op.call);op.call.check();check();}
 uncertain=true;const value=await json(`/youth/document-uploads/${upload.id}/complete`,'POST',{},op.call);if(!youthRecord(value)||!youthExact(value,['upload','pending'])||typeof value.pending!=='boolean')throw new ApiError('파일 준비 결과를 확인하지 못했습니다.',200);accept(value.upload);if(value.pending||phase==='finalizing'){uncertain=true;throw new ApiError('서버가 파일을 확인하고 있습니다. 같은 업로드 결과를 확인하세요.',202);}if(phase!=='ready'&&phase!=='consumed')throw new ApiError('파일 준비 결과를 확인하세요.',0);
 }catch(cause){if(cause instanceof ApiError&&cause.status===503&&cause.code==='UPLOAD_RETRY'){putSent=false;uncertain=false;phase='uploading';if(upload)upload={...upload,state:'uploading'};}throw cause;}finally{op.finish();if(current===op)current=undefined;entry.busy=false;}}
 const operation:YouthUploadOperation={prepare:()=>work('prepare'),refresh:()=>work('refresh'),readyUploadId(){try{check();return upload?.state==='ready'&&Date.parse(upload.expiresAt)>Date.now()?upload.id:null;}catch{return null;}},getState:()=>({phase,busy:entry.busy,uncertain}),cancel:()=>current?.cancel(),async discard(){check();if(entry.busy)throw new ApiError('파일 처리 중에는 제거할 수 없습니다.',409);if(!upload){discardYouthDecisionFile(options.file,options);return;}const op=context(options);try{const value=await json(`/youth/document-uploads/${upload.id}`,'DELETE',{},op.call);if(!youthRecord(value)||!youthExact(value,['upload']))throw new ApiError('업로드 제거 결과를 확인하세요.',200);accept(value.upload);if(!['deleting','deleted','expired','purged'].includes(phase))throw new ApiError('업로드 제거 결과를 확인하세요.',200);discardYouthDecisionFile(options.file,options);}finally{op.finish();}},release:()=>options.file.release()};entry.operation=operation;entry.binding=binding;return operation;
 }
 function createYouthDecisionTransfer(options:YouthFileScope&{document:YouthDocument;requestId:string;reason:'CASE_SUPPORT'|'EXTERNAL_SUBMISSION'|'INTERNAL_REVIEW'|'OTHER';reasonDetail?:string}):YouthDecisionTransfer{
 if(!isYouthDocument(options.document)||!youthId(options.requestId)||!['CASE_SUPPORT','EXTERNAL_SUBMISSION','INTERNAL_REVIEW','OTHER'].includes(options.reason)||options.reason==='OTHER'&&!options.reasonDetail?.trim()||(options.reasonDetail?.trim().length??0)>200)throw new ApiError('결정문과 다운로드 사유를 확인하세요.',400);
 const captured=epoch(options.token),body=Object.freeze({requestId:options.requestId,reason:options.reason,...(options.reasonDetail!==undefined?{reasonDetail:options.reasonDetail.trim()}:{})});let local:F|undefined,info:ResourceFileInfo|undefined,busy=false,released=false,shared=false,current:ReturnType<typeof context>|undefined;
 const check=()=>{if(captured!==epoch(options.token)||released||options.isCurrent&&!options.isCurrent())throw abort();};
 async function download(){check();if(busy)throw new ApiError('파일 처리 중입니다.',409);if(local!==undefined)return true;busy=true;const op=context(options,body);current=op;let pending:F|undefined;try{const result=await adapter.download(`/youth/decision-documents/${options.document.id}/download`,{id:options.document.id,name:options.document.name,mimeType:'application/octet-stream',size:options.document.size,previewKind:'unsupported'},op.call);pending=result.file;owned.set(result.file,options.token);op.call.check();check();if(adapter.size(result.file)!==options.document.size)throw new ApiError('파일 전체 크기가 일치하지 않습니다.',0);local=result.file;info=result.info;pending=undefined;return true;}catch(cause){if(isYouthFileCancellation(cause))return false;throw cause;}finally{if(pending!==undefined)remove(pending);op.finish();current=undefined;busy=false;}}
 async function exportFile(action:'save'|'share'){check();if(busy||local===undefined||!info)throw new ApiError('결정문을 먼저 완전히 내려받으세요.',0);busy=true;const op=context(options);current=op;try{const value=await adapter.export(local,info,action,op.call);op.call.check();check();if(value&&(action==='share'||value.includes('공유 창')))shared=true;return value;}finally{op.finish();current=undefined;busy=false;}}
 return{download,save:()=>exportFile('save'),share:()=>exportFile('share'),isReady(){try{check();return local!==undefined&&!busy;}catch{return false;}},cancel:()=>current?.cancel(),release(){if(released)return;released=true;current?.cancel();if(local!==undefined){const file=local;local=undefined;if(shared&&captured===epoch(options.token)){const timer=setTimeout(()=>{timers.delete(timer);if(owned.has(file))remove(file);},600000);timers.add(timer);}else remove(file);}}};
 }
 function clearYouthFileResources(options:{expectedToken?:string}={}):Promise<void>{if(options.expectedToken)versions.set(options.expectedToken,(versions.get(options.expectedToken)??0)+1);else{generation++;versions.clear();}
 for(const [cancel,token]of [...active])if(!options.expectedToken||token===options.expectedToken)cancel();for(const entry of [...entries])if(!options.expectedToken||entry.token===options.expectedToken){entry.operation?.cancel();entry.token='';entries.delete(entry);}for(const [file,token]of [...owned])if(!options.expectedToken||token===options.expectedToken)remove(file);for(const [token,off]of [...registered])if(!options.expectedToken||token===options.expectedToken){off();registered.delete(token);}if(!options.expectedToken){for(const timer of timers)clearTimeout(timer);timers.clear();return adapter.clear();}return Promise.resolve();}
 return{pickYouthDecisionFile,discardYouthDecisionFile,purgeYouthDecisionFile,createYouthDecisionUpload,createYouthDecisionTransfer,clearYouthFileResources};
}
